-- Tabla para almacenar solicitudes de recursos de grupos de extensión
CREATE TABLE
  deu.group_resource_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    group_id INTEGER NOT NULL REFERENCES deu.extension_groups (id) ON DELETE CASCADE,
    type VARCHAR NOT NULL,
    content TEXT,
    status deu.request_status_enum NOT NULL,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL
  );
