CREATE TYPE contract_type_enum AS ENUM ('inicial', 'adenda');

-- Tabla para almacenar los contratos/adendas legales de un proveedor
CREATE TABLE
  deu.provider_contracts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    provider_id INTEGER NOT NULL REFERENCES deu.providers (id) ON DELETE CASCADE,
    type contract_type_enum NOT NULL,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL
  );
