-- contraseña: nolodire
-- Insert mock data for users
-- user_id 1: eaguilar (root), 2: deu_admin1, 3: deu_admin2
-- user_id 4-14: one faculty_admin per faculty (excluding DEU/NA)
INSERT INTO
  deu.users (
    ci,
    email,
    first_name,
    last_name,
    date_of_birth,
    gender,
    education,
    address,
    password
  )
VALUES
  (
    100,
    'eaguilar@email.com',
    'Ellery',
    'Aguilar',
    '1988-09-03',
    'masculino',
    'universitaria_incompleta',
    'caracas',
    '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'
  ),
  (
    101,
    'deu_admin1@example.com',
    'Admin1',
    'Deu',
    '1980-01-01',
    'masculino',
    'universitaria_completa',
    'UCV',
    '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'
  ),
  (
    102,
    'deu_admin2@example.com',
    'Admin2',
    'Deu',
    '1982-02-02',
    'masculino',
    'universitaria_completa',
    'UCV',
    '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'
  ),
  (
    103,
    'coordinador_agronomia@extension.ucv.ve',
    'Admin',
    'Agronomía',
    '2000-01-01',
    'masculino',
    'universitaria_completa',
    'UCV',
    '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'
  ),
  (
    104,
    'coordinador_arquitectura@extension.ucv.ve',
    'Admin',
    'Arquitectura y Urbanismo',
    '2000-01-01',
    'masculino',
    'universitaria_completa',
    'UCV',
    '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'
  ),
  (
    105,
    'coordinador_ciencias@extension.ucv.ve',
    'Admin',
    'Ciencias',
    '2000-01-01',
    'masculino',
    'universitaria_completa',
    'UCV',
    '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'
  ),
  (
    106,
    'coordinador_fases@extension.ucv.ve',
    'Admin',
    'Ciencias Económicas y Sociales',
    '2000-01-01',
    'masculino',
    'universitaria_completa',
    'UCV',
    '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'
  ),
  (
    107,
    'coordinador_ciencias_politicas@extension.ucv.ve',
    'Admin',
    'Ciencias Jurídicas y Políticas',
    '2000-01-01',
    'masculino',
    'universitaria_completa',
    'UCV',
    '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'
  ),
  (
    108,
    'coordinador_veterinaria@extension.ucv.ve',
    'Admin',
    'Ciencias Veterinarias',
    '2000-01-01',
    'masculino',
    'universitaria_completa',
    'UCV',
    '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'
  ),
  (
    109,
    'coordinador_farmacia@extension.ucv.ve',
    'Admin',
    'Farmacia',
    '2000-01-01',
    'masculino',
    'universitaria_completa',
    'UCV',
    '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'
  ),
  (
    110,
    'coordinador_humanidades@extension.ucv.ve',
    'Admin',
    'Humanidades y Educación',
    '2000-01-01',
    'masculino',
    'universitaria_completa',
    'UCV',
    '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'
  ),
  (
    111,
    'coordinador_ingenieria@extension.ucv.ve',
    'Admin',
    'Ingeniería',
    '2000-01-01',
    'masculino',
    'universitaria_completa',
    'UCV',
    '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'
  ),
  (
    112,
    'coordinador_medicina@extension.ucv.ve',
    'Admin',
    'Medicina',
    '2000-01-01',
    'masculino',
    'universitaria_completa',
    'UCV',
    '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'
  ),
  (
    113,
    'coordinador_odontologia@extension.ucv.ve',
    'Admin',
    'Odontología',
    '2000-01-01',
    'masculino',
    'universitaria_completa',
    'UCV',
    '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'
  );
