--- Grupos de Extensión
-- Tabla para almacenar información de grupos de extensión
CREATE TABLE
  deu.extension_groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    user_id INTEGER NOT NULL REFERENCES deu.users (id) ON DELETE CASCADE, -- Usuario que creó el grupo
    name VARCHAR,
    description TEXT,
    is_multidisciplinary BOOLEAN DEFAULT FALSE, -- Grupo normal o multidisciplinario
    faculty deu.faculty_enum[] DEFAULT ARRAY['DEU']::deu.faculty_enum[], -- Facultad responsable del grupo
    foundation DATE, -- Fecha de Fundación del Grupo
    objective TEXT,
    code VARCHAR, -- Código asignado por la DEU
    group_director VARCHAR, -- Director del grupo de extensión
    type VARCHAR[] DEFAULT ARRAY[]::VARCHAR[], -- Tipo de grupo (por ejemplo, académico, cultural, deportivo)
    location VARCHAR,
    is_active BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL
  );
