-- Tabla para almacenar relaciones usuario-rol
CREATE TABLE
  deu.user_roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    user_id INTEGER NOT NULL REFERENCES deu.users (id) ON DELETE CASCADE,
    role_id INTEGER NOT NULL REFERENCES deu.roles (id) ON DELETE CASCADE,
    domain_type TEXT NOT NULL CHECK (domain_type IN ('course', 'group', 'all')),
    faculty deu.faculty_enum NULL,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL,
    UNIQUE (user_id, role_id)
  );
