CREATE TYPE deu.education_level_enum AS ENUM (
  'bachiller',
  'universitaria_incompleta',
  'universitaria_completa',
  'posgrado'
);

-- Tabla para almacenar información de usuarios
CREATE TABLE
  deu.users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    ci INTEGER UNIQUE,
    email VARCHAR UNIQUE NOT NULL,
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL,
    date_of_birth DATE,
    gender VARCHAR,
    education deu.education_level_enum DEFAULT 'bachiller' NOT NULL,
    address VARCHAR,
    password CHAR(60) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL
  );
