CREATE TYPE deu.request_status_enum AS ENUM ('under_review', 'rejected', 'approved');

-- Tabla para almacenar información de solicitudes de aval
CREATE TABLE
  deu.course_auth_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    course_id INTEGER NOT NULL REFERENCES deu.courses (id) ON DELETE CASCADE,
    status deu.request_status_enum DEFAULT 'under_review' NOT NULL,
    reviewer_id INTEGER DEFAULT NULL REFERENCES deu.users (id) ON DELETE CASCADE, -- ID de la cuenta de administrador que revisa la solicitud
    comments TEXT,
    reviewed_at TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL
  );
