-- Registro de recordatorios enviados por el servicio notifier. Permite no repetir un recordatorio
-- (mismo kind, target y destinatario) hasta que pase el intervalo de reenvío.
CREATE TABLE
  deu.notifications_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    kind VARCHAR NOT NULL, -- Tipo de recordatorio (coordinator_pending_requests, group_renewal)
    target VARCHAR NOT NULL, -- Entidad a la que se refiere (código de facultad, id del grupo)
    recipient TEXT NOT NULL, -- Correo al que se envió
    sent_at TIMESTAMP DEFAULT NOW () NOT NULL
  );

CREATE INDEX notifications_log_lookup_idx ON deu.notifications_log (kind, target, recipient, sent_at DESC);
