CREATE SCHEMA IF NOT EXISTS deu;

GRANT ALL PRIVILEGES ON DATABASE deu TO deu_admin;

GRANT ALL PRIVILEGES ON SCHEMA deu TO deu_admin;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA deu TO deu_admin;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA deu TO deu_admin;

ALTER SCHEMA deu OWNER TO deu_admin;
