-- Tabla para solicitudes de registro de proveedores
CREATE TABLE
  deu.provider_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    provider_id INTEGER NOT NULL REFERENCES deu.providers (id) ON DELETE CASCADE,
    status deu.request_status_enum DEFAULT 'under_review' NOT NULL,
    reviewer_id INTEGER DEFAULT NULL REFERENCES deu.users (id) ON DELETE SET NULL,
    comments TEXT,
    reviewed_at TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL
  );
