-- Solicitudes de renovación anual de grupos de extensión. El usuario del grupo envía de nuevo
-- todos los datos del grupo (mismo formulario que al crearlo); se guardan en payload y solo
-- reemplazan los datos del grupo cuando todas sus solicitudes de aval (group_auth_requests con
-- este renewal_id) son aprobadas. Los archivos propuestos se guardan en deu.files con
-- owner_type 'group_renewal'.
CREATE TABLE
  deu.group_renewals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    group_id INTEGER NOT NULL REFERENCES deu.extension_groups (id) ON DELETE CASCADE,
    payload JSONB NOT NULL, -- Datos propuestos del grupo y sus miembros
    submitted_by INTEGER REFERENCES deu.users (id) ON DELETE SET NULL,
    status deu.request_status_enum DEFAULT 'under_review' NOT NULL,
    reviewed_at TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP DEFAULT NOW () NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW () NOT NULL
  );

-- Una sola renovación en revisión por grupo.
CREATE UNIQUE INDEX group_renewals_one_pending_idx ON deu.group_renewals (group_id)
WHERE
  status = 'under_review';

-- NULL: solicitud de creación del grupo. No NULL: solicitud de aval de esa renovación.
ALTER TABLE deu.group_auth_requests
ADD COLUMN renewal_id INTEGER DEFAULT NULL REFERENCES deu.group_renewals (id) ON DELETE CASCADE;

ALTER TABLE deu.files DROP CONSTRAINT IF EXISTS files_owner_type_check;
ALTER TABLE deu.files ADD CONSTRAINT files_owner_type_check CHECK (
  owner_type IN (
    'course',
    'group',
    'group_activity',
    'course_cycle',
    'provider',
    'user',
    'group_member',
    'course_cycle_close_request',
    'provider_contract',
    'course_request',
    'group_renewal'
  )
);
