// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/eaguilar88/deu/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSigner creates a new instance of MockSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSigner {
	mock := &MockSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSigner is an autogenerated mock type for the Signer type
type MockSigner struct {
	mock.Mock
}

type MockSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSigner) EXPECT() *MockSigner_Expecter {
	return &MockSigner_Expecter{mock: &_m.Mock}
}

// GenerateJWT provides a mock function for the type MockSigner
func (_mock *MockSigner) GenerateJWT(userID string, roles []entities.UserRole, providerCode string) (string, error) {
	ret := _mock.Called(userID, roles, providerCode)

	if len(ret) == 0 {
		panic("no return value specified for GenerateJWT")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []entities.UserRole, string) (string, error)); ok {
		return returnFunc(userID, roles, providerCode)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []entities.UserRole, string) string); ok {
		r0 = returnFunc(userID, roles, providerCode)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, []entities.UserRole, string) error); ok {
		r1 = returnFunc(userID, roles, providerCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSigner_GenerateJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateJWT'
type MockSigner_GenerateJWT_Call struct {
	*mock.Call
}

// GenerateJWT is a helper method to define mock.On call
//   - userID string
//   - roles []entities.UserRole
//   - providerCode string
func (_e *MockSigner_Expecter) GenerateJWT(userID interface{}, roles interface{}, providerCode interface{}) *MockSigner_GenerateJWT_Call {
	return &MockSigner_GenerateJWT_Call{Call: _e.mock.On("GenerateJWT", userID, roles, providerCode)}
}

func (_c *MockSigner_GenerateJWT_Call) Run(run func(userID string, roles []entities.UserRole, providerCode string)) *MockSigner_GenerateJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []entities.UserRole
		if args[1] != nil {
			arg1 = args[1].([]entities.UserRole)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(arg0, arg1, arg2)
	})
	return _c
}

func (_c *MockSigner_GenerateJWT_Call) Return(s string, err error) *MockSigner_GenerateJWT_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSigner_GenerateJWT_Call) RunAndReturn(run func(userID string, roles []entities.UserRole, providerCode string) (string, error)) *MockSigner_GenerateJWT_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function for the type MockSigner
func (_mock *MockSigner) ValidateToken(tokenString string) (map[string]any, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 map[string]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (map[string]any, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) map[string]any); ok {
		r0 = returnFunc(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSigner_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockSigner_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockSigner_Expecter) ValidateToken(tokenString interface{}) *MockSigner_ValidateToken_Call {
	return &MockSigner_ValidateToken_Call{Call: _e.mock.On("ValidateToken", tokenString)}
}

func (_c *MockSigner_ValidateToken_Call) Run(run func(tokenString string)) *MockSigner_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(arg0)
	})
	return _c
}

func (_c *MockSigner_ValidateToken_Call) Return(stringToV map[string]any, err error) *MockSigner_ValidateToken_Call {
	_c.Call.Return(stringToV, err)
	return _c
}

func (_c *MockSigner_ValidateToken_Call) RunAndReturn(run func(tokenString string) (map[string]any, error)) *MockSigner_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}
