openapi: 3.0.0
info:
  title: DEU UCV API
  description: API del proyecto DEU UCV
  contact: { }
  version: "{{ .AppVersion }}"
paths:
  /:
    get:
      tags:
        - "sasa"
      summary: Foo
      responses:
        200:
          description: "Documentation"