# Use the official PostgreSQL image for version 16 on Alpine Linux
FROM postgres:16-alpine

# Optionally, you can add additional configuration or customization here
# For example, you can copy initialization scripts or configuration files
# from your host machine to the container.


EXPOSE 5432