-- https://dbdiagram.io/d/EDC-Tesis-EA-65bc1bacac844320ae437e82
CREATE SCHEMA IF NOT EXISTS deu;

-- Crear el usuario 'deu_admin' con acceso completo
GRANT ALL PRIVILEGES ON DATABASE deu TO deu_admin;
GRANT ALL PRIVILEGES ON SCHEMA deu TO deu_admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA deu TO deu_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA deu TO deu_admin;
ALTER SCHEMA deu OWNER TO deu_admin;

SET search_path TO deu;

CREATE TYPE education_level_enum AS ENUM (
  'bachiller',
  'universitaria_incompleta',
  'universitaria_completa',
  'posgrado'
);

-- Definir tablas

-- Tabla para almacenar información de usuarios
CREATE TABLE deu.users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  ci INTEGER UNIQUE NOT NULL,
  username VARCHAR UNIQUE NOT NULL,
  first_name VARCHAR NOT NULL,
  last_name VARCHAR NOT NULL,
  date_of_birth DATE,
  gender VARCHAR,
  education education_level_enum NOT NULL,
  address VARCHAR,
  password CHAR(60) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL
);

-- Tabla para almacenar información de roles
CREATE TABLE deu.roles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  name VARCHAR UNIQUE NOT NULL,
  description TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL
);

-- Tabla para almacenar relaciones usuario-rol
CREATE TABLE deu.user_roles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL REFERENCES deu.users(id) ON DELETE CASCADE,
  role_id INTEGER NOT NULL REFERENCES deu.roles(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL,
  UNIQUE (user_id, role_id)
);

CREATE TYPE request_status_enum AS ENUM (
  'created',
  'under_review',
  'rejected',
  'approved'
);


CREATE TYPE entity_type_enum AS ENUM (
  'course',
  'extension_group'
);

-- Tabla para almacenar información de solicitudes de aval
CREATE TABLE deu.requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL REFERENCES deu.users(id) ON DELETE CASCADE,
  type entity_type_enum NOT NULL,
  name VARCHAR,
  description TEXT,
  status request_status_enum DEFAULT 'created' NOT NULL,
  reviewer_id INTEGER DEFAULT NULL REFERENCES deu.users(id) ON DELETE CASCADE, -- ID de la cuenta de administrador que revisa la solicitud
  comments TEXT,
  reviewed_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL
);

-- Tabla para almacenar información de documentos de solicitudes
CREATE TABLE deu.request_documents (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  request_id INTEGER NOT NULL REFERENCES deu.requests(id) ON DELETE CASCADE,
  path VARCHAR,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL
);

-- Tabla para almacenar información de entidades
CREATE TABLE deu.entities (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  name VARCHAR,
  description TEXT,
  user_id INTEGER NOT NULL REFERENCES deu.users(id) ON DELETE CASCADE, -- ID del usuario que creó esta entidad de solicitud
  endorsement_id INTEGER REFERENCES deu.requests(id) ON DELETE SET NULL, -- ID de la solicitud utilizada para el aval
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL
);

-- Tabla para almacenar información de grupos de extensión
CREATE TABLE deu.extension_groups (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  entity_id INTEGER NOT NULL REFERENCES deu.entities(id) ON DELETE CASCADE,
  name VARCHAR,
  description TEXT,
  objective TEXT,
  action TEXT,
  reach TEXT,
  path VARCHAR
);

-- Tabla para almacenar información de cursos
CREATE TABLE deu.courses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  entity_id INTEGER NOT NULL REFERENCES deu.entities(id) ON DELETE CASCADE,
  objectives TEXT,
  content TEXT,
  cost FLOAT,
  location VARCHAR
);

-- Tabla para almacenar información de ciclos de cursos
CREATE TABLE deu.course_cycles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  course_id INTEGER NOT NULL REFERENCES deu.courses(id),
  start_date DATE,
  end_date DATE,
  inscription_date DATE,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL
);

CREATE TYPE course_participant_status_enum AS ENUM (
  'abandoned',
  'approved',
  'failed'
);

-- Tabla para almacenar información de participantes de cursos
CREATE TABLE deu.course_participants (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL REFERENCES deu.users(id) ON DELETE CASCADE,
  course_cycle_id INTEGER NOT NULL REFERENCES deu.course_cycles(id),
  participant_status course_participant_status_enum,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL,
  UNIQUE (user_id, course_cycle_id)
);

-- Tabla para almacenar información de actividades
CREATE TABLE deu.activities (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  name VARCHAR,
  group_id INTEGER REFERENCES deu.extension_groups(id) ON DELETE SET NULL,
  description TEXT,
  date DATE,
  path VARCHAR,
  location VARCHAR,
  assistants INTEGER,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL
);

-- Tabla para almacenar información de proveedores. Un proveedor es aquel que tiene código de proveedor asignado por la DEU.
-- Únicamente los coordinadores de cursos y los representantes de grupos de extensión pueden ser proveedores
CREATE TABLE deu.providers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL REFERENCES deu.users(id) ON DELETE CASCADE,
  code VARCHAR,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL,
  CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES deu.users(id) ON DELETE CASCADE
);

CREATE TYPE contact_type_enum AS ENUM (
  'email',
  'phone'
);

CREATE TYPE owner_type_enum AS ENUM (
  'user',
  'provider'
);

-- Crear la tabla de contactos con las restricciones y tipos adecuados
-- Tabla para almacenar información de contactos
CREATE TABLE contacts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    contact_type contact_type_enum NOT NULL DEFAULT 'email',
    contact_value TEXT NOT NULL,
    owner_type owner_type_enum NOT NULL,
    owner_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMP DEFAULT NULL,
    CONSTRAINT unique_contact_per_owner UNIQUE (contact_type, contact_value, owner_type, owner_id),
    CONSTRAINT fk_user FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Comentarios
COMMENT ON TABLE deu.roles IS 'Roles incluyen: root, admin, coordinador, facilitador, estudiante, extension';
COMMENT ON COLUMN contacts.contact_type IS 'Tipo de contacto: ya sea ''email'' o ''phone''';
COMMENT ON COLUMN contacts.contact_value IS 'El valor real del contacto (por ejemplo, una dirección de correo electrónico o un número de teléfono)';
COMMENT ON COLUMN contacts.owner_type IS 'El tipo de entidad que posee el contacto (''user'' o ''provider'')';
COMMENT ON COLUMN contacts.owner_id IS 'El ID del usuario o proveedor que posee el contacto';
COMMENT ON COLUMN contacts.created_at IS 'Marca de tiempo de cuando se creó la entrada de contacto';

-- Insertar datos iniciales
INSERT INTO deu.roles (name, description) VALUES
  ('root', 'Superusuario con acceso total al sistema.'),
  ('super-admin', 'Administrador con privilegios elevados.'),
  ('evaluador', 'Responsable de evaluar solicitudes de avales de cursos y grupos de extension. Puede ser por escuela o de la DEU'),
  ('coordinador', 'Representante de un ente que imparte diplomados.'),
  ('facilitador', 'Encargado de impartir cursos y talleres.'),
  ('estudiante', 'Participante inscrito en cursos.'),
  ('grupo', 'Grupo o departamento de extensión.');

-- contraseña: nolodire
INSERT INTO deu.users (ci, username, first_name, last_name, date_of_birth, gender, education, address, password) VALUES
  (11111111, 'eaguilar@email.com', 'Ellery', 'Aguilar', '1988-09-03', 'masculino', 'universitaria_incompleta', 'caracas', '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'),
   (22222222, 'john.doe@email.com', 'John', 'Doe', '2000-01-25', 'masculino', 'universitaria_completa', 'Av Boyacá, Residencias Gran Mariscal', '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa');

INSERT INTO deu.user_roles (user_id, role_id) VALUES
  (1, 2),
  (2, 4);

  INSERT INTO deu.requests (user_id, type, name, description, status, reviewer_id, comments, reviewed_at) VALUES
    (2, 'course', 'Curso de SQL', 'Curso avanzado de SQL para desarrolladores', 'approved', 1, 'Aprobado por el administrador', NOW());

  INSERT INTO deu.entities (name, description, user_id, endorsement_id) VALUES
    ('Curso de SQL', 'Curso avanzado de SQL para desarrolladores', 2, 1);

  INSERT INTO deu.courses (entity_id, objectives, content, cost, location) VALUES
    (1, 'Aprender SQL avanzado', 'SELECT, JOIN, INDEXES, etc.', 100.0, 'Online');

  INSERT INTO deu.course_cycles (course_id, start_date, end_date, inscription_date) VALUES
    (1, '2023-11-01', '2023-12-01', '2023-10-15');

  INSERT INTO deu.course_participants (user_id, course_cycle_id, participant_status) VALUES
    (1, 1, 'approved');

  INSERT INTO deu.extension_groups (entity_id, name, description, objective, action, reach, path) VALUES
    (1, 'Grupo de SQL', 'Grupo de estudio de SQL', 'Aprender SQL avanzado', 'Estudiar en grupo', 'Online', 'https://meet.google.com/');