CREATE SCHEMA IF NOT EXISTS "deu";

-- Create the 'deu_admin' user with full accessqw
GRANT ALL PRIVILEGES ON DATABASE deu TO deu_admin;
GRANT ALL PRIVILEGES ON SCHEMA deu TO deu_admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA deu TO deu_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA deu TO deu_admin;
ALTER SCHEMA deu OWNER TO deu_admin;

SET search_path TO deu;

-- Create ENUM types
CREATE TYPE "provider_type" AS ENUM (
  'user',
  'extension_group'
);

CREATE TYPE "education_level" AS ENUM (
  'bachiller',
  'universitaria_incompleta',
  'universitaria_completa',
  'posgrado'
);

CREATE TYPE "request_status" AS ENUM (
  'created',
  'under_review',
  'rejected',
  'approved'
);

CREATE TYPE "contact_type" AS ENUM (
  'user',
  'course',
  'extension_group'
);

CREATE TYPE "course_participant_status" AS ENUM (
  'abandoned',
  'approved',
  'failed'
);

CREATE TYPE "user_role" AS ENUM (
  'root', 
  'admin', 
  'coordinador', 
  'facilitador', 
  'estudiante', 
  'extensión'
);

CREATE TYPE "entity_type" AS ENUM (
  'course',
  'extension_group'
);

-- Define tables
CREATE TABLE "deu"."users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "ci" INTEGER UNIQUE NOT NULL,
  "username" VARCHAR UNIQUE NOT NULL,
  "first_name" VARCHAR NOT NULL,
  "last_name" VARCHAR NOT NULL,
  "date_of_birth" DATE,
  "gender" VARCHAR,
  "education" education_level NOT NULL,
  "address" VARCHAR,
  "provider_code" VARCHAR(50),
  "created_at" TIMESTAMP DEFAULT (now()),
  "updated_at" TIMESTAMP DEFAULT (now()),
  "password" CHAR(60) NOT NULL
);

CREATE TABLE "deu"."roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" VARCHAR UNIQUE NOT NULL,
  "description" TEXT,
  "created_at" TIMESTAMP DEFAULT (now()),
  "updated_at" TIMESTAMP DEFAULT (now())
);

CREATE TABLE "deu"."user_roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" INTEGER NOT NULL REFERENCES deu.users(id) ON DELETE CASCADE,
  "role_id" INTEGER NOT NULL REFERENCES deu.roles(id) ON DELETE CASCADE,
  UNIQUE ("user_id", "role_id")
);

CREATE TABLE "deu"."requests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" INTEGER NOT NULL REFERENCES deu.users(id) ON DELETE CASCADE,
  "type" entity_type NOT NULL,
  "name" VARCHAR,
  "description" TEXT,
  "status" request_status DEFAULT 'created' NOT NULL,
  "comments" TEXT,
  "created_at" TIMESTAMP DEFAULT (now()),
  "updated_at" TIMESTAMP DEFAULT (now())
);

CREATE TABLE "deu"."request_documents" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "request_id" INTEGER NOT NULL REFERENCES deu.requests(id) ON DELETE CASCADE,
  "path" VARCHAR,
  "created_at" TIMESTAMP DEFAULT (now()),
  "updated_at" TIMESTAMP DEFAULT (now())
);

CREATE TABLE "deu"."entities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" VARCHAR,
  "description" TEXT,
  "user_id" INTEGER NOT NULL REFERENCES deu.users(id) ON DELETE CASCADE, -- ID of the user associated with the entity
  "endorsement_id" INTEGER REFERENCES deu.requests(id) ON DELETE CASCADE, -- ID of the request used for endorsement
  "endorsed_by" VARCHAR REFERENCES deu.users(id) ON DELETE SET NULL, -- ID of the administrator account that approved the request
  "created_at" TIMESTAMP DEFAULT (now()),
  "updated_at" TIMESTAMP DEFAULT (now())
);

CREATE TABLE "deu"."providers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "entity_id" INTEGER NOT NULL,
  "entity_type" provider_type NOT NULL,
  "registration_date" DATE,
  "code" VARCHAR,
  "created_at" TIMESTAMP DEFAULT (now()),
  "updated_at" TIMESTAMP DEFAULT (now())
);

CREATE TABLE "deu"."extension_groups" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" VARCHAR,
  "description" TEXT,
  "objective" TEXT,
  "action" TEXT,
  "reach" TEXT,
  "path" VARCHAR
);

CREATE TABLE "deu"."courses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "objectives" TEXT,
  "content" TEXT,
  "cost" FLOAT,
  "location" VARCHAR,
  "created_at" TIMESTAMP DEFAULT (now()),
  "updated_at" TIMESTAMP DEFAULT (now())
);

CREATE TABLE "deu"."contact_info" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "entity_id" INTEGER,
  "entity_type" contact_type,
  "email" VARCHAR,
  "phone" VARCHAR,
  FOREIGN KEY ("entity_id") REFERENCES deu.users(id),
  FOREIGN KEY ("entity_id") REFERENCES deu.courses(id),
  FOREIGN KEY ("entity_id") REFERENCES deu.extension_groups(id)
);

CREATE TABLE "deu"."course_cycles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "course_id" INTEGER NOT NULL REFERENCES deu.courses(id),
  "start_date" DATE,
  "end_date" DATE,
  "inscription_date" DATE,
  "created_at" TIMESTAMP DEFAULT (now()),
  "updated_at" TIMESTAMP DEFAULT (now())
);

CREATE TABLE "deu"."course_participants" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" INTEGER NOT NULL REFERENCES deu.users(id) ON DELETE CASCADE,
  "course_cycle_id" INTEGER NOT NULL REFERENCES deu.course_cycles(id),
  "participant_status" course_participant_status,
  "created_at" TIMESTAMP DEFAULT (now()),
  "updated_at" TIMESTAMP DEFAULT (now()),
  UNIQUE ("user_id", "course_cycle_id")
);

CREATE TABLE "deu"."activities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" VARCHAR,
  "description" TEXT,
  "date" DATE,
  "path" VARCHAR,
  "location" VARCHAR,
  "assistants" INTEGER
);

-- Comments
COMMENT ON TABLE "deu"."roles" IS 'Roles include: root, admin, coordinador, facilitador, estudiante, extension';

-- Insert initial data
INSERT INTO deu.roles (name, description) VALUES
  ('root', 'Superusuario con acceso total al sistema.'),
  ('admin', 'Administrador con privilegios elevados.'),
  ('coordinador', 'Representante de un ente que imparte diplomados.'),
  ('facilitador', 'Encargado de impartir cursos y talleres.'),
  ('estudiante', 'Participante inscrito en cursos.'),
  ('extensión', 'Grupo o departamento de extensión.');

INSERT INTO deu.users (ci, username, first_name, last_name, date_of_birth, gender, education, address, password) VALUES
  (183245415, 'eaguilar@email.com', 'Ellery', 'Aguilar', '1988-09-03', 'masculino', 'universitaria_incompleta', 'caracas', '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa');

INSERT INTO deu.user_roles (user_id, role_id) VALUES
  (1, 2);