-- https://dbdiagram.io/d/EDC-Tesis-EA-65bc1bacac844320ae437e82
CREATE SCHEMA IF NOT EXISTS deu;

-- Crear el usuario 'deu_admin' con acceso completo
GRANT ALL PRIVILEGES ON DATABASE deu TO deu_admin;

GRANT ALL PRIVILEGES ON SCHEMA deu TO deu_admin;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA deu TO deu_admin;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA deu TO deu_admin;

ALTER SCHEMA deu OWNER TO deu_admin;

SET
  search_path TO deu;

CREATE TYPE education_level_enum AS ENUM (
  'bachiller',
  'universitaria_incompleta',
  'universitaria_completa',
  'posgrado'
);

-- Definir tablas
-- Tabla para almacenar información de usuarios
CREATE TABLE
  deu.users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    ci INTEGER UNIQUE,
    email VARCHAR UNIQUE NOT NULL, -- Cambiado de username a email
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL,
    date_of_birth DATE,
    gender VARCHAR,
    education education_level_enum DEFAULT 'bachiller'  NOT NULL,
    address VARCHAR,
    password CHAR(60) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL
  );

-- Tabla para almacenar información de proveedores. Un proveedor es aquel que tiene código de proveedor asignado por la DEU.
-- Únicamente los coordinadores de cursos y los representantes de grupos de extensión pueden ser proveedores
CREATE TABLE
  deu.providers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    user_id INTEGER NOT NULL REFERENCES deu.users (id) ON DELETE CASCADE,
    name VARCHAR,
    party_type VARCHAR CHECK (party_type IN ('natural', 'juridical')),
    profit_type VARCHAR NOT NULL CHECK (profit_type IN ('lucrativo', 'no_lucrativo')),
    is_internal BOOLEAN,
    bio text,
    code VARCHAR,
    is_active BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL
  );

-- Tabla para almacenar información de roles
CREATE TABLE
  deu.roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR UNIQUE NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL
  );

-- Tabla para almacenar relaciones usuario-rol
CREATE TABLE
  deu.user_roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    user_id INTEGER NOT NULL REFERENCES deu.users (id) ON DELETE CASCADE,
    role_id INTEGER NOT NULL REFERENCES deu.roles (id) ON DELETE CASCADE,
    domain_type TEXT NOT NULL CHECK (domain_type IN ('course', 'group', 'all')),
    faculty faculty_enum NULL,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL,
    UNIQUE (user_id, role_id)
  );

CREATE TYPE faculty_enum AS ENUM (
  'Agronomía',
  'Arquitectura y Urbanismo',
  'Ciencias',
  'Ciencias Económicas y Sociales',
  'Ciencias Jurídicas y Políticas',
  'Ciencias Veterinarias',
  'Farmacia',
  'Humanidades y Educación',
  'Ingeniería',
  'Medicina',
  'Odontología',
  'DEU'
);

CREATE TYPE request_status_enum AS ENUM ('created', 'under_review', 'rejected', 'approved');

CREATE TYPE resource_request_status_enum AS ENUM ('under_review', 'approved', 'rejected');

CREATE TYPE course_location_enum AS ENUM ('online', 'in_site', 'mixed');

CREATE TYPE course_type_enum AS ENUM (
  'unassigned',
  'skill_development',
  'life_skills',
  'technical_training'
);

-- Tabla para almacenar información de cursos
CREATE TABLE
  deu.courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR,
    description TEXT, --descripcion
    provider_id INTEGER NOT NULL REFERENCES deu.providers (id) ON DELETE CASCADE, -- ID del proveedor que creó esta entidad de solicitud
    objectives TEXT, --objetivos
    rationale TEXT, -- fundamentacion
    duration VARCHAR, -- duracion
    cost VARCHAR, -- estructura_costos
    instructor_profile TEXT, -- perfil_docente
    profiles TEXT, -- perfiles
    requirements TEXT, -- exigencias
    content TEXT, -- estructura_curricular
    evaluation TEXT, -- evaluacion
    schedule TEXT, -- cronograma
    type course_type_enum DEFAULT 'unassigned', -- Tipo de curso (Formación para el trabajo, Formación técnica/profesional, Formación para toda la vida)
    faculty faculty_enum DEFAULT 'DEU', -- facultad
    location course_location_enum, -- ubicacion
    is_active BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL
  );

-- Tabla para almacenar información de solicitudes de aval
CREATE TABLE
  deu.course_auth_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    course_id INTEGER NOT NULL REFERENCES deu.courses (id) ON DELETE CASCADE,
    status request_status_enum DEFAULT 'under_review' NOT NULL,
    reviewer_id INTEGER DEFAULT NULL REFERENCES deu.users (id) ON DELETE CASCADE, -- ID de la cuenta de administrador que revisa la solicitud
    comments TEXT,
    reviewed_at TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL
  );

-- Tabla para almacenar información de ciclos de cursos
CREATE TABLE
  deu.course_cycles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    course_id INTEGER NOT NULL REFERENCES deu.courses (id),
    start_date DATE,
    end_date DATE,
    inscription_date DATE,
    is_active BOOLEAN DEFAULT TRUE,
    closed_at TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL
  );

CREATE TABLE
  deu.course_cycle_announcements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    course_cycle_id INTEGER NOT NULL REFERENCES deu.course_cycles (id) ON DELETE CASCADE,
    title VARCHAR,
    content TEXT,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL
  );

CREATE TYPE visitante_status_enum AS ENUM ('approved', 'abandoned', 'failed', 'ongoing');

-- Tabla para almacenar información de participantes de cursos
CREATE TABLE
  deu.visitantes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    user_id INTEGER NOT NULL REFERENCES deu.users (id) ON DELETE CASCADE,
    course_cycle_id INTEGER NOT NULL REFERENCES deu.course_cycles (id),
    participant_status visitante_status_enum,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL,
    UNIQUE (user_id, course_cycle_id)
  );

--- Grupos de Extensión
-- Tabla para almacenar información de grupos de extensión
CREATE TABLE
  deu.extension_groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    user_id INTEGER NOT NULL REFERENCES deu.users (id) ON DELETE CASCADE, -- Usuario que creó el grupo
    name VARCHAR,
    description TEXT,
    faculty faculty_enum DEFAULT 'DEU', -- Facultad responsable del grupo
    objective TEXT,
    code VARCHAR, -- Código asignado por la DEU
    group_director VARCHAR, -- Director del grupo de extensión
    type VARCHAR, -- Tipo de grupo (por ejemplo, académico, cultural, deportivo)
    location VARCHAR,
    is_active BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL
  );

-- Tabla para almacenar información de proyectos de grupos de extensión
CREATE TABLE
  deu.group_auth_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    group_id INTEGER NOT NULL REFERENCES deu.extension_groups (id) ON DELETE CASCADE,
    status request_status_enum DEFAULT 'under_review' NOT NULL,
    faculty faculty_enum DEFAULT 'DEU' NOT NULL, -- Facultad responsable de evaluar la solicitud
    reviewer_id INTEGER DEFAULT NULL REFERENCES deu.users (id) ON DELETE CASCADE, -- ID de la cuenta de administrador que revisa la solicitud
    reviewed_at TIMESTAMP DEFAULT NULL,
    comments TEXT,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW ()
  );

-- Tabla para almacenar información de miembros de grupos de extensión
CREATE TABLE
  deu.group_members (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    group_id INTEGER NOT NULL REFERENCES deu.extension_groups (id) ON DELETE CASCADE,
    name VARCHAR NOT NULL,
    ci INTEGER,
    phone VARCHAR,
    email VARCHAR,
    coordination VARCHAR,
    year INTEGER,
    faculty faculty_enum DEFAULT 'DEU',
    school VARCHAR,
    document VARCHAR,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL
  );

-- Tabla para almacenar solicitudes de recursos de grupos de extensión
CREATE TABLE
  deu.group_resource_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    group_id INTEGER NOT NULL REFERENCES deu.extension_groups (id) ON DELETE CASCADE,
    type VARCHAR NOT NULL,
    content TEXT,
    status resource_request_status_enum NOT NULL,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL
  );

-- Tabla para almacenar información de actividades
CREATE TABLE
  deu.activities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR,
    group_id INTEGER REFERENCES deu.extension_groups (id) ON DELETE SET NULL,
    description TEXT,
    date DATE,
    knowledge_area VARCHAR, -- Área de conocimiento relacionada con la actividad
    allies VARCHAR, -- Aliados o colaboradores de la actividad
    stimated_participants INTEGER, -- Participantes estimados
    actual_participants INTEGER, -- Participantes reales
    active_members INTEGER, -- Miembros activos del grupo
    path VARCHAR,
    location VARCHAR,
    assistants INTEGER,
    comments TEXT,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL
  );

CREATE TYPE contact_type_enum AS ENUM ('email', 'phone');

CREATE TYPE owner_type_enum AS ENUM ('user', 'provider', 'group');

-- Crear la tabla de contactos con las restricciones y tipos adecuados
-- Tabla para almacenar información de contactos
CREATE TABLE
  contacts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    contact_type contact_type_enum NOT NULL DEFAULT 'email',
    contact_value TEXT NOT NULL,
    owner_type owner_type_enum NOT NULL,
    owner_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW (),
    updated_at TIMESTAMPTZ DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL,
    CONSTRAINT unique_contact_per_owner UNIQUE (contact_type, contact_value, owner_type, owner_id)
  );

CREATE TABLE 
files (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  owner_type TEXT NOT NULL CHECK (owner_type IN ('course', 'group', 'group_activity', 'course_cycle', 'provider', 'user')),
  owner_id INTEGER NOT NULL,
  file_key TEXT NOT NULL,
  purpose TEXT NOT NULL,
  public BOOLEAN DEFAULT false,
  metadata JSONB,
  uploaded_by INTEGER REFERENCES deu.users(id),
  created_at TIMESTAMP DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX idx_owner_type_owner_id ON files (owner_type, owner_id);

-- Tabla para solicitudes de registro de proveedores
CREATE TABLE
  deu.provider_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    provider_id INTEGER NOT NULL REFERENCES deu.providers (id) ON DELETE CASCADE,
    status request_status_enum DEFAULT 'under_review' NOT NULL,
    reviewer_id INTEGER DEFAULT NULL REFERENCES deu.users (id) ON DELETE SET NULL,
    comments TEXT,
    reviewed_at TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL
  );

-- Tabla para solicitudes de cierre/certificación de ciclos de cursos
CREATE TABLE
  deu.course_cycle_close_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    course_cycle_id INTEGER NOT NULL REFERENCES deu.course_cycles (id) ON DELETE CASCADE,
    submitted_by INTEGER NOT NULL REFERENCES deu.users (id) ON DELETE CASCADE,
    status request_status_enum DEFAULT 'under_review' NOT NULL,
    comments TEXT,
    reviewer_id INTEGER DEFAULT NULL REFERENCES deu.users (id) ON DELETE SET NULL,
    reviewed_at TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP DEFAULT NOW (),
    updated_at TIMESTAMP DEFAULT NOW (),
    deleted_at TIMESTAMP DEFAULT NULL
  );

-- Comentarios
COMMENT ON TABLE deu.roles IS 'Roles incluyen: root, admin, coordinador, facilitador, estudiante, extension';

COMMENT ON COLUMN contacts.contact_type IS 'Tipo de contacto: ya sea ''email'' o ''phone''';

COMMENT ON COLUMN contacts.contact_value IS 'El valor real del contacto (por ejemplo, una dirección de correo electrónico o un número de teléfono)';

COMMENT ON COLUMN contacts.owner_type IS 'El tipo de entidad que posee el contacto (''user'' o ''provider'')';

COMMENT ON COLUMN contacts.owner_id IS 'El ID del usuario o proveedor que posee el contacto';

COMMENT ON COLUMN contacts.created_at IS 'Marca de tiempo de cuando se creó la entrada de contacto';

-- Insertar datos iniciales
INSERT INTO
  deu.roles (name, description)
VALUES
  (
    'root',
    'Superusuario con acceso total al sistema.'
  ),
  (
    'deu_admin',
    'Administrador con privilegios elevados.'
  ),
  (
    'faculty_admin',
    'Responsable de evaluar solicitudes de avales de cursos y grupos de extension. Puede ser por escuela o de la DEU'
  ),
  (
    'course_admin',
    'Representante de un ente que imparte diplomados.'
  ),
  (
    'course_manager',
    'Encargado de impartir cursos y talleres.'
  ),
  (
    'group_helper',
    'Grupo o departamento de extensión'
  ),
  (
    'group_admin',
    'Grupo o departamento de extensión.'
  ),
  (
    'visitante',
    'Participante interesados en cursos.'
  );

-- contraseña: nolodire
-- Insert mock data for users
INSERT INTO
  deu.users (ci, email, first_name, last_name, date_of_birth, gender, education, address, password)
VALUES
  (101, 'deu_admin1@example.com', 'Admin1', 'Deu', '1980-01-01', 'male', 'universitaria_completa', 'Address 1', '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'),
  (102, 'deu_admin2@example.com', 'Admin2', 'Deu', '1982-02-02', 'female', 'universitaria_completa', 'Address 2', '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'),
  (103, 'faculty_admin1@example.com', 'Faculty1', 'Admin', '1985-03-03', 'male', 'posgrado', 'Address 3', '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'),
  (104, 'faculty_admin2@example.com', 'Faculty2', 'Admin', '1987-04-04', 'female', 'posgrado', 'Address 4', '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'),
  (105, 'course_admin@example.com', 'Course', 'Admin', '1990-05-05', 'male', 'universitaria_completa', 'Address 5', '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'),
  (106, 'course_manager@example.com', 'Course', 'Manager', '1992-06-06', 'female', 'universitaria_completa', 'Address 6', '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'),
  (107, 'participant1@example.com', 'Participant1', 'User', '1995-07-07', 'male', 'universitaria_incompleta', 'Address 7', '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'),
  (108, 'participant2@example.com', 'Participant2', 'User', '1996-08-08', 'female', 'universitaria_incompleta', 'Address 8', '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'),
  (109, 'participant3@example.com', 'Participant3', 'User', '1997-09-09', 'male', 'universitaria_incompleta', 'Address 9', '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'),
  (110, 'participant4@example.com', 'Participant4', 'User', '1998-10-10', 'female', 'universitaria_incompleta', 'Address 10', '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'),
  (111, 'group_admin@example.com', 'Group', 'Admin', '1989-11-11', 'male', 'universitaria_completa', 'Address 11', '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'),
  (112, 'group_helper@example.com', 'Group', 'Helper', '1991-12-12', 'female', 'universitaria_completa', 'Address 12', '$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa'),
  (100, 'eaguilar@email.com','Ellery','Aguilar','1988-09-03','masculino','universitaria_incompleta','caracas','$2a$10$rFfAKJJIvbGaQCay8zC9bulGQ/kOYDOwwVBGr0WyWA1sUTLZsuXpa');

-- Insert mock data for user_roles
INSERT INTO
  deu.user_roles (user_id, role_id, domain_type)
VALUES
  (13, 1, 'all'), -- root user
  (1, 2, 'all'), -- deu_admin
  (2, 2, 'all'), -- deu_admin
  (3, 3, 'all'), -- faculty_admin
  (4, 3, 'all'), -- faculty_admin
  (5, 4, 'course'), -- course_admin
  (6, 5, 'course'), -- course_manager
  (7, 6, 'course'), -- visitante
  (8, 6, 'course'), -- visitante
  (9, 6, 'course'), -- visitante
  (10, 6, 'course'), -- visitante
  (11, 7, 'group'), -- group_admin
  (12, 8, 'group'); -- group_helper

  -- Insert mock data for providers
  INSERT INTO
    deu.providers (user_id, name, party_type, profit_type, is_internal, bio, code, is_active)
  VALUES
    (5, 'Extensión Ingeniería UCV', 'natural', 'no_lucrativo', false, 'Proveedor de cursos de formación profesional en el área de ingeniería.', CONCAT('ECP-', LEFT(MD5(RANDOM()::TEXT), 6)), true), -- course_admin
    (11, 'Grupo Cultural Humanidades', 'natural', 'no_lucrativo', true, 'Grupo de extensión universitaria dedicado a actividades culturales y humanísticas.', CONCAT('GEX-', LEFT(MD5(RANDOM()::TEXT), 6)), true); -- group_admin

  -- Insert mock data for courses
  INSERT INTO
    deu.courses (name, description, provider_id, objectives, duration, content, type, faculty, cost, location, is_active)
  VALUES
    ('Course 1', 'Description for Course 1', 1, 'Objectives for Course 1', 40, 'Content for Course 1', 'skill_development', 'Ingeniería', 100.0, 'online', TRUE),
    ('Course 2', 'Description for Course 2', 1, 'Objectives for Course 2', 30, 'Content for Course 2', 'life_skills', 'Ciencias', 80.0, 'in_site', FALSE),
    ('Course 3', 'Description for Course 3', 1, 'Objectives for Course 3', 50, 'Content for Course 3', 'technical_training', 'Medicina', 120.0, 'online', TRUE);

  -- Insert mock data for course_auth_requests
  INSERT INTO
    deu.course_auth_requests (course_id, status, reviewer_id, comments, reviewed_at)
  VALUES
    (1, 'approved', 2, 'Approved successfully', '2023-01-15'),
    (2, 'under_review', NULL, NULL, NULL),
    (3, 'rejected', 2, 'Insufficient details provided', '2023-02-10');

  -- Insert mock data for extension_groups
  INSERT INTO
    deu.extension_groups (name, user_id, description, faculty, objective, code, group_director, type, location, is_active)
  VALUES
    ('Group 1', 11, 'Description for Group 1', 'Humanidades y Educación', 'Objective for Group 1', 'GEX-1234', 'John Doe', 'cultural', 'Location 1', TRUE);

  -- Insert mock data for group_auth_requests
  INSERT INTO
    deu.group_auth_requests (group_id, reviewer_id, status, comments, reviewed_at)
  VALUES
    (1, 2, 'approved', 'Approved successfully', '2023-01-15'),
    (1, 3, 'approved', NULL, '2023-01-15');