// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/eaguilar88/deu/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateProvider provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateProvider(ctx context.Context, provider entities.Provider) (int64, error) {
	ret := _mock.Called(ctx, provider)

	if len(ret) == 0 {
		panic("no return value specified for CreateProvider")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Provider) (int64, error)); ok {
		return returnFunc(ctx, provider)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Provider) int64); ok {
		r0 = returnFunc(ctx, provider)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Provider) error); ok {
		r1 = returnFunc(ctx, provider)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProvider'
type MockRepository_CreateProvider_Call struct {
	*mock.Call
}

// CreateProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - provider entities.Provider
func (_e *MockRepository_Expecter) CreateProvider(ctx interface{}, provider interface{}) *MockRepository_CreateProvider_Call {
	return &MockRepository_CreateProvider_Call{Call: _e.mock.On("CreateProvider", ctx, provider)}
}

func (_c *MockRepository_CreateProvider_Call) Run(run func(ctx context.Context, provider entities.Provider)) *MockRepository_CreateProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Provider
		if args[1] != nil {
			arg1 = args[1].(entities.Provider)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateProvider_Call) Return(n int64, err error) *MockRepository_CreateProvider_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_CreateProvider_Call) RunAndReturn(run func(ctx context.Context, provider entities.Provider) (int64, error)) *MockRepository_CreateProvider_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProviderRequest provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateProviderRequest(ctx context.Context, providerID int64) error {
	ret := _mock.Called(ctx, providerID)

	if len(ret) == 0 {
		panic("no return value specified for CreateProviderRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, providerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateProviderRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProviderRequest'
type MockRepository_CreateProviderRequest_Call struct {
	*mock.Call
}

// CreateProviderRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - providerID int64
func (_e *MockRepository_Expecter) CreateProviderRequest(ctx interface{}, providerID interface{}) *MockRepository_CreateProviderRequest_Call {
	return &MockRepository_CreateProviderRequest_Call{Call: _e.mock.On("CreateProviderRequest", ctx, providerID)}
}

func (_c *MockRepository_CreateProviderRequest_Call) Run(run func(ctx context.Context, providerID int64)) *MockRepository_CreateProviderRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateProviderRequest_Call) Return(err error) *MockRepository_CreateProviderRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateProviderRequest_Call) RunAndReturn(run func(ctx context.Context, providerID int64) error) *MockRepository_CreateProviderRequest_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProvider provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteProvider(ctx context.Context, providerID string) error {
	ret := _mock.Called(ctx, providerID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProvider")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, providerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProvider'
type MockRepository_DeleteProvider_Call struct {
	*mock.Call
}

// DeleteProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - providerID string
func (_e *MockRepository_Expecter) DeleteProvider(ctx interface{}, providerID interface{}) *MockRepository_DeleteProvider_Call {
	return &MockRepository_DeleteProvider_Call{Call: _e.mock.On("DeleteProvider", ctx, providerID)}
}

func (_c *MockRepository_DeleteProvider_Call) Run(run func(ctx context.Context, providerID string)) *MockRepository_DeleteProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteProvider_Call) Return(err error) *MockRepository_DeleteProvider_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteProvider_Call) RunAndReturn(run func(ctx context.Context, providerID string) error) *MockRepository_DeleteProvider_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilesByOwner provides a mock function for the type MockRepository
func (_mock *MockRepository) GetFilesByOwner(ctx context.Context, ownerID string, ownerType entities.OwnerType) (entities.GroupedFiles, error) {
	ret := _mock.Called(ctx, ownerID, ownerType)

	if len(ret) == 0 {
		panic("no return value specified for GetFilesByOwner")
	}

	var r0 entities.GroupedFiles
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entities.OwnerType) (entities.GroupedFiles, error)); ok {
		return returnFunc(ctx, ownerID, ownerType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entities.OwnerType) entities.GroupedFiles); ok {
		r0 = returnFunc(ctx, ownerID, ownerType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.GroupedFiles)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, entities.OwnerType) error); ok {
		r1 = returnFunc(ctx, ownerID, ownerType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetFilesByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilesByOwner'
type MockRepository_GetFilesByOwner_Call struct {
	*mock.Call
}

// GetFilesByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - ownerType entities.OwnerType
func (_e *MockRepository_Expecter) GetFilesByOwner(ctx interface{}, ownerID interface{}, ownerType interface{}) *MockRepository_GetFilesByOwner_Call {
	return &MockRepository_GetFilesByOwner_Call{Call: _e.mock.On("GetFilesByOwner", ctx, ownerID, ownerType)}
}

func (_c *MockRepository_GetFilesByOwner_Call) Run(run func(ctx context.Context, ownerID string, ownerType entities.OwnerType)) *MockRepository_GetFilesByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entities.OwnerType
		if args[2] != nil {
			arg2 = args[2].(entities.OwnerType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_GetFilesByOwner_Call) Return(groupedFiles entities.GroupedFiles, err error) *MockRepository_GetFilesByOwner_Call {
	_c.Call.Return(groupedFiles, err)
	return _c
}

func (_c *MockRepository_GetFilesByOwner_Call) RunAndReturn(run func(ctx context.Context, ownerID string, ownerType entities.OwnerType) (entities.GroupedFiles, error)) *MockRepository_GetFilesByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilesByOwnerAndPurpose provides a mock function for the type MockRepository
func (_mock *MockRepository) GetFilesByOwnerAndPurpose(ctx context.Context, ownerID string, ownerType string, purpose string) ([]*entities.File, error) {
	ret := _mock.Called(ctx, ownerID, ownerType, purpose)

	if len(ret) == 0 {
		panic("no return value specified for GetFilesByOwnerAndPurpose")
	}

	var r0 []*entities.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ([]*entities.File, error)); ok {
		return returnFunc(ctx, ownerID, ownerType, purpose)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) []*entities.File); ok {
		r0 = returnFunc(ctx, ownerID, ownerType, purpose)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, ownerID, ownerType, purpose)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetFilesByOwnerAndPurpose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilesByOwnerAndPurpose'
type MockRepository_GetFilesByOwnerAndPurpose_Call struct {
	*mock.Call
}

// GetFilesByOwnerAndPurpose is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - ownerType string
//   - purpose string
func (_e *MockRepository_Expecter) GetFilesByOwnerAndPurpose(ctx interface{}, ownerID interface{}, ownerType interface{}, purpose interface{}) *MockRepository_GetFilesByOwnerAndPurpose_Call {
	return &MockRepository_GetFilesByOwnerAndPurpose_Call{Call: _e.mock.On("GetFilesByOwnerAndPurpose", ctx, ownerID, ownerType, purpose)}
}

func (_c *MockRepository_GetFilesByOwnerAndPurpose_Call) Run(run func(ctx context.Context, ownerID string, ownerType string, purpose string)) *MockRepository_GetFilesByOwnerAndPurpose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_GetFilesByOwnerAndPurpose_Call) Return(files []*entities.File, err error) *MockRepository_GetFilesByOwnerAndPurpose_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockRepository_GetFilesByOwnerAndPurpose_Call) RunAndReturn(run func(ctx context.Context, ownerID string, ownerType string, purpose string) ([]*entities.File, error)) *MockRepository_GetFilesByOwnerAndPurpose_Call {
	_c.Call.Return(run)
	return _c
}

// GetProvider provides a mock function for the type MockRepository
func (_mock *MockRepository) GetProvider(ctx context.Context, providerID string) (entities.Provider, error) {
	ret := _mock.Called(ctx, providerID)

	if len(ret) == 0 {
		panic("no return value specified for GetProvider")
	}

	var r0 entities.Provider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entities.Provider, error)); ok {
		return returnFunc(ctx, providerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entities.Provider); ok {
		r0 = returnFunc(ctx, providerID)
	} else {
		r0 = ret.Get(0).(entities.Provider)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, providerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProvider'
type MockRepository_GetProvider_Call struct {
	*mock.Call
}

// GetProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - providerID string
func (_e *MockRepository_Expecter) GetProvider(ctx interface{}, providerID interface{}) *MockRepository_GetProvider_Call {
	return &MockRepository_GetProvider_Call{Call: _e.mock.On("GetProvider", ctx, providerID)}
}

func (_c *MockRepository_GetProvider_Call) Run(run func(ctx context.Context, providerID string)) *MockRepository_GetProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetProvider_Call) Return(provider entities.Provider, err error) *MockRepository_GetProvider_Call {
	_c.Call.Return(provider, err)
	return _c
}

func (_c *MockRepository_GetProvider_Call) RunAndReturn(run func(ctx context.Context, providerID string) (entities.Provider, error)) *MockRepository_GetProvider_Call {
	_c.Call.Return(run)
	return _c
}

// GetProviderByCode provides a mock function for the type MockRepository
func (_mock *MockRepository) GetProviderByCode(ctx context.Context, code string) (entities.Provider, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetProviderByCode")
	}

	var r0 entities.Provider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entities.Provider, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entities.Provider); ok {
		r0 = returnFunc(ctx, code)
	} else {
		r0 = ret.Get(0).(entities.Provider)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetProviderByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProviderByCode'
type MockRepository_GetProviderByCode_Call struct {
	*mock.Call
}

// GetProviderByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockRepository_Expecter) GetProviderByCode(ctx interface{}, code interface{}) *MockRepository_GetProviderByCode_Call {
	return &MockRepository_GetProviderByCode_Call{Call: _e.mock.On("GetProviderByCode", ctx, code)}
}

func (_c *MockRepository_GetProviderByCode_Call) Run(run func(ctx context.Context, code string)) *MockRepository_GetProviderByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetProviderByCode_Call) Return(provider entities.Provider, err error) *MockRepository_GetProviderByCode_Call {
	_c.Call.Return(provider, err)
	return _c
}

func (_c *MockRepository_GetProviderByCode_Call) RunAndReturn(run func(ctx context.Context, code string) (entities.Provider, error)) *MockRepository_GetProviderByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetProviderByUserID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetProviderByUserID(ctx context.Context, userID string) (entities.Provider, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProviderByUserID")
	}

	var r0 entities.Provider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entities.Provider, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entities.Provider); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(entities.Provider)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetProviderByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProviderByUserID'
type MockRepository_GetProviderByUserID_Call struct {
	*mock.Call
}

// GetProviderByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) GetProviderByUserID(ctx interface{}, userID interface{}) *MockRepository_GetProviderByUserID_Call {
	return &MockRepository_GetProviderByUserID_Call{Call: _e.mock.On("GetProviderByUserID", ctx, userID)}
}

func (_c *MockRepository_GetProviderByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_GetProviderByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetProviderByUserID_Call) Return(provider entities.Provider, err error) *MockRepository_GetProviderByUserID_Call {
	_c.Call.Return(provider, err)
	return _c
}

func (_c *MockRepository_GetProviderByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) (entities.Provider, error)) *MockRepository_GetProviderByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetProviderContactInfo provides a mock function for the type MockRepository
func (_mock *MockRepository) GetProviderContactInfo(ctx context.Context, providerID string) (entities.User, error) {
	ret := _mock.Called(ctx, providerID)

	if len(ret) == 0 {
		panic("no return value specified for GetProviderContactInfo")
	}

	var r0 entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entities.User, error)); ok {
		return returnFunc(ctx, providerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entities.User); ok {
		r0 = returnFunc(ctx, providerID)
	} else {
		r0 = ret.Get(0).(entities.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, providerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetProviderContactInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProviderContactInfo'
type MockRepository_GetProviderContactInfo_Call struct {
	*mock.Call
}

// GetProviderContactInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - providerID string
func (_e *MockRepository_Expecter) GetProviderContactInfo(ctx interface{}, providerID interface{}) *MockRepository_GetProviderContactInfo_Call {
	return &MockRepository_GetProviderContactInfo_Call{Call: _e.mock.On("GetProviderContactInfo", ctx, providerID)}
}

func (_c *MockRepository_GetProviderContactInfo_Call) Run(run func(ctx context.Context, providerID string)) *MockRepository_GetProviderContactInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetProviderContactInfo_Call) Return(user entities.User, err error) *MockRepository_GetProviderContactInfo_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_GetProviderContactInfo_Call) RunAndReturn(run func(ctx context.Context, providerID string) (entities.User, error)) *MockRepository_GetProviderContactInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetProviders provides a mock function for the type MockRepository
func (_mock *MockRepository) GetProviders(ctx context.Context, pageScope entities.PageScope, filters entities.ProviderFilters) ([]entities.Provider, entities.PageScope, error) {
	ret := _mock.Called(ctx, pageScope, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetProviders")
	}

	var r0 []entities.Provider
	var r1 entities.PageScope
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.PageScope, entities.ProviderFilters) ([]entities.Provider, entities.PageScope, error)); ok {
		return returnFunc(ctx, pageScope, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.PageScope, entities.ProviderFilters) []entities.Provider); ok {
		r0 = returnFunc(ctx, pageScope, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Provider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.PageScope, entities.ProviderFilters) entities.PageScope); ok {
		r1 = returnFunc(ctx, pageScope, filters)
	} else {
		r1 = ret.Get(1).(entities.PageScope)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, entities.PageScope, entities.ProviderFilters) error); ok {
		r2 = returnFunc(ctx, pageScope, filters)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_GetProviders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProviders'
type MockRepository_GetProviders_Call struct {
	*mock.Call
}

// GetProviders is a helper method to define mock.On call
//   - ctx context.Context
//   - pageScope entities.PageScope
//   - filters entities.ProviderFilters
func (_e *MockRepository_Expecter) GetProviders(ctx interface{}, pageScope interface{}, filters interface{}) *MockRepository_GetProviders_Call {
	return &MockRepository_GetProviders_Call{Call: _e.mock.On("GetProviders", ctx, pageScope, filters)}
}

func (_c *MockRepository_GetProviders_Call) Run(run func(ctx context.Context, pageScope entities.PageScope, filters entities.ProviderFilters)) *MockRepository_GetProviders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.PageScope
		if args[1] != nil {
			arg1 = args[1].(entities.PageScope)
		}
		var arg2 entities.ProviderFilters
		if args[2] != nil {
			arg2 = args[2].(entities.ProviderFilters)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_GetProviders_Call) Return(providers []entities.Provider, pageScope1 entities.PageScope, err error) *MockRepository_GetProviders_Call {
	_c.Call.Return(providers, pageScope1, err)
	return _c
}

func (_c *MockRepository_GetProviders_Call) RunAndReturn(run func(ctx context.Context, pageScope entities.PageScope, filters entities.ProviderFilters) ([]entities.Provider, entities.PageScope, error)) *MockRepository_GetProviders_Call {
	_c.Call.Return(run)
	return _c
}

// MarkCoursesWithDocumentation provides a mock function for the type MockRepository
func (_mock *MockRepository) MarkCoursesWithDocumentation(ctx context.Context, providerID string, from string, to string) error {
	ret := _mock.Called(ctx, providerID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for MarkCoursesWithDocumentation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, providerID, from, to)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_MarkCoursesWithDocumentation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkCoursesWithDocumentation'
type MockRepository_MarkCoursesWithDocumentation_Call struct {
	*mock.Call
}

// MarkCoursesWithDocumentation is a helper method to define mock.On call
//   - ctx context.Context
//   - providerID string
//   - from string
//   - to string
func (_e *MockRepository_Expecter) MarkCoursesWithDocumentation(ctx interface{}, providerID interface{}, from interface{}, to interface{}) *MockRepository_MarkCoursesWithDocumentation_Call {
	return &MockRepository_MarkCoursesWithDocumentation_Call{Call: _e.mock.On("MarkCoursesWithDocumentation", ctx, providerID, from, to)}
}

func (_c *MockRepository_MarkCoursesWithDocumentation_Call) Run(run func(ctx context.Context, providerID string, from string, to string)) *MockRepository_MarkCoursesWithDocumentation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_MarkCoursesWithDocumentation_Call) Return(err error) *MockRepository_MarkCoursesWithDocumentation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_MarkCoursesWithDocumentation_Call) RunAndReturn(run func(ctx context.Context, providerID string, from string, to string) error) *MockRepository_MarkCoursesWithDocumentation_Call {
	_c.Call.Return(run)
	return _c
}

// SaveFilesToDB provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveFilesToDB(ctx context.Context, file []*entities.File) error {
	ret := _mock.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for SaveFilesToDB")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*entities.File) error); ok {
		r0 = returnFunc(ctx, file)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveFilesToDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFilesToDB'
type MockRepository_SaveFilesToDB_Call struct {
	*mock.Call
}

// SaveFilesToDB is a helper method to define mock.On call
//   - ctx context.Context
//   - file []*entities.File
func (_e *MockRepository_Expecter) SaveFilesToDB(ctx interface{}, file interface{}) *MockRepository_SaveFilesToDB_Call {
	return &MockRepository_SaveFilesToDB_Call{Call: _e.mock.On("SaveFilesToDB", ctx, file)}
}

func (_c *MockRepository_SaveFilesToDB_Call) Run(run func(ctx context.Context, file []*entities.File)) *MockRepository_SaveFilesToDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*entities.File
		if args[1] != nil {
			arg1 = args[1].([]*entities.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SaveFilesToDB_Call) Return(err error) *MockRepository_SaveFilesToDB_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveFilesToDB_Call) RunAndReturn(run func(ctx context.Context, file []*entities.File) error) *MockRepository_SaveFilesToDB_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProvider provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateProvider(ctx context.Context, providerID string, provider entities.Provider) error {
	ret := _mock.Called(ctx, providerID, provider)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProvider")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entities.Provider) error); ok {
		r0 = returnFunc(ctx, providerID, provider)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProvider'
type MockRepository_UpdateProvider_Call struct {
	*mock.Call
}

// UpdateProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - providerID string
//   - provider entities.Provider
func (_e *MockRepository_Expecter) UpdateProvider(ctx interface{}, providerID interface{}, provider interface{}) *MockRepository_UpdateProvider_Call {
	return &MockRepository_UpdateProvider_Call{Call: _e.mock.On("UpdateProvider", ctx, providerID, provider)}
}

func (_c *MockRepository_UpdateProvider_Call) Run(run func(ctx context.Context, providerID string, provider entities.Provider)) *MockRepository_UpdateProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entities.Provider
		if args[2] != nil {
			arg2 = args[2].(entities.Provider)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateProvider_Call) Return(err error) *MockRepository_UpdateProvider_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateProvider_Call) RunAndReturn(run func(ctx context.Context, providerID string, provider entities.Provider) error) *MockRepository_UpdateProvider_Call {
	_c.Call.Return(run)
	return _c
}
