// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/eaguilar88/deu/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorageClient creates a new instance of MockStorageClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageClient {
	mock := &MockStorageClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorageClient is an autogenerated mock type for the StorageClient type
type MockStorageClient struct {
	mock.Mock
}

type MockStorageClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageClient) EXPECT() *MockStorageClient_Expecter {
	return &MockStorageClient_Expecter{mock: &_m.Mock}
}

// DeleteFile provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) DeleteFile(ctx context.Context, objectKey string) error {
	ret := _mock.Called(ctx, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, objectKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageClient_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type MockStorageClient_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
func (_e *MockStorageClient_Expecter) DeleteFile(ctx interface{}, objectKey interface{}) *MockStorageClient_DeleteFile_Call {
	return &MockStorageClient_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, objectKey)}
}

func (_c *MockStorageClient_DeleteFile_Call) Run(run func(ctx context.Context, objectKey string)) *MockStorageClient_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageClient_DeleteFile_Call) Return(err error) *MockStorageClient_DeleteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageClient_DeleteFile_Call) RunAndReturn(run func(ctx context.Context, objectKey string) error) *MockStorageClient_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileMetadata provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) GetFileMetadata(ctx context.Context, objectKey string) (map[string]string, error) {
	ret := _mock.Called(ctx, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for GetFileMetadata")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return returnFunc(ctx, objectKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = returnFunc(ctx, objectKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, objectKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageClient_GetFileMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileMetadata'
type MockStorageClient_GetFileMetadata_Call struct {
	*mock.Call
}

// GetFileMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
func (_e *MockStorageClient_Expecter) GetFileMetadata(ctx interface{}, objectKey interface{}) *MockStorageClient_GetFileMetadata_Call {
	return &MockStorageClient_GetFileMetadata_Call{Call: _e.mock.On("GetFileMetadata", ctx, objectKey)}
}

func (_c *MockStorageClient_GetFileMetadata_Call) Run(run func(ctx context.Context, objectKey string)) *MockStorageClient_GetFileMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageClient_GetFileMetadata_Call) Return(stringToString map[string]string, err error) *MockStorageClient_GetFileMetadata_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockStorageClient_GetFileMetadata_Call) RunAndReturn(run func(ctx context.Context, objectKey string) (map[string]string, error)) *MockStorageClient_GetFileMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileURL provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) GetFileURL(ctx context.Context, objectKey string) (string, error) {
	ret := _mock.Called(ctx, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for GetFileURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, objectKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, objectKey)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, objectKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageClient_GetFileURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileURL'
type MockStorageClient_GetFileURL_Call struct {
	*mock.Call
}

// GetFileURL is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
func (_e *MockStorageClient_Expecter) GetFileURL(ctx interface{}, objectKey interface{}) *MockStorageClient_GetFileURL_Call {
	return &MockStorageClient_GetFileURL_Call{Call: _e.mock.On("GetFileURL", ctx, objectKey)}
}

func (_c *MockStorageClient_GetFileURL_Call) Run(run func(ctx context.Context, objectKey string)) *MockStorageClient_GetFileURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageClient_GetFileURL_Call) Return(s string, err error) *MockStorageClient_GetFileURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStorageClient_GetFileURL_Call) RunAndReturn(run func(ctx context.Context, objectKey string) (string, error)) *MockStorageClient_GetFileURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetObject provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) GetObject(ctx context.Context, objectKey string) (io.ReadCloser, string, error) {
	ret := _mock.Called(ctx, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 io.ReadCloser
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, string, error)); ok {
		return returnFunc(ctx, objectKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, objectKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, objectKey)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, objectKey)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStorageClient_GetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObject'
type MockStorageClient_GetObject_Call struct {
	*mock.Call
}

// GetObject is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
func (_e *MockStorageClient_Expecter) GetObject(ctx interface{}, objectKey interface{}) *MockStorageClient_GetObject_Call {
	return &MockStorageClient_GetObject_Call{Call: _e.mock.On("GetObject", ctx, objectKey)}
}

func (_c *MockStorageClient_GetObject_Call) Run(run func(ctx context.Context, objectKey string)) *MockStorageClient_GetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *MockStorageClient_GetObject_Call) Return(body io.ReadCloser, contentType string, err error) *MockStorageClient_GetObject_Call {
	_c.Call.Return(body, contentType, err)
	return _c
}

func (_c *MockStorageClient_GetObject_Call) RunAndReturn(run func(ctx context.Context, objectKey string) (io.ReadCloser, string, error)) *MockStorageClient_GetObject_Call {
	_c.Call.Return(run)
	return _c
}

// UploadFile provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) UploadFile(ctx context.Context, file []*entities.File) error {
	ret := _mock.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*entities.File) error); ok {
		r0 = returnFunc(ctx, file)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageClient_UploadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFile'
type MockStorageClient_UploadFile_Call struct {
	*mock.Call
}

// UploadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - file []*entities.File
func (_e *MockStorageClient_Expecter) UploadFile(ctx interface{}, file interface{}) *MockStorageClient_UploadFile_Call {
	return &MockStorageClient_UploadFile_Call{Call: _e.mock.On("UploadFile", ctx, file)}
}

func (_c *MockStorageClient_UploadFile_Call) Run(run func(ctx context.Context, file []*entities.File)) *MockStorageClient_UploadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*entities.File
		if args[1] != nil {
			arg1 = args[1].([]*entities.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageClient_UploadFile_Call) Return(err error) *MockStorageClient_UploadFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageClient_UploadFile_Call) RunAndReturn(run func(ctx context.Context, file []*entities.File) error) *MockStorageClient_UploadFile_Call {
	_c.Call.Return(run)
	return _c
}
