// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// StorageClientMock is an autogenerated mock type for the StorageClient type
type StorageClientMock struct {
	mock.Mock
}

type StorageClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageClientMock) EXPECT() *StorageClientMock_Expecter {
	return &StorageClientMock_Expecter{mock: &_m.Mock}
}

// DeleteFile provides a mock function with given fields: ctx, objectKey
func (_m *StorageClientMock) DeleteFile(ctx context.Context, objectKey string) error {
	ret := _m.Called(ctx, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, objectKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageClientMock_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type StorageClientMock_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
func (_e *StorageClientMock_Expecter) DeleteFile(ctx interface{}, objectKey interface{}) *StorageClientMock_DeleteFile_Call {
	return &StorageClientMock_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, objectKey)}
}

func (_c *StorageClientMock_DeleteFile_Call) Run(run func(ctx context.Context, objectKey string)) *StorageClientMock_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *StorageClientMock_DeleteFile_Call) Return(_a0 error) *StorageClientMock_DeleteFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageClientMock_DeleteFile_Call) RunAndReturn(run func(context.Context, string) error) *StorageClientMock_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadFile provides a mock function with given fields: ctx, objectKey, destinationPath
func (_m *StorageClientMock) DownloadFile(ctx context.Context, objectKey string, destinationPath string) error {
	ret := _m.Called(ctx, objectKey, destinationPath)

	if len(ret) == 0 {
		panic("no return value specified for DownloadFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, objectKey, destinationPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageClientMock_DownloadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadFile'
type StorageClientMock_DownloadFile_Call struct {
	*mock.Call
}

// DownloadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
//   - destinationPath string
func (_e *StorageClientMock_Expecter) DownloadFile(ctx interface{}, objectKey interface{}, destinationPath interface{}) *StorageClientMock_DownloadFile_Call {
	return &StorageClientMock_DownloadFile_Call{Call: _e.mock.On("DownloadFile", ctx, objectKey, destinationPath)}
}

func (_c *StorageClientMock_DownloadFile_Call) Run(run func(ctx context.Context, objectKey string, destinationPath string)) *StorageClientMock_DownloadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *StorageClientMock_DownloadFile_Call) Return(_a0 error) *StorageClientMock_DownloadFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageClientMock_DownloadFile_Call) RunAndReturn(run func(context.Context, string, string) error) *StorageClientMock_DownloadFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileURL provides a mock function with given fields: ctx, objectKey
func (_m *StorageClientMock) GetFileURL(ctx context.Context, objectKey string) (string, error) {
	ret := _m.Called(ctx, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for GetFileURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, objectKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, objectKey)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, objectKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageClientMock_GetFileURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileURL'
type StorageClientMock_GetFileURL_Call struct {
	*mock.Call
}

// GetFileURL is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
func (_e *StorageClientMock_Expecter) GetFileURL(ctx interface{}, objectKey interface{}) *StorageClientMock_GetFileURL_Call {
	return &StorageClientMock_GetFileURL_Call{Call: _e.mock.On("GetFileURL", ctx, objectKey)}
}

func (_c *StorageClientMock_GetFileURL_Call) Run(run func(ctx context.Context, objectKey string)) *StorageClientMock_GetFileURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *StorageClientMock_GetFileURL_Call) Return(_a0 string, _a1 error) *StorageClientMock_GetFileURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageClientMock_GetFileURL_Call) RunAndReturn(run func(context.Context, string) (string, error)) *StorageClientMock_GetFileURL_Call {
	_c.Call.Return(run)
	return _c
}

// UploadFile provides a mock function with given fields: ctx, file, objectKey, metadata
func (_m *StorageClientMock) UploadFile(ctx context.Context, file multipart.File, objectKey string, metadata map[string]string) error {
	ret := _m.Called(ctx, file, objectKey, metadata)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, multipart.File, string, map[string]string) error); ok {
		r0 = rf(ctx, file, objectKey, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageClientMock_UploadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFile'
type StorageClientMock_UploadFile_Call struct {
	*mock.Call
}

// UploadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - file multipart.File
//   - objectKey string
//   - metadata map[string]string
func (_e *StorageClientMock_Expecter) UploadFile(ctx interface{}, file interface{}, objectKey interface{}, metadata interface{}) *StorageClientMock_UploadFile_Call {
	return &StorageClientMock_UploadFile_Call{Call: _e.mock.On("UploadFile", ctx, file, objectKey, metadata)}
}

func (_c *StorageClientMock_UploadFile_Call) Run(run func(ctx context.Context, file multipart.File, objectKey string, metadata map[string]string)) *StorageClientMock_UploadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(multipart.File), args[2].(string), args[3].(map[string]string))
	})
	return _c
}

func (_c *StorageClientMock_UploadFile_Call) Return(_a0 error) *StorageClientMock_UploadFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageClientMock_UploadFile_Call) RunAndReturn(run func(context.Context, multipart.File, string, map[string]string) error) *StorageClientMock_UploadFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorageClientMock creates a new instance of StorageClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageClientMock {
	mock := &StorageClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
