version: '3'

services:
  # vuejs:
  #   container_name: "deu-vuejs"
  #   image: "deu_vuejs"
  #   build:
  #     context: "frontend"
  #     dockerfile: "Dockerfile"
  #   depends_on:
  #     - "go-deu"
  #     - "postgres16"

  go-deu:
    container_name: "backend"
    image: "deu_golang"
    build:
      context: "backend"
      dockerfile: "./Dockerfile"
    env_file:
      - ${PWD}/.env
    ports:
      - 8085:8085
    links:
      - "postgres16"
  postgres16:
    container_name: "postgres16"
    image: postgres:16-alpine
    build:
      context: "postgresql"
      dockerfile: Dockerfile
    restart: "always"
    ports:
      - 5432:5432
    environment:
      TIMEZONE: "GMT-4"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./postgresql/sql-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: