services:
  # vuejs:
  #   container_name: "deu-vuejs"
  #   image: "deu_vuejs"
  #   build:
  #     context: "frontend"
  #     dockerfile: "Dockerfile"
  #   depends_on:
  #     - "go-deu"
  #     - "postgres16"

  # go-deu:
  #   container_name: "backend"
  #   image: "deu_golang"
  #   build:
  #     context: "backend"
  #     dockerfile: "./Dockerfile"
  #   env_file:
  #     - ${PWD}/.env
  #   ports:
  #     - 8085:8085
  #   links:
  #     - "postgres16"
  #   volumes:
  #     - ./backend/:/app
  db:
    container_name: "pg16"
    image: postgres:16-alpine
    restart: "unless-stopped"
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
    env_file:
      - ${PWD}/.env
volumes:
  postgres_data: