services:
  traefik:
    image: traefik:v3.3
    restart: unless-stopped
    command:
      - "--api.dashboard=true" # Enable the dashboard
      - "--api.insecure=true" # Allow insecure dashboard (for local testing)
      - "--providers.docker=true" # Enable Docker provider
      - "--providers.docker.exposedbydefault=false" # Don't expose containers by default
      - "--entrypoints.web.address=:80" # Define entrypoint for HTTP
      - "--entrypoints.websecure.address=:443" # Enable HTTPS
      - "--log.level=DEBUG" # Set log level to warn
    ports:
      - "80:80" # Expose HTTP
      - "443:443" # Expose HTTPS
      - "8080:8080" # Expose Traefik dashboard (optional)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Allow Traefik to talk to Docker
    networks:
      - web
  landing:
    build:
      context: "./landing"
      dockerfile: "Dockerfile"
    restart: unless-stopped
    depends_on:
      - backend
      - db
    labels:
      - "traefik.enable=true" # Enable Traefik for this service
      - "traefik.http.routers.landing.rule=Host(`extension.ucv.ve`)" # Route based on hostname
      - "traefik.http.routers.landing.entrypoints=web" # Use the web entrypoint
      - "traefik.http.services.landing.loadbalancer.server.port=80" # Target container's port
    networks:
      - web
  diplomados:
    build:
      context: "./diplomados"
      dockerfile: "Dockerfile"
    restart: unless-stopped
    depends_on:
      - backend
      - db
    labels:
      - "traefik.enable=true" # Enable Traefik for this service
      - "traefik.http.routers.formacion.rule=Host(`formacion.extension.ucv.ve`)" # Route based on hostname
      - "traefik.http.routers.formacion.entrypoints=web" # Use the web entrypoint
      - "traefik.http.services.formacion.loadbalancer.server.port=80" # Target container's port
    networks:
      - web
  grupos:
    build:
      context: "./grupos/gsu_ucv"
      dockerfile: "Dockerfile"
    restart: unless-stopped
    depends_on:
      - backend
      - db
    labels:
      - "traefik.enable=true" # Enable Traefik for this service
      - "traefik.http.routers.grupos.rule=Host(`grupos.extension.ucv.ve`)" # Route based on hostname
      - "traefik.http.routers.grupos.entrypoints=web" # Use the web entrypoint
      - "traefik.http.services.grupos.loadbalancer.server.port=80" # Target container's port
    networks:
      - web
  backend:
    build:
      context: "./backend"
      dockerfile: "Dockerfile"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8081:80
    env_file:
      - .env
    secrets:
      - b2_key_id
      - b2_application_id
    environment:
      - B2_KEY_ID_FILE=/run/secrets/b2_key_id
      - B2_APPLICATION_ID_FILE=/run/secrets/b2_application_id
    links:
      - "db"
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.backend.rule=Host(`api.extension.ucv.ve`)"
      - "traefik.http.routers.backend.entrypoints=web" # Use the web entrypoint
      - "traefik.http.services.backend.loadbalancer.server.port=80" # Target container's port
    networks:
      - web
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
    env_file:
      - .env
    networks:
      - web
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
networks:
  web:
    driver: bridge
secrets:
  b2_key_id:
    file: ./secrets/b2_key_id
  b2_application_id:
    file: ./secrets/b2_application_id
