services:
  # vuejs:
  #   container_name: "deu-vuejs"
  #   image: "deu_vuejs"
  #   build:
  #     context: "frontend"
  #     dockerfile: "Dockerfile"
  #   depends_on:
  #     - "go-deu"
  #     - "postgres16"

  # go-deu:
  #   container_name: "backend"
  #   image: "deu_golang"
  #   build:
  #     context: "backend"
  #     dockerfile: "./Dockerfile"
  #   env_file:
  #     - ${PWD}/.env
  #   ports:
  #     - 8085:8085
  #   links:
  #     - "postgres16"
  #   volumes:
  #     - ./backend/:/app
  postgres16:
    container_name: "postgres16"
    image: postgres:16-alpine
    build:
      context: "./postgresql"
      dockerfile: Dockerfile
    restart: "unless-stopped"
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      TIMEZONE: "GMT-4"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
volumes:
  postgres_data: