services:
  home:
    container_name: "landing-app"
    build:
      context: "./home"
      dockerfile: "Dockerfile"
    env_file:
      - .env
    ports:
      - ${HTTP_LANDING_PORT}:${HTTP_LANDING_PORT}
    restart: "always"
    depends_on:
      - db
      - go-deu

  go-deu:
    container_name: "boh-go"
    build:
      context: "./backend"
      dockerfile: "Dockerfile"
    env_file:
      - .env
    ports:
      - ${HTTP_SERVE_PORT}
    links:
      - "db"
  db:
    container_name: "pg16"
    image: postgres:16-alpine
    restart: "unless-stopped"
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
    env_file:
      - .env
volumes:
  postgres_data: