// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/eaguilar88/deu/internal/group_analytics"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetActivitiesByCityMetrics provides a mock function for the type MockRepository
func (_mock *MockRepository) GetActivitiesByCityMetrics(ctx context.Context, year int, groupID string) ([]group_analytics.ActivitiesByCityMetric, error) {
	ret := _mock.Called(ctx, year, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetActivitiesByCityMetrics")
	}

	var r0 []group_analytics.ActivitiesByCityMetric
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) ([]group_analytics.ActivitiesByCityMetric, error)); ok {
		return returnFunc(ctx, year, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) []group_analytics.ActivitiesByCityMetric); ok {
		r0 = returnFunc(ctx, year, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]group_analytics.ActivitiesByCityMetric)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = returnFunc(ctx, year, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetActivitiesByCityMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActivitiesByCityMetrics'
type MockRepository_GetActivitiesByCityMetrics_Call struct {
	*mock.Call
}

// GetActivitiesByCityMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - year int
//   - groupID string
func (_e *MockRepository_Expecter) GetActivitiesByCityMetrics(ctx interface{}, year interface{}, groupID interface{}) *MockRepository_GetActivitiesByCityMetrics_Call {
	return &MockRepository_GetActivitiesByCityMetrics_Call{Call: _e.mock.On("GetActivitiesByCityMetrics", ctx, year, groupID)}
}

func (_c *MockRepository_GetActivitiesByCityMetrics_Call) Run(run func(ctx context.Context, year int, groupID string)) *MockRepository_GetActivitiesByCityMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_GetActivitiesByCityMetrics_Call) Return(activitiesByCityMetrics []group_analytics.ActivitiesByCityMetric, err error) *MockRepository_GetActivitiesByCityMetrics_Call {
	_c.Call.Return(activitiesByCityMetrics, err)
	return _c
}

func (_c *MockRepository_GetActivitiesByCityMetrics_Call) RunAndReturn(run func(ctx context.Context, year int, groupID string) ([]group_analytics.ActivitiesByCityMetric, error)) *MockRepository_GetActivitiesByCityMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetActivitiesByStateMetrics provides a mock function for the type MockRepository
func (_mock *MockRepository) GetActivitiesByStateMetrics(ctx context.Context, year int, groupID string) ([]group_analytics.ActivitiesByStateMetric, error) {
	ret := _mock.Called(ctx, year, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetActivitiesByStateMetrics")
	}

	var r0 []group_analytics.ActivitiesByStateMetric
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) ([]group_analytics.ActivitiesByStateMetric, error)); ok {
		return returnFunc(ctx, year, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) []group_analytics.ActivitiesByStateMetric); ok {
		r0 = returnFunc(ctx, year, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]group_analytics.ActivitiesByStateMetric)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = returnFunc(ctx, year, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetActivitiesByStateMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActivitiesByStateMetrics'
type MockRepository_GetActivitiesByStateMetrics_Call struct {
	*mock.Call
}

// GetActivitiesByStateMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - year int
//   - groupID string
func (_e *MockRepository_Expecter) GetActivitiesByStateMetrics(ctx interface{}, year interface{}, groupID interface{}) *MockRepository_GetActivitiesByStateMetrics_Call {
	return &MockRepository_GetActivitiesByStateMetrics_Call{Call: _e.mock.On("GetActivitiesByStateMetrics", ctx, year, groupID)}
}

func (_c *MockRepository_GetActivitiesByStateMetrics_Call) Run(run func(ctx context.Context, year int, groupID string)) *MockRepository_GetActivitiesByStateMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_GetActivitiesByStateMetrics_Call) Return(activitiesByStateMetrics []group_analytics.ActivitiesByStateMetric, err error) *MockRepository_GetActivitiesByStateMetrics_Call {
	_c.Call.Return(activitiesByStateMetrics, err)
	return _c
}

func (_c *MockRepository_GetActivitiesByStateMetrics_Call) RunAndReturn(run func(ctx context.Context, year int, groupID string) ([]group_analytics.ActivitiesByStateMetric, error)) *MockRepository_GetActivitiesByStateMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetActivityParticipantsMetrics provides a mock function for the type MockRepository
func (_mock *MockRepository) GetActivityParticipantsMetrics(ctx context.Context, year int, groupID string) ([]group_analytics.ActivityParticipantsMetric, error) {
	ret := _mock.Called(ctx, year, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetActivityParticipantsMetrics")
	}

	var r0 []group_analytics.ActivityParticipantsMetric
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) ([]group_analytics.ActivityParticipantsMetric, error)); ok {
		return returnFunc(ctx, year, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) []group_analytics.ActivityParticipantsMetric); ok {
		r0 = returnFunc(ctx, year, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]group_analytics.ActivityParticipantsMetric)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = returnFunc(ctx, year, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetActivityParticipantsMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActivityParticipantsMetrics'
type MockRepository_GetActivityParticipantsMetrics_Call struct {
	*mock.Call
}

// GetActivityParticipantsMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - year int
//   - groupID string
func (_e *MockRepository_Expecter) GetActivityParticipantsMetrics(ctx interface{}, year interface{}, groupID interface{}) *MockRepository_GetActivityParticipantsMetrics_Call {
	return &MockRepository_GetActivityParticipantsMetrics_Call{Call: _e.mock.On("GetActivityParticipantsMetrics", ctx, year, groupID)}
}

func (_c *MockRepository_GetActivityParticipantsMetrics_Call) Run(run func(ctx context.Context, year int, groupID string)) *MockRepository_GetActivityParticipantsMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_GetActivityParticipantsMetrics_Call) Return(activityParticipantsMetrics []group_analytics.ActivityParticipantsMetric, err error) *MockRepository_GetActivityParticipantsMetrics_Call {
	_c.Call.Return(activityParticipantsMetrics, err)
	return _c
}

func (_c *MockRepository_GetActivityParticipantsMetrics_Call) RunAndReturn(run func(ctx context.Context, year int, groupID string) ([]group_analytics.ActivityParticipantsMetric, error)) *MockRepository_GetActivityParticipantsMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupParticipantsMetrics provides a mock function for the type MockRepository
func (_mock *MockRepository) GetGroupParticipantsMetrics(ctx context.Context, year int, groupID string) ([]group_analytics.GroupParticipantsMetric, error) {
	ret := _mock.Called(ctx, year, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupParticipantsMetrics")
	}

	var r0 []group_analytics.GroupParticipantsMetric
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) ([]group_analytics.GroupParticipantsMetric, error)); ok {
		return returnFunc(ctx, year, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) []group_analytics.GroupParticipantsMetric); ok {
		r0 = returnFunc(ctx, year, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]group_analytics.GroupParticipantsMetric)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = returnFunc(ctx, year, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetGroupParticipantsMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupParticipantsMetrics'
type MockRepository_GetGroupParticipantsMetrics_Call struct {
	*mock.Call
}

// GetGroupParticipantsMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - year int
//   - groupID string
func (_e *MockRepository_Expecter) GetGroupParticipantsMetrics(ctx interface{}, year interface{}, groupID interface{}) *MockRepository_GetGroupParticipantsMetrics_Call {
	return &MockRepository_GetGroupParticipantsMetrics_Call{Call: _e.mock.On("GetGroupParticipantsMetrics", ctx, year, groupID)}
}

func (_c *MockRepository_GetGroupParticipantsMetrics_Call) Run(run func(ctx context.Context, year int, groupID string)) *MockRepository_GetGroupParticipantsMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_GetGroupParticipantsMetrics_Call) Return(groupParticipantsMetrics []group_analytics.GroupParticipantsMetric, err error) *MockRepository_GetGroupParticipantsMetrics_Call {
	_c.Call.Return(groupParticipantsMetrics, err)
	return _c
}

func (_c *MockRepository_GetGroupParticipantsMetrics_Call) RunAndReturn(run func(ctx context.Context, year int, groupID string) ([]group_analytics.GroupParticipantsMetric, error)) *MockRepository_GetGroupParticipantsMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetKnowledgeAreasByYearMetrics provides a mock function for the type MockRepository
func (_mock *MockRepository) GetKnowledgeAreasByYearMetrics(ctx context.Context, startYear int, endYear int, masterAreas []string, groupID string) ([]group_analytics.KnowledgeAreaYear, error) {
	ret := _mock.Called(ctx, startYear, endYear, masterAreas, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetKnowledgeAreasByYearMetrics")
	}

	var r0 []group_analytics.KnowledgeAreaYear
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, []string, string) ([]group_analytics.KnowledgeAreaYear, error)); ok {
		return returnFunc(ctx, startYear, endYear, masterAreas, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, []string, string) []group_analytics.KnowledgeAreaYear); ok {
		r0 = returnFunc(ctx, startYear, endYear, masterAreas, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]group_analytics.KnowledgeAreaYear)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, []string, string) error); ok {
		r1 = returnFunc(ctx, startYear, endYear, masterAreas, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetKnowledgeAreasByYearMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKnowledgeAreasByYearMetrics'
type MockRepository_GetKnowledgeAreasByYearMetrics_Call struct {
	*mock.Call
}

// GetKnowledgeAreasByYearMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - startYear int
//   - endYear int
//   - masterAreas []string
//   - groupID string
func (_e *MockRepository_Expecter) GetKnowledgeAreasByYearMetrics(ctx interface{}, startYear interface{}, endYear interface{}, masterAreas interface{}, groupID interface{}) *MockRepository_GetKnowledgeAreasByYearMetrics_Call {
	return &MockRepository_GetKnowledgeAreasByYearMetrics_Call{Call: _e.mock.On("GetKnowledgeAreasByYearMetrics", ctx, startYear, endYear, masterAreas, groupID)}
}

func (_c *MockRepository_GetKnowledgeAreasByYearMetrics_Call) Run(run func(ctx context.Context, startYear int, endYear int, masterAreas []string, groupID string)) *MockRepository_GetKnowledgeAreasByYearMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepository_GetKnowledgeAreasByYearMetrics_Call) Return(knowledgeAreaYears []group_analytics.KnowledgeAreaYear, err error) *MockRepository_GetKnowledgeAreasByYearMetrics_Call {
	_c.Call.Return(knowledgeAreaYears, err)
	return _c
}

func (_c *MockRepository_GetKnowledgeAreasByYearMetrics_Call) RunAndReturn(run func(ctx context.Context, startYear int, endYear int, masterAreas []string, groupID string) ([]group_analytics.KnowledgeAreaYear, error)) *MockRepository_GetKnowledgeAreasByYearMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetYearlyActivitiesMetrics provides a mock function for the type MockRepository
func (_mock *MockRepository) GetYearlyActivitiesMetrics(ctx context.Context, startYear int, endYear int, groupID string) ([]group_analytics.YearlyActivitiesMetric, error) {
	ret := _mock.Called(ctx, startYear, endYear, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetYearlyActivitiesMetrics")
	}

	var r0 []group_analytics.YearlyActivitiesMetric
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, string) ([]group_analytics.YearlyActivitiesMetric, error)); ok {
		return returnFunc(ctx, startYear, endYear, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, string) []group_analytics.YearlyActivitiesMetric); ok {
		r0 = returnFunc(ctx, startYear, endYear, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]group_analytics.YearlyActivitiesMetric)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, string) error); ok {
		r1 = returnFunc(ctx, startYear, endYear, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetYearlyActivitiesMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetYearlyActivitiesMetrics'
type MockRepository_GetYearlyActivitiesMetrics_Call struct {
	*mock.Call
}

// GetYearlyActivitiesMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - startYear int
//   - endYear int
//   - groupID string
func (_e *MockRepository_Expecter) GetYearlyActivitiesMetrics(ctx interface{}, startYear interface{}, endYear interface{}, groupID interface{}) *MockRepository_GetYearlyActivitiesMetrics_Call {
	return &MockRepository_GetYearlyActivitiesMetrics_Call{Call: _e.mock.On("GetYearlyActivitiesMetrics", ctx, startYear, endYear, groupID)}
}

func (_c *MockRepository_GetYearlyActivitiesMetrics_Call) Run(run func(ctx context.Context, startYear int, endYear int, groupID string)) *MockRepository_GetYearlyActivitiesMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_GetYearlyActivitiesMetrics_Call) Return(yearlyActivitiesMetrics []group_analytics.YearlyActivitiesMetric, err error) *MockRepository_GetYearlyActivitiesMetrics_Call {
	_c.Call.Return(yearlyActivitiesMetrics, err)
	return _c
}

func (_c *MockRepository_GetYearlyActivitiesMetrics_Call) RunAndReturn(run func(ctx context.Context, startYear int, endYear int, groupID string) ([]group_analytics.YearlyActivitiesMetric, error)) *MockRepository_GetYearlyActivitiesMetrics_Call {
	_c.Call.Return(run)
	return _c
}
