// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetPublicFile provides a mock function for the type MockService
func (_mock *MockService) GetPublicFile(ctx context.Context, key string) (io.ReadCloser, string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicFile")
	}

	var r0 io.ReadCloser
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, key)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_GetPublicFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicFile'
type MockService_GetPublicFile_Call struct {
	*mock.Call
}

// GetPublicFile is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockService_Expecter) GetPublicFile(ctx interface{}, key interface{}) *MockService_GetPublicFile_Call {
	return &MockService_GetPublicFile_Call{Call: _e.mock.On("GetPublicFile", ctx, key)}
}

func (_c *MockService_GetPublicFile_Call) Run(run func(ctx context.Context, key string)) *MockService_GetPublicFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetPublicFile_Call) Return(readCloser io.ReadCloser, s string, err error) *MockService_GetPublicFile_Call {
	_c.Call.Return(readCloser, s, err)
	return _c
}

func (_c *MockService_GetPublicFile_Call) RunAndReturn(run func(ctx context.Context, key string) (io.ReadCloser, string, error)) *MockService_GetPublicFile_Call {
	_c.Call.Return(run)
	return _c
}
