with-expecter: true
all: true
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}Mock"
outpkg: "mocks"
filename: "{{.InterfaceName | lower | snakecase}}_mock.go"
packages:
  github.com/eaguilar88/deu:
    config:
      recursive: true
      