all: true
dir: "{{.InterfaceDir}}/mocks"
filename: "{{ .InterfaceName | snakecase | lower }}_mock.go"
force-file-write: true
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: "mocks"
recursive: true
template: testify
packages:
  github.com/mytheresa/go-hiring-challenge:
    config:
      all: true  