// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/eaguilar88/deu/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ApproveGroupRequest provides a mock function for the type MockRepository
func (_mock *MockRepository) ApproveGroupRequest(ctx context.Context, reqID string) error {
	ret := _mock.Called(ctx, reqID)

	if len(ret) == 0 {
		panic("no return value specified for ApproveGroupRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, reqID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_ApproveGroupRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveGroupRequest'
type MockRepository_ApproveGroupRequest_Call struct {
	*mock.Call
}

// ApproveGroupRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - reqID string
func (_e *MockRepository_Expecter) ApproveGroupRequest(ctx interface{}, reqID interface{}) *MockRepository_ApproveGroupRequest_Call {
	return &MockRepository_ApproveGroupRequest_Call{Call: _e.mock.On("ApproveGroupRequest", ctx, reqID)}
}

func (_c *MockRepository_ApproveGroupRequest_Call) Run(run func(ctx context.Context, reqID string)) *MockRepository_ApproveGroupRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ApproveGroupRequest_Call) Return(err error) *MockRepository_ApproveGroupRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_ApproveGroupRequest_Call) RunAndReturn(run func(ctx context.Context, reqID string) error) *MockRepository_ApproveGroupRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupRequestByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetGroupRequestByID(ctx context.Context, reqID string) (entities.GroupAuthRequest, error) {
	ret := _mock.Called(ctx, reqID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupRequestByID")
	}

	var r0 entities.GroupAuthRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entities.GroupAuthRequest, error)); ok {
		return returnFunc(ctx, reqID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entities.GroupAuthRequest); ok {
		r0 = returnFunc(ctx, reqID)
	} else {
		r0 = ret.Get(0).(entities.GroupAuthRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, reqID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetGroupRequestByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupRequestByID'
type MockRepository_GetGroupRequestByID_Call struct {
	*mock.Call
}

// GetGroupRequestByID is a helper method to define mock.On call
//   - ctx context.Context
//   - reqID string
func (_e *MockRepository_Expecter) GetGroupRequestByID(ctx interface{}, reqID interface{}) *MockRepository_GetGroupRequestByID_Call {
	return &MockRepository_GetGroupRequestByID_Call{Call: _e.mock.On("GetGroupRequestByID", ctx, reqID)}
}

func (_c *MockRepository_GetGroupRequestByID_Call) Run(run func(ctx context.Context, reqID string)) *MockRepository_GetGroupRequestByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetGroupRequestByID_Call) Return(groupAuthRequest entities.GroupAuthRequest, err error) *MockRepository_GetGroupRequestByID_Call {
	_c.Call.Return(groupAuthRequest, err)
	return _c
}

func (_c *MockRepository_GetGroupRequestByID_Call) RunAndReturn(run func(ctx context.Context, reqID string) (entities.GroupAuthRequest, error)) *MockRepository_GetGroupRequestByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupRequestsByFaculty provides a mock function for the type MockRepository
func (_mock *MockRepository) GetGroupRequestsByFaculty(ctx context.Context, faculty entities.Faculty, pageScope entities.PageScope) ([]entities.GroupAuthRequest, entities.PageScope, error) {
	ret := _mock.Called(ctx, faculty, pageScope)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupRequestsByFaculty")
	}

	var r0 []entities.GroupAuthRequest
	var r1 entities.PageScope
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Faculty, entities.PageScope) ([]entities.GroupAuthRequest, entities.PageScope, error)); ok {
		return returnFunc(ctx, faculty, pageScope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Faculty, entities.PageScope) []entities.GroupAuthRequest); ok {
		r0 = returnFunc(ctx, faculty, pageScope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.GroupAuthRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Faculty, entities.PageScope) entities.PageScope); ok {
		r1 = returnFunc(ctx, faculty, pageScope)
	} else {
		r1 = ret.Get(1).(entities.PageScope)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, entities.Faculty, entities.PageScope) error); ok {
		r2 = returnFunc(ctx, faculty, pageScope)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_GetGroupRequestsByFaculty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupRequestsByFaculty'
type MockRepository_GetGroupRequestsByFaculty_Call struct {
	*mock.Call
}

// GetGroupRequestsByFaculty is a helper method to define mock.On call
//   - ctx context.Context
//   - faculty entities.Faculty
//   - pageScope entities.PageScope
func (_e *MockRepository_Expecter) GetGroupRequestsByFaculty(ctx interface{}, faculty interface{}, pageScope interface{}) *MockRepository_GetGroupRequestsByFaculty_Call {
	return &MockRepository_GetGroupRequestsByFaculty_Call{Call: _e.mock.On("GetGroupRequestsByFaculty", ctx, faculty, pageScope)}
}

func (_c *MockRepository_GetGroupRequestsByFaculty_Call) Run(run func(ctx context.Context, faculty entities.Faculty, pageScope entities.PageScope)) *MockRepository_GetGroupRequestsByFaculty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Faculty
		if args[1] != nil {
			arg1 = args[1].(entities.Faculty)
		}
		var arg2 entities.PageScope
		if args[2] != nil {
			arg2 = args[2].(entities.PageScope)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_GetGroupRequestsByFaculty_Call) Return(groupAuthRequests []entities.GroupAuthRequest, pageScope1 entities.PageScope, err error) *MockRepository_GetGroupRequestsByFaculty_Call {
	_c.Call.Return(groupAuthRequests, pageScope1, err)
	return _c
}

func (_c *MockRepository_GetGroupRequestsByFaculty_Call) RunAndReturn(run func(ctx context.Context, faculty entities.Faculty, pageScope entities.PageScope) ([]entities.GroupAuthRequest, entities.PageScope, error)) *MockRepository_GetGroupRequestsByFaculty_Call {
	_c.Call.Return(run)
	return _c
}

// RejectGroupRequest provides a mock function for the type MockRepository
func (_mock *MockRepository) RejectGroupRequest(ctx context.Context, reqID string) error {
	ret := _mock.Called(ctx, reqID)

	if len(ret) == 0 {
		panic("no return value specified for RejectGroupRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, reqID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RejectGroupRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectGroupRequest'
type MockRepository_RejectGroupRequest_Call struct {
	*mock.Call
}

// RejectGroupRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - reqID string
func (_e *MockRepository_Expecter) RejectGroupRequest(ctx interface{}, reqID interface{}) *MockRepository_RejectGroupRequest_Call {
	return &MockRepository_RejectGroupRequest_Call{Call: _e.mock.On("RejectGroupRequest", ctx, reqID)}
}

func (_c *MockRepository_RejectGroupRequest_Call) Run(run func(ctx context.Context, reqID string)) *MockRepository_RejectGroupRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_RejectGroupRequest_Call) Return(err error) *MockRepository_RejectGroupRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RejectGroupRequest_Call) RunAndReturn(run func(ctx context.Context, reqID string) error) *MockRepository_RejectGroupRequest_Call {
	_c.Call.Return(run)
	return _c
}
