// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/eaguilar88/deu/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryMock is an autogenerated mock type for the Repository type
type RepositoryMock struct {
	mock.Mock
}

type RepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryMock) EXPECT() *RepositoryMock_Expecter {
	return &RepositoryMock_Expecter{mock: &_m.Mock}
}

// ApproveGroupRequest provides a mock function with given fields: ctx, reqID
func (_m *RepositoryMock) ApproveGroupRequest(ctx context.Context, reqID string) error {
	ret := _m.Called(ctx, reqID)

	if len(ret) == 0 {
		panic("no return value specified for ApproveGroupRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, reqID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryMock_ApproveGroupRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveGroupRequest'
type RepositoryMock_ApproveGroupRequest_Call struct {
	*mock.Call
}

// ApproveGroupRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - reqID string
func (_e *RepositoryMock_Expecter) ApproveGroupRequest(ctx interface{}, reqID interface{}) *RepositoryMock_ApproveGroupRequest_Call {
	return &RepositoryMock_ApproveGroupRequest_Call{Call: _e.mock.On("ApproveGroupRequest", ctx, reqID)}
}

func (_c *RepositoryMock_ApproveGroupRequest_Call) Run(run func(ctx context.Context, reqID string)) *RepositoryMock_ApproveGroupRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RepositoryMock_ApproveGroupRequest_Call) Return(_a0 error) *RepositoryMock_ApproveGroupRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryMock_ApproveGroupRequest_Call) RunAndReturn(run func(context.Context, string) error) *RepositoryMock_ApproveGroupRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupRequestByID provides a mock function with given fields: ctx, reqID
func (_m *RepositoryMock) GetGroupRequestByID(ctx context.Context, reqID string) (entities.GroupAuthRequest, error) {
	ret := _m.Called(ctx, reqID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupRequestByID")
	}

	var r0 entities.GroupAuthRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.GroupAuthRequest, error)); ok {
		return rf(ctx, reqID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.GroupAuthRequest); ok {
		r0 = rf(ctx, reqID)
	} else {
		r0 = ret.Get(0).(entities.GroupAuthRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, reqID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryMock_GetGroupRequestByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupRequestByID'
type RepositoryMock_GetGroupRequestByID_Call struct {
	*mock.Call
}

// GetGroupRequestByID is a helper method to define mock.On call
//   - ctx context.Context
//   - reqID string
func (_e *RepositoryMock_Expecter) GetGroupRequestByID(ctx interface{}, reqID interface{}) *RepositoryMock_GetGroupRequestByID_Call {
	return &RepositoryMock_GetGroupRequestByID_Call{Call: _e.mock.On("GetGroupRequestByID", ctx, reqID)}
}

func (_c *RepositoryMock_GetGroupRequestByID_Call) Run(run func(ctx context.Context, reqID string)) *RepositoryMock_GetGroupRequestByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RepositoryMock_GetGroupRequestByID_Call) Return(_a0 entities.GroupAuthRequest, _a1 error) *RepositoryMock_GetGroupRequestByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryMock_GetGroupRequestByID_Call) RunAndReturn(run func(context.Context, string) (entities.GroupAuthRequest, error)) *RepositoryMock_GetGroupRequestByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupRequestsByFaculty provides a mock function with given fields: ctx, faculty, pageScope
func (_m *RepositoryMock) GetGroupRequestsByFaculty(ctx context.Context, faculty entities.Faculty, pageScope entities.PageScope) ([]entities.GroupAuthRequest, entities.PageScope, error) {
	ret := _m.Called(ctx, faculty, pageScope)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupRequestsByFaculty")
	}

	var r0 []entities.GroupAuthRequest
	var r1 entities.PageScope
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Faculty, entities.PageScope) ([]entities.GroupAuthRequest, entities.PageScope, error)); ok {
		return rf(ctx, faculty, pageScope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.Faculty, entities.PageScope) []entities.GroupAuthRequest); ok {
		r0 = rf(ctx, faculty, pageScope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.GroupAuthRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.Faculty, entities.PageScope) entities.PageScope); ok {
		r1 = rf(ctx, faculty, pageScope)
	} else {
		r1 = ret.Get(1).(entities.PageScope)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entities.Faculty, entities.PageScope) error); ok {
		r2 = rf(ctx, faculty, pageScope)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RepositoryMock_GetGroupRequestsByFaculty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupRequestsByFaculty'
type RepositoryMock_GetGroupRequestsByFaculty_Call struct {
	*mock.Call
}

// GetGroupRequestsByFaculty is a helper method to define mock.On call
//   - ctx context.Context
//   - faculty entities.Faculty
//   - pageScope entities.PageScope
func (_e *RepositoryMock_Expecter) GetGroupRequestsByFaculty(ctx interface{}, faculty interface{}, pageScope interface{}) *RepositoryMock_GetGroupRequestsByFaculty_Call {
	return &RepositoryMock_GetGroupRequestsByFaculty_Call{Call: _e.mock.On("GetGroupRequestsByFaculty", ctx, faculty, pageScope)}
}

func (_c *RepositoryMock_GetGroupRequestsByFaculty_Call) Run(run func(ctx context.Context, faculty entities.Faculty, pageScope entities.PageScope)) *RepositoryMock_GetGroupRequestsByFaculty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.Faculty), args[2].(entities.PageScope))
	})
	return _c
}

func (_c *RepositoryMock_GetGroupRequestsByFaculty_Call) Return(_a0 []entities.GroupAuthRequest, _a1 entities.PageScope, _a2 error) *RepositoryMock_GetGroupRequestsByFaculty_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *RepositoryMock_GetGroupRequestsByFaculty_Call) RunAndReturn(run func(context.Context, entities.Faculty, entities.PageScope) ([]entities.GroupAuthRequest, entities.PageScope, error)) *RepositoryMock_GetGroupRequestsByFaculty_Call {
	_c.Call.Return(run)
	return _c
}

// RejectGroupRequest provides a mock function with given fields: ctx, reqID
func (_m *RepositoryMock) RejectGroupRequest(ctx context.Context, reqID string) error {
	ret := _m.Called(ctx, reqID)

	if len(ret) == 0 {
		panic("no return value specified for RejectGroupRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, reqID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryMock_RejectGroupRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectGroupRequest'
type RepositoryMock_RejectGroupRequest_Call struct {
	*mock.Call
}

// RejectGroupRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - reqID string
func (_e *RepositoryMock_Expecter) RejectGroupRequest(ctx interface{}, reqID interface{}) *RepositoryMock_RejectGroupRequest_Call {
	return &RepositoryMock_RejectGroupRequest_Call{Call: _e.mock.On("RejectGroupRequest", ctx, reqID)}
}

func (_c *RepositoryMock_RejectGroupRequest_Call) Run(run func(ctx context.Context, reqID string)) *RepositoryMock_RejectGroupRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RepositoryMock_RejectGroupRequest_Call) Return(_a0 error) *RepositoryMock_RejectGroupRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryMock_RejectGroupRequest_Call) RunAndReturn(run func(context.Context, string) error) *RepositoryMock_RejectGroupRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepositoryMock creates a new instance of RepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryMock {
	mock := &RepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
