// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/eaguilar88/deu/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ApproveGroupRequest provides a mock function for the type MockRepository
func (_mock *MockRepository) ApproveGroupRequest(ctx context.Context, reqID string) error {
	ret := _mock.Called(ctx, reqID)

	if len(ret) == 0 {
		panic("no return value specified for ApproveGroupRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, reqID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_ApproveGroupRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveGroupRequest'
type MockRepository_ApproveGroupRequest_Call struct {
	*mock.Call
}

// ApproveGroupRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - reqID string
func (_e *MockRepository_Expecter) ApproveGroupRequest(ctx interface{}, reqID interface{}) *MockRepository_ApproveGroupRequest_Call {
	return &MockRepository_ApproveGroupRequest_Call{Call: _e.mock.On("ApproveGroupRequest", ctx, reqID)}
}

func (_c *MockRepository_ApproveGroupRequest_Call) Run(run func(ctx context.Context, reqID string)) *MockRepository_ApproveGroupRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ApproveGroupRequest_Call) Return(err error) *MockRepository_ApproveGroupRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_ApproveGroupRequest_Call) RunAndReturn(run func(ctx context.Context, reqID string) error) *MockRepository_ApproveGroupRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupRequestByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetGroupRequestByID(ctx context.Context, reqID string) (entities.GroupRequest, error) {
	ret := _mock.Called(ctx, reqID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupRequestByID")
	}

	var r0 entities.GroupRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entities.GroupRequest, error)); ok {
		return returnFunc(ctx, reqID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entities.GroupRequest); ok {
		r0 = returnFunc(ctx, reqID)
	} else {
		r0 = ret.Get(0).(entities.GroupRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, reqID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetGroupRequestByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupRequestByID'
type MockRepository_GetGroupRequestByID_Call struct {
	*mock.Call
}

// GetGroupRequestByID is a helper method to define mock.On call
//   - ctx context.Context
//   - reqID string
func (_e *MockRepository_Expecter) GetGroupRequestByID(ctx interface{}, reqID interface{}) *MockRepository_GetGroupRequestByID_Call {
	return &MockRepository_GetGroupRequestByID_Call{Call: _e.mock.On("GetGroupRequestByID", ctx, reqID)}
}

func (_c *MockRepository_GetGroupRequestByID_Call) Run(run func(ctx context.Context, reqID string)) *MockRepository_GetGroupRequestByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetGroupRequestByID_Call) Return(groupRequest entities.GroupRequest, err error) *MockRepository_GetGroupRequestByID_Call {
	_c.Call.Return(groupRequest, err)
	return _c
}

func (_c *MockRepository_GetGroupRequestByID_Call) RunAndReturn(run func(ctx context.Context, reqID string) (entities.GroupRequest, error)) *MockRepository_GetGroupRequestByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupRequestsByFaculty provides a mock function for the type MockRepository
func (_mock *MockRepository) GetGroupRequestsByFaculty(ctx context.Context, faculty entities.Faculty, status string, pageScope entities.PageScope) ([]entities.GroupRequest, entities.PageScope, int, error) {
	ret := _mock.Called(ctx, faculty, status, pageScope)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupRequestsByFaculty")
	}

	var r0 []entities.GroupRequest
	var r1 entities.PageScope
	var r2 int
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Faculty, string, entities.PageScope) ([]entities.GroupRequest, entities.PageScope, int, error)); ok {
		return returnFunc(ctx, faculty, status, pageScope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Faculty, string, entities.PageScope) []entities.GroupRequest); ok {
		r0 = returnFunc(ctx, faculty, status, pageScope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.GroupRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Faculty, string, entities.PageScope) entities.PageScope); ok {
		r1 = returnFunc(ctx, faculty, status, pageScope)
	} else {
		r1 = ret.Get(1).(entities.PageScope)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, entities.Faculty, string, entities.PageScope) int); ok {
		r2 = returnFunc(ctx, faculty, status, pageScope)
	} else {
		r2 = ret.Get(2).(int)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, entities.Faculty, string, entities.PageScope) error); ok {
		r3 = returnFunc(ctx, faculty, status, pageScope)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockRepository_GetGroupRequestsByFaculty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupRequestsByFaculty'
type MockRepository_GetGroupRequestsByFaculty_Call struct {
	*mock.Call
}

// GetGroupRequestsByFaculty is a helper method to define mock.On call
//   - ctx context.Context
//   - faculty entities.Faculty
//   - status string
//   - pageScope entities.PageScope
func (_e *MockRepository_Expecter) GetGroupRequestsByFaculty(ctx interface{}, faculty interface{}, status interface{}, pageScope interface{}) *MockRepository_GetGroupRequestsByFaculty_Call {
	return &MockRepository_GetGroupRequestsByFaculty_Call{Call: _e.mock.On("GetGroupRequestsByFaculty", ctx, faculty, status, pageScope)}
}

func (_c *MockRepository_GetGroupRequestsByFaculty_Call) Run(run func(ctx context.Context, faculty entities.Faculty, status string, pageScope entities.PageScope)) *MockRepository_GetGroupRequestsByFaculty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Faculty
		if args[1] != nil {
			arg1 = args[1].(entities.Faculty)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 entities.PageScope
		if args[3] != nil {
			arg3 = args[3].(entities.PageScope)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_GetGroupRequestsByFaculty_Call) Return(groupRequests []entities.GroupRequest, pageScope1 entities.PageScope, n int, err error) *MockRepository_GetGroupRequestsByFaculty_Call {
	_c.Call.Return(groupRequests, pageScope1, n, err)
	return _c
}

func (_c *MockRepository_GetGroupRequestsByFaculty_Call) RunAndReturn(run func(ctx context.Context, faculty entities.Faculty, status string, pageScope entities.PageScope) ([]entities.GroupRequest, entities.PageScope, int, error)) *MockRepository_GetGroupRequestsByFaculty_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupRequestsByGroupID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetGroupRequestsByGroupID(ctx context.Context, groupID string) ([]entities.GroupRequest, error) {
	ret := _mock.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupRequestsByGroupID")
	}

	var r0 []entities.GroupRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]entities.GroupRequest, error)); ok {
		return returnFunc(ctx, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []entities.GroupRequest); ok {
		r0 = returnFunc(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.GroupRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetGroupRequestsByGroupID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupRequestsByGroupID'
type MockRepository_GetGroupRequestsByGroupID_Call struct {
	*mock.Call
}

// GetGroupRequestsByGroupID is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID string
func (_e *MockRepository_Expecter) GetGroupRequestsByGroupID(ctx interface{}, groupID interface{}) *MockRepository_GetGroupRequestsByGroupID_Call {
	return &MockRepository_GetGroupRequestsByGroupID_Call{Call: _e.mock.On("GetGroupRequestsByGroupID", ctx, groupID)}
}

func (_c *MockRepository_GetGroupRequestsByGroupID_Call) Run(run func(ctx context.Context, groupID string)) *MockRepository_GetGroupRequestsByGroupID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetGroupRequestsByGroupID_Call) Return(groupRequests []entities.GroupRequest, err error) *MockRepository_GetGroupRequestsByGroupID_Call {
	_c.Call.Return(groupRequests, err)
	return _c
}

func (_c *MockRepository_GetGroupRequestsByGroupID_Call) RunAndReturn(run func(ctx context.Context, groupID string) ([]entities.GroupRequest, error)) *MockRepository_GetGroupRequestsByGroupID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingGroupRequestsCounts provides a mock function for the type MockRepository
func (_mock *MockRepository) GetPendingGroupRequestsCounts(ctx context.Context) ([]entities.FacultyPendingCount, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingGroupRequestsCounts")
	}

	var r0 []entities.FacultyPendingCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entities.FacultyPendingCount, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entities.FacultyPendingCount); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.FacultyPendingCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetPendingGroupRequestsCounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingGroupRequestsCounts'
type MockRepository_GetPendingGroupRequestsCounts_Call struct {
	*mock.Call
}

// GetPendingGroupRequestsCounts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetPendingGroupRequestsCounts(ctx interface{}) *MockRepository_GetPendingGroupRequestsCounts_Call {
	return &MockRepository_GetPendingGroupRequestsCounts_Call{Call: _e.mock.On("GetPendingGroupRequestsCounts", ctx)}
}

func (_c *MockRepository_GetPendingGroupRequestsCounts_Call) Run(run func(ctx context.Context)) *MockRepository_GetPendingGroupRequestsCounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetPendingGroupRequestsCounts_Call) Return(facultyPendingCounts []entities.FacultyPendingCount, err error) *MockRepository_GetPendingGroupRequestsCounts_Call {
	_c.Call.Return(facultyPendingCounts, err)
	return _c
}

func (_c *MockRepository_GetPendingGroupRequestsCounts_Call) RunAndReturn(run func(ctx context.Context) ([]entities.FacultyPendingCount, error)) *MockRepository_GetPendingGroupRequestsCounts_Call {
	_c.Call.Return(run)
	return _c
}

// RejectGroupRequest provides a mock function for the type MockRepository
func (_mock *MockRepository) RejectGroupRequest(ctx context.Context, reqID string) error {
	ret := _mock.Called(ctx, reqID)

	if len(ret) == 0 {
		panic("no return value specified for RejectGroupRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, reqID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RejectGroupRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectGroupRequest'
type MockRepository_RejectGroupRequest_Call struct {
	*mock.Call
}

// RejectGroupRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - reqID string
func (_e *MockRepository_Expecter) RejectGroupRequest(ctx interface{}, reqID interface{}) *MockRepository_RejectGroupRequest_Call {
	return &MockRepository_RejectGroupRequest_Call{Call: _e.mock.On("RejectGroupRequest", ctx, reqID)}
}

func (_c *MockRepository_RejectGroupRequest_Call) Run(run func(ctx context.Context, reqID string)) *MockRepository_RejectGroupRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_RejectGroupRequest_Call) Return(err error) *MockRepository_RejectGroupRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RejectGroupRequest_Call) RunAndReturn(run func(ctx context.Context, reqID string) error) *MockRepository_RejectGroupRequest_Call {
	_c.Call.Return(run)
	return _c
}
