// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/eaguilar88/deu/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryMock is an autogenerated mock type for the Repository type
type RepositoryMock struct {
	mock.Mock
}

type RepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryMock) EXPECT() *RepositoryMock_Expecter {
	return &RepositoryMock_Expecter{mock: &_m.Mock}
}

// CreateEndorsement provides a mock function with given fields: ctx, endorsement
func (_m *RepositoryMock) CreateEndorsement(ctx context.Context, endorsement entities.Endorsement) (int64, error) {
	ret := _m.Called(ctx, endorsement)

	if len(ret) == 0 {
		panic("no return value specified for CreateEndorsement")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Endorsement) (int64, error)); ok {
		return rf(ctx, endorsement)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.Endorsement) int64); ok {
		r0 = rf(ctx, endorsement)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.Endorsement) error); ok {
		r1 = rf(ctx, endorsement)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryMock_CreateEndorsement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEndorsement'
type RepositoryMock_CreateEndorsement_Call struct {
	*mock.Call
}

// CreateEndorsement is a helper method to define mock.On call
//   - ctx context.Context
//   - endorsement entities.Endorsement
func (_e *RepositoryMock_Expecter) CreateEndorsement(ctx interface{}, endorsement interface{}) *RepositoryMock_CreateEndorsement_Call {
	return &RepositoryMock_CreateEndorsement_Call{Call: _e.mock.On("CreateEndorsement", ctx, endorsement)}
}

func (_c *RepositoryMock_CreateEndorsement_Call) Run(run func(ctx context.Context, endorsement entities.Endorsement)) *RepositoryMock_CreateEndorsement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.Endorsement))
	})
	return _c
}

func (_c *RepositoryMock_CreateEndorsement_Call) Return(_a0 int64, _a1 error) *RepositoryMock_CreateEndorsement_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryMock_CreateEndorsement_Call) RunAndReturn(run func(context.Context, entities.Endorsement) (int64, error)) *RepositoryMock_CreateEndorsement_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEndorsement provides a mock function with given fields: ctx, endorsementID
func (_m *RepositoryMock) DeleteEndorsement(ctx context.Context, endorsementID string) error {
	ret := _m.Called(ctx, endorsementID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEndorsement")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, endorsementID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryMock_DeleteEndorsement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEndorsement'
type RepositoryMock_DeleteEndorsement_Call struct {
	*mock.Call
}

// DeleteEndorsement is a helper method to define mock.On call
//   - ctx context.Context
//   - endorsementID string
func (_e *RepositoryMock_Expecter) DeleteEndorsement(ctx interface{}, endorsementID interface{}) *RepositoryMock_DeleteEndorsement_Call {
	return &RepositoryMock_DeleteEndorsement_Call{Call: _e.mock.On("DeleteEndorsement", ctx, endorsementID)}
}

func (_c *RepositoryMock_DeleteEndorsement_Call) Run(run func(ctx context.Context, endorsementID string)) *RepositoryMock_DeleteEndorsement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RepositoryMock_DeleteEndorsement_Call) Return(_a0 error) *RepositoryMock_DeleteEndorsement_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryMock_DeleteEndorsement_Call) RunAndReturn(run func(context.Context, string) error) *RepositoryMock_DeleteEndorsement_Call {
	_c.Call.Return(run)
	return _c
}

// GetEndorsement provides a mock function with given fields: ctx, endorsementID
func (_m *RepositoryMock) GetEndorsement(ctx context.Context, endorsementID string) (entities.Endorsement, error) {
	ret := _m.Called(ctx, endorsementID)

	if len(ret) == 0 {
		panic("no return value specified for GetEndorsement")
	}

	var r0 entities.Endorsement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.Endorsement, error)); ok {
		return rf(ctx, endorsementID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.Endorsement); ok {
		r0 = rf(ctx, endorsementID)
	} else {
		r0 = ret.Get(0).(entities.Endorsement)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, endorsementID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryMock_GetEndorsement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEndorsement'
type RepositoryMock_GetEndorsement_Call struct {
	*mock.Call
}

// GetEndorsement is a helper method to define mock.On call
//   - ctx context.Context
//   - endorsementID string
func (_e *RepositoryMock_Expecter) GetEndorsement(ctx interface{}, endorsementID interface{}) *RepositoryMock_GetEndorsement_Call {
	return &RepositoryMock_GetEndorsement_Call{Call: _e.mock.On("GetEndorsement", ctx, endorsementID)}
}

func (_c *RepositoryMock_GetEndorsement_Call) Run(run func(ctx context.Context, endorsementID string)) *RepositoryMock_GetEndorsement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RepositoryMock_GetEndorsement_Call) Return(_a0 entities.Endorsement, _a1 error) *RepositoryMock_GetEndorsement_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryMock_GetEndorsement_Call) RunAndReturn(run func(context.Context, string) (entities.Endorsement, error)) *RepositoryMock_GetEndorsement_Call {
	_c.Call.Return(run)
	return _c
}

// GetEndorsements provides a mock function with given fields: ctx, pageScope
func (_m *RepositoryMock) GetEndorsements(ctx context.Context, pageScope entities.PageScope) ([]entities.Endorsement, entities.PageScope, error) {
	ret := _m.Called(ctx, pageScope)

	if len(ret) == 0 {
		panic("no return value specified for GetEndorsements")
	}

	var r0 []entities.Endorsement
	var r1 entities.PageScope
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.PageScope) ([]entities.Endorsement, entities.PageScope, error)); ok {
		return rf(ctx, pageScope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.PageScope) []entities.Endorsement); ok {
		r0 = rf(ctx, pageScope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Endorsement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.PageScope) entities.PageScope); ok {
		r1 = rf(ctx, pageScope)
	} else {
		r1 = ret.Get(1).(entities.PageScope)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entities.PageScope) error); ok {
		r2 = rf(ctx, pageScope)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RepositoryMock_GetEndorsements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEndorsements'
type RepositoryMock_GetEndorsements_Call struct {
	*mock.Call
}

// GetEndorsements is a helper method to define mock.On call
//   - ctx context.Context
//   - pageScope entities.PageScope
func (_e *RepositoryMock_Expecter) GetEndorsements(ctx interface{}, pageScope interface{}) *RepositoryMock_GetEndorsements_Call {
	return &RepositoryMock_GetEndorsements_Call{Call: _e.mock.On("GetEndorsements", ctx, pageScope)}
}

func (_c *RepositoryMock_GetEndorsements_Call) Run(run func(ctx context.Context, pageScope entities.PageScope)) *RepositoryMock_GetEndorsements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.PageScope))
	})
	return _c
}

func (_c *RepositoryMock_GetEndorsements_Call) Return(_a0 []entities.Endorsement, _a1 entities.PageScope, _a2 error) *RepositoryMock_GetEndorsements_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *RepositoryMock_GetEndorsements_Call) RunAndReturn(run func(context.Context, entities.PageScope) ([]entities.Endorsement, entities.PageScope, error)) *RepositoryMock_GetEndorsements_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEndorsement provides a mock function with given fields: ctx, endorsementID, endorsement
func (_m *RepositoryMock) UpdateEndorsement(ctx context.Context, endorsementID string, endorsement entities.Endorsement) error {
	ret := _m.Called(ctx, endorsementID, endorsement)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEndorsement")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.Endorsement) error); ok {
		r0 = rf(ctx, endorsementID, endorsement)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryMock_UpdateEndorsement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEndorsement'
type RepositoryMock_UpdateEndorsement_Call struct {
	*mock.Call
}

// UpdateEndorsement is a helper method to define mock.On call
//   - ctx context.Context
//   - endorsementID string
//   - endorsement entities.Endorsement
func (_e *RepositoryMock_Expecter) UpdateEndorsement(ctx interface{}, endorsementID interface{}, endorsement interface{}) *RepositoryMock_UpdateEndorsement_Call {
	return &RepositoryMock_UpdateEndorsement_Call{Call: _e.mock.On("UpdateEndorsement", ctx, endorsementID, endorsement)}
}

func (_c *RepositoryMock_UpdateEndorsement_Call) Run(run func(ctx context.Context, endorsementID string, endorsement entities.Endorsement)) *RepositoryMock_UpdateEndorsement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entities.Endorsement))
	})
	return _c
}

func (_c *RepositoryMock_UpdateEndorsement_Call) Return(_a0 error) *RepositoryMock_UpdateEndorsement_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryMock_UpdateEndorsement_Call) RunAndReturn(run func(context.Context, string, entities.Endorsement) error) *RepositoryMock_UpdateEndorsement_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepositoryMock creates a new instance of RepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryMock {
	mock := &RepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
