// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/eaguilar88/deu/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryMock is an autogenerated mock type for the Repository type
type RepositoryMock struct {
	mock.Mock
}

type RepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryMock) EXPECT() *RepositoryMock_Expecter {
	return &RepositoryMock_Expecter{mock: &_m.Mock}
}

// CreateCourse provides a mock function with given fields: ctx, user
func (_m *RepositoryMock) CreateCourse(ctx context.Context, user entities.Course) (int64, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourse")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Course) (int64, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.Course) int64); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.Course) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryMock_CreateCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCourse'
type RepositoryMock_CreateCourse_Call struct {
	*mock.Call
}

// CreateCourse is a helper method to define mock.On call
//   - ctx context.Context
//   - user entities.Course
func (_e *RepositoryMock_Expecter) CreateCourse(ctx interface{}, user interface{}) *RepositoryMock_CreateCourse_Call {
	return &RepositoryMock_CreateCourse_Call{Call: _e.mock.On("CreateCourse", ctx, user)}
}

func (_c *RepositoryMock_CreateCourse_Call) Run(run func(ctx context.Context, user entities.Course)) *RepositoryMock_CreateCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.Course))
	})
	return _c
}

func (_c *RepositoryMock_CreateCourse_Call) Return(_a0 int64, _a1 error) *RepositoryMock_CreateCourse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryMock_CreateCourse_Call) RunAndReturn(run func(context.Context, entities.Course) (int64, error)) *RepositoryMock_CreateCourse_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCourse provides a mock function with given fields: ctx, userID
func (_m *RepositoryMock) DeleteCourse(ctx context.Context, userID int) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryMock_DeleteCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCourse'
type RepositoryMock_DeleteCourse_Call struct {
	*mock.Call
}

// DeleteCourse is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *RepositoryMock_Expecter) DeleteCourse(ctx interface{}, userID interface{}) *RepositoryMock_DeleteCourse_Call {
	return &RepositoryMock_DeleteCourse_Call{Call: _e.mock.On("DeleteCourse", ctx, userID)}
}

func (_c *RepositoryMock_DeleteCourse_Call) Run(run func(ctx context.Context, userID int)) *RepositoryMock_DeleteCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *RepositoryMock_DeleteCourse_Call) Return(_a0 error) *RepositoryMock_DeleteCourse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryMock_DeleteCourse_Call) RunAndReturn(run func(context.Context, int) error) *RepositoryMock_DeleteCourse_Call {
	_c.Call.Return(run)
	return _c
}

// GetCourse provides a mock function with given fields: ctx, userID
func (_m *RepositoryMock) GetCourse(ctx context.Context, userID int) (entities.Course, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCourse")
	}

	var r0 entities.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (entities.Course, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) entities.Course); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(entities.Course)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryMock_GetCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCourse'
type RepositoryMock_GetCourse_Call struct {
	*mock.Call
}

// GetCourse is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *RepositoryMock_Expecter) GetCourse(ctx interface{}, userID interface{}) *RepositoryMock_GetCourse_Call {
	return &RepositoryMock_GetCourse_Call{Call: _e.mock.On("GetCourse", ctx, userID)}
}

func (_c *RepositoryMock_GetCourse_Call) Run(run func(ctx context.Context, userID int)) *RepositoryMock_GetCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *RepositoryMock_GetCourse_Call) Return(_a0 entities.Course, _a1 error) *RepositoryMock_GetCourse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryMock_GetCourse_Call) RunAndReturn(run func(context.Context, int) (entities.Course, error)) *RepositoryMock_GetCourse_Call {
	_c.Call.Return(run)
	return _c
}

// GetCourses provides a mock function with given fields: ctx, pageScope
func (_m *RepositoryMock) GetCourses(ctx context.Context, pageScope entities.PageScope) ([]entities.Course, entities.PageScope, error) {
	ret := _m.Called(ctx, pageScope)

	if len(ret) == 0 {
		panic("no return value specified for GetCourses")
	}

	var r0 []entities.Course
	var r1 entities.PageScope
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.PageScope) ([]entities.Course, entities.PageScope, error)); ok {
		return rf(ctx, pageScope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.PageScope) []entities.Course); ok {
		r0 = rf(ctx, pageScope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.PageScope) entities.PageScope); ok {
		r1 = rf(ctx, pageScope)
	} else {
		r1 = ret.Get(1).(entities.PageScope)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entities.PageScope) error); ok {
		r2 = rf(ctx, pageScope)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RepositoryMock_GetCourses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCourses'
type RepositoryMock_GetCourses_Call struct {
	*mock.Call
}

// GetCourses is a helper method to define mock.On call
//   - ctx context.Context
//   - pageScope entities.PageScope
func (_e *RepositoryMock_Expecter) GetCourses(ctx interface{}, pageScope interface{}) *RepositoryMock_GetCourses_Call {
	return &RepositoryMock_GetCourses_Call{Call: _e.mock.On("GetCourses", ctx, pageScope)}
}

func (_c *RepositoryMock_GetCourses_Call) Run(run func(ctx context.Context, pageScope entities.PageScope)) *RepositoryMock_GetCourses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.PageScope))
	})
	return _c
}

func (_c *RepositoryMock_GetCourses_Call) Return(_a0 []entities.Course, _a1 entities.PageScope, _a2 error) *RepositoryMock_GetCourses_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *RepositoryMock_GetCourses_Call) RunAndReturn(run func(context.Context, entities.PageScope) ([]entities.Course, entities.PageScope, error)) *RepositoryMock_GetCourses_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCourse provides a mock function with given fields: ctx, userID, user
func (_m *RepositoryMock) UpdateCourse(ctx context.Context, userID int, user entities.Course) error {
	ret := _m.Called(ctx, userID, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, entities.Course) error); ok {
		r0 = rf(ctx, userID, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryMock_UpdateCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCourse'
type RepositoryMock_UpdateCourse_Call struct {
	*mock.Call
}

// UpdateCourse is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - user entities.Course
func (_e *RepositoryMock_Expecter) UpdateCourse(ctx interface{}, userID interface{}, user interface{}) *RepositoryMock_UpdateCourse_Call {
	return &RepositoryMock_UpdateCourse_Call{Call: _e.mock.On("UpdateCourse", ctx, userID, user)}
}

func (_c *RepositoryMock_UpdateCourse_Call) Run(run func(ctx context.Context, userID int, user entities.Course)) *RepositoryMock_UpdateCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(entities.Course))
	})
	return _c
}

func (_c *RepositoryMock_UpdateCourse_Call) Return(_a0 error) *RepositoryMock_UpdateCourse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryMock_UpdateCourse_Call) RunAndReturn(run func(context.Context, int, entities.Course) error) *RepositoryMock_UpdateCourse_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepositoryMock creates a new instance of RepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryMock {
	mock := &RepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
