// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/eaguilar88/deu/internal/group_dashboards"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetDeuDashboardMetrics provides a mock function for the type MockRepository
func (_mock *MockRepository) GetDeuDashboardMetrics(ctx context.Context) (int, []group_dashboards.ResourceRequestsByFaculty, int, int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDeuDashboardMetrics")
	}

	var r0 int
	var r1 []group_dashboards.ResourceRequestsByFaculty
	var r2 int
	var r3 int
	var r4 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, []group_dashboards.ResourceRequestsByFaculty, int, int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) []group_dashboards.ResourceRequestsByFaculty); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]group_dashboards.ResourceRequestsByFaculty)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) int); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Get(2).(int)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context) int); ok {
		r3 = returnFunc(ctx)
	} else {
		r3 = ret.Get(3).(int)
	}
	if returnFunc, ok := ret.Get(4).(func(context.Context) error); ok {
		r4 = returnFunc(ctx)
	} else {
		r4 = ret.Error(4)
	}
	return r0, r1, r2, r3, r4
}

// MockRepository_GetDeuDashboardMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeuDashboardMetrics'
type MockRepository_GetDeuDashboardMetrics_Call struct {
	*mock.Call
}

// GetDeuDashboardMetrics is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetDeuDashboardMetrics(ctx interface{}) *MockRepository_GetDeuDashboardMetrics_Call {
	return &MockRepository_GetDeuDashboardMetrics_Call{Call: _e.mock.On("GetDeuDashboardMetrics", ctx)}
}

func (_c *MockRepository_GetDeuDashboardMetrics_Call) Run(run func(ctx context.Context)) *MockRepository_GetDeuDashboardMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetDeuDashboardMetrics_Call) Return(pendingDeu int, rawResourceReqs []group_dashboards.ResourceRequestsByFaculty, activeGroups int, inactiveGroups int, err error) *MockRepository_GetDeuDashboardMetrics_Call {
	_c.Call.Return(pendingDeu, rawResourceReqs, activeGroups, inactiveGroups, err)
	return _c
}

func (_c *MockRepository_GetDeuDashboardMetrics_Call) RunAndReturn(run func(ctx context.Context) (int, []group_dashboards.ResourceRequestsByFaculty, int, int, error)) *MockRepository_GetDeuDashboardMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetFacultyDashboardMetrics provides a mock function for the type MockRepository
func (_mock *MockRepository) GetFacultyDashboardMetrics(ctx context.Context, faculty string) (int, int, error) {
	ret := _mock.Called(ctx, faculty)

	if len(ret) == 0 {
		panic("no return value specified for GetFacultyDashboardMetrics")
	}

	var r0 int
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, int, error)); ok {
		return returnFunc(ctx, faculty)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, faculty)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) int); ok {
		r1 = returnFunc(ctx, faculty)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, faculty)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_GetFacultyDashboardMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFacultyDashboardMetrics'
type MockRepository_GetFacultyDashboardMetrics_Call struct {
	*mock.Call
}

// GetFacultyDashboardMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - faculty string
func (_e *MockRepository_Expecter) GetFacultyDashboardMetrics(ctx interface{}, faculty interface{}) *MockRepository_GetFacultyDashboardMetrics_Call {
	return &MockRepository_GetFacultyDashboardMetrics_Call{Call: _e.mock.On("GetFacultyDashboardMetrics", ctx, faculty)}
}

func (_c *MockRepository_GetFacultyDashboardMetrics_Call) Run(run func(ctx context.Context, faculty string)) *MockRepository_GetFacultyDashboardMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetFacultyDashboardMetrics_Call) Return(pendingRequests int, totalGroups int, err error) *MockRepository_GetFacultyDashboardMetrics_Call {
	_c.Call.Return(pendingRequests, totalGroups, err)
	return _c
}

func (_c *MockRepository_GetFacultyDashboardMetrics_Call) RunAndReturn(run func(ctx context.Context, faculty string) (int, int, error)) *MockRepository_GetFacultyDashboardMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupDashboardMetrics provides a mock function for the type MockRepository
func (_mock *MockRepository) GetGroupDashboardMetrics(ctx context.Context, groupID string) (int, int, error) {
	ret := _mock.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupDashboardMetrics")
	}

	var r0 int
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, int, error)); ok {
		return returnFunc(ctx, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, groupID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) int); ok {
		r1 = returnFunc(ctx, groupID)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, groupID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_GetGroupDashboardMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupDashboardMetrics'
type MockRepository_GetGroupDashboardMetrics_Call struct {
	*mock.Call
}

// GetGroupDashboardMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID string
func (_e *MockRepository_Expecter) GetGroupDashboardMetrics(ctx interface{}, groupID interface{}) *MockRepository_GetGroupDashboardMetrics_Call {
	return &MockRepository_GetGroupDashboardMetrics_Call{Call: _e.mock.On("GetGroupDashboardMetrics", ctx, groupID)}
}

func (_c *MockRepository_GetGroupDashboardMetrics_Call) Run(run func(ctx context.Context, groupID string)) *MockRepository_GetGroupDashboardMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetGroupDashboardMetrics_Call) Return(upcoming int, pendingReports int, err error) *MockRepository_GetGroupDashboardMetrics_Call {
	_c.Call.Return(upcoming, pendingReports, err)
	return _c
}

func (_c *MockRepository_GetGroupDashboardMetrics_Call) RunAndReturn(run func(ctx context.Context, groupID string) (int, int, error)) *MockRepository_GetGroupDashboardMetrics_Call {
	_c.Call.Return(run)
	return _c
}
