// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/eaguilar88/deu/internal/group_dashboards"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetDeuDashboard provides a mock function for the type MockService
func (_mock *MockService) GetDeuDashboard(ctx context.Context) (*group_dashboards.DeuDashboardResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDeuDashboard")
	}

	var r0 *group_dashboards.DeuDashboardResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*group_dashboards.DeuDashboardResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *group_dashboards.DeuDashboardResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*group_dashboards.DeuDashboardResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetDeuDashboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeuDashboard'
type MockService_GetDeuDashboard_Call struct {
	*mock.Call
}

// GetDeuDashboard is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetDeuDashboard(ctx interface{}) *MockService_GetDeuDashboard_Call {
	return &MockService_GetDeuDashboard_Call{Call: _e.mock.On("GetDeuDashboard", ctx)}
}

func (_c *MockService_GetDeuDashboard_Call) Run(run func(ctx context.Context)) *MockService_GetDeuDashboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetDeuDashboard_Call) Return(deuDashboardResponse *group_dashboards.DeuDashboardResponse, err error) *MockService_GetDeuDashboard_Call {
	_c.Call.Return(deuDashboardResponse, err)
	return _c
}

func (_c *MockService_GetDeuDashboard_Call) RunAndReturn(run func(ctx context.Context) (*group_dashboards.DeuDashboardResponse, error)) *MockService_GetDeuDashboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetFacultyDashboard provides a mock function for the type MockService
func (_mock *MockService) GetFacultyDashboard(ctx context.Context, faculty string) (*group_dashboards.FacultyDashboardResponse, error) {
	ret := _mock.Called(ctx, faculty)

	if len(ret) == 0 {
		panic("no return value specified for GetFacultyDashboard")
	}

	var r0 *group_dashboards.FacultyDashboardResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*group_dashboards.FacultyDashboardResponse, error)); ok {
		return returnFunc(ctx, faculty)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *group_dashboards.FacultyDashboardResponse); ok {
		r0 = returnFunc(ctx, faculty)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*group_dashboards.FacultyDashboardResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, faculty)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetFacultyDashboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFacultyDashboard'
type MockService_GetFacultyDashboard_Call struct {
	*mock.Call
}

// GetFacultyDashboard is a helper method to define mock.On call
//   - ctx context.Context
//   - faculty string
func (_e *MockService_Expecter) GetFacultyDashboard(ctx interface{}, faculty interface{}) *MockService_GetFacultyDashboard_Call {
	return &MockService_GetFacultyDashboard_Call{Call: _e.mock.On("GetFacultyDashboard", ctx, faculty)}
}

func (_c *MockService_GetFacultyDashboard_Call) Run(run func(ctx context.Context, faculty string)) *MockService_GetFacultyDashboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetFacultyDashboard_Call) Return(facultyDashboardResponse *group_dashboards.FacultyDashboardResponse, err error) *MockService_GetFacultyDashboard_Call {
	_c.Call.Return(facultyDashboardResponse, err)
	return _c
}

func (_c *MockService_GetFacultyDashboard_Call) RunAndReturn(run func(ctx context.Context, faculty string) (*group_dashboards.FacultyDashboardResponse, error)) *MockService_GetFacultyDashboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupDashboard provides a mock function for the type MockService
func (_mock *MockService) GetGroupDashboard(ctx context.Context, groupID string) (*group_dashboards.GroupDashboardResponse, error) {
	ret := _mock.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupDashboard")
	}

	var r0 *group_dashboards.GroupDashboardResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*group_dashboards.GroupDashboardResponse, error)); ok {
		return returnFunc(ctx, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *group_dashboards.GroupDashboardResponse); ok {
		r0 = returnFunc(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*group_dashboards.GroupDashboardResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetGroupDashboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupDashboard'
type MockService_GetGroupDashboard_Call struct {
	*mock.Call
}

// GetGroupDashboard is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID string
func (_e *MockService_Expecter) GetGroupDashboard(ctx interface{}, groupID interface{}) *MockService_GetGroupDashboard_Call {
	return &MockService_GetGroupDashboard_Call{Call: _e.mock.On("GetGroupDashboard", ctx, groupID)}
}

func (_c *MockService_GetGroupDashboard_Call) Run(run func(ctx context.Context, groupID string)) *MockService_GetGroupDashboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetGroupDashboard_Call) Return(groupDashboardResponse *group_dashboards.GroupDashboardResponse, err error) *MockService_GetGroupDashboard_Call {
	_c.Call.Return(groupDashboardResponse, err)
	return _c
}

func (_c *MockService_GetGroupDashboard_Call) RunAndReturn(run func(ctx context.Context, groupID string) (*group_dashboards.GroupDashboardResponse, error)) *MockService_GetGroupDashboard_Call {
	_c.Call.Return(run)
	return _c
}
