// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/eaguilar88/deu/internal/email"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMailClient creates a new instance of MockMailClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockMailClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockMailClient is an autogenerated mock type for the MailClient type
type MockMailClient struct {
	mock.Mock
}

type MockMailClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMailClient) EXPECT() *MockMailClient_Expecter {
	return &MockMailClient_Expecter{mock: &_m.Mock}
}

// SendTemplateWithAttachments provides a mock function for the type MockMailClient
func (_mock *MockMailClient) SendTemplateWithAttachments(ctx context.Context, to string, tmpl email.Template, data any, attachments []email.Attachment) error {
	ret := _mock.Called(ctx, to, tmpl, data, attachments)

	if len(ret) == 0 {
		panic("no return value specified for SendTemplateWithAttachments")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, email.Template, any, []email.Attachment) error); ok {
		r0 = returnFunc(ctx, to, tmpl, data, attachments)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMailClient_SendTemplateWithAttachments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTemplateWithAttachments'
type MockMailClient_SendTemplateWithAttachments_Call struct {
	*mock.Call
}

// SendTemplateWithAttachments is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - tmpl email.Template
//   - data any
//   - attachments []email.Attachment
func (_e *MockMailClient_Expecter) SendTemplateWithAttachments(ctx any, to any, tmpl any, data any, attachments any) *MockMailClient_SendTemplateWithAttachments_Call {
	return &MockMailClient_SendTemplateWithAttachments_Call{Call: _e.mock.On("SendTemplateWithAttachments", ctx, to, tmpl, data, attachments)}
}

func (_c *MockMailClient_SendTemplateWithAttachments_Call) Run(run func(ctx context.Context, to string, tmpl email.Template, data any, attachments []email.Attachment)) *MockMailClient_SendTemplateWithAttachments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 email.Template
		if args[2] != nil {
			arg2 = args[2].(email.Template)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		var arg4 []email.Attachment
		if args[4] != nil {
			arg4 = args[4].([]email.Attachment)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockMailClient_SendTemplateWithAttachments_Call) Return(err error) *MockMailClient_SendTemplateWithAttachments_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMailClient_SendTemplateWithAttachments_Call) RunAndReturn(run func(ctx context.Context, to string, tmpl email.Template, data any, attachments []email.Attachment) error) *MockMailClient_SendTemplateWithAttachments_Call {
	_c.Call.Return(run)
	return _c
}
