CREATE SCHEMA "deu";

SET search_path TO "deu";

CREATE TYPE "provider_type" AS ENUM (
  'user',
  'extension_group'
);

CREATE TYPE "education_level" AS ENUM (
  'bachiller',
  'universitario_incompleta',
  'universitaria_completa',
  'posgrado'
);

CREATE TYPE "request_status" AS ENUM (
  'created',
  'under_review',
  'rejected',
  'approved'
);

CREATE TYPE "contact_type" AS ENUM (
  'user',
  'course',
  'extension_group'
);

CREATE TYPE "course_participant_status" AS ENUM (
  'abandoned',
  'approved',
  'failed'
);

CREATE TABLE "deu"."users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "ci" integer UNIQUE,
  "username" varchar UNIQUE,
  "first_name" varchar,
  "last_name" varchar,
  "date_of_birth" date,
  "gender" varchar,
  "education" education_level,
  "address" varchar,
  "created_at" timestamp,
  "updated_at" timestamp,
  "password" char(60)
);

CREATE TABLE "deu"."providers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "entity_id" integer NOT NULL,
  "entity_type" provider_type,
  "registration_date" date,
  "code" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "deu"."extension_group" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar,
  "description" text,
  "objective" text,
  "action" text,
  "reach" text,
  "path" varchar
);

CREATE TABLE "deu"."endorsment_requests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" integer,
  "status" request_status,
  "path" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "deu"."courses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" integer,
  "endorsment_id" integer,
  "endorsed_by" varchar,
  "objectives" text,
  "content" text,
  "cost" float,
  "location" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "deu"."contact_info" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "entity_id" integer,
  "entity_type" contact_type,
  "email" varchar,
  "phone" varchar
);

CREATE TABLE "deu"."course_cycles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "course_id" integer,
  "start_date" date,
  "end_date" date,
  "inscription_date" date,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "deu"."course_participants" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" integer,
  "course_cycle_id" integer,
  "participant_status" course_participant_status,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "deu"."roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar UNIQUE,
  "description" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "deu"."user_roles" (
  "user_id" integer,
  "role_id" integer,
  "created_at" timestamp,
  "updated_at" timestamp,
  PRIMARY KEY ("user_id", "role_id")
);

CREATE TABLE "deu"."activities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar,
  "description" text,
  "date" date,
  "path" varchar,
  "location" varchar,
  "assistants" integer
);

CREATE UNIQUE INDEX ON "deu"."providers" ("entity_id", "entity_type");

CREATE UNIQUE INDEX ON "deu"."course_participants" ("user_id", "course_cycle_id");

COMMENT ON TABLE "deu"."roles" IS 'Los roles son: root - admin - facilitador - estudiante - extensión';

ALTER TABLE "deu"."endorsment_requests" ADD FOREIGN KEY ("user_id") REFERENCES "deu"."users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "deu"."courses" ADD FOREIGN KEY ("user_id") REFERENCES "deu"."users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "deu"."courses" ADD FOREIGN KEY ("endorsment_id") REFERENCES "deu"."endorsment_requests" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "deu"."user_roles" ADD FOREIGN KEY ("role_id") REFERENCES "deu"."roles" ("id");

ALTER TABLE "deu"."user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "deu"."users" ("id");

ALTER TABLE "deu"."course_cycles" ADD FOREIGN KEY ("course_id") REFERENCES "deu"."courses" ("id");

ALTER TABLE "deu"."course_participants" ADD FOREIGN KEY ("course_cycle_id") REFERENCES "deu"."course_cycles" ("id");

ALTER TABLE "deu"."course_participants" ADD FOREIGN KEY ("user_id") REFERENCES "deu"."users" ("id");

ALTER TABLE "deu"."contact_info" ADD FOREIGN KEY ("entity_id") REFERENCES "deu"."courses" ("id");

ALTER TABLE "deu"."contact_info" ADD FOREIGN KEY ("entity_id") REFERENCES "deu"."users" ("id");

ALTER TABLE "deu"."contact_info" ADD FOREIGN KEY ("entity_id") REFERENCES "deu"."extension_group" ("id");

ALTER TABLE "deu"."providers" ADD FOREIGN KEY ("entity_id") REFERENCES "deu"."users" ("id");

ALTER TABLE "deu"."providers" ADD FOREIGN KEY ("entity_id") REFERENCES "deu"."extension_group" ("id");
