// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/eaguilar88/deu/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ApproveCourseCycleCloseRequest provides a mock function for the type MockRepository
func (_mock *MockRepository) ApproveCourseCycleCloseRequest(ctx context.Context, id string, reviewerID string, cycleID string) error {
	ret := _mock.Called(ctx, id, reviewerID, cycleID)

	if len(ret) == 0 {
		panic("no return value specified for ApproveCourseCycleCloseRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, id, reviewerID, cycleID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_ApproveCourseCycleCloseRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveCourseCycleCloseRequest'
type MockRepository_ApproveCourseCycleCloseRequest_Call struct {
	*mock.Call
}

// ApproveCourseCycleCloseRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reviewerID string
//   - cycleID string
func (_e *MockRepository_Expecter) ApproveCourseCycleCloseRequest(ctx interface{}, id interface{}, reviewerID interface{}, cycleID interface{}) *MockRepository_ApproveCourseCycleCloseRequest_Call {
	return &MockRepository_ApproveCourseCycleCloseRequest_Call{Call: _e.mock.On("ApproveCourseCycleCloseRequest", ctx, id, reviewerID, cycleID)}
}

func (_c *MockRepository_ApproveCourseCycleCloseRequest_Call) Run(run func(ctx context.Context, id string, reviewerID string, cycleID string)) *MockRepository_ApproveCourseCycleCloseRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_ApproveCourseCycleCloseRequest_Call) Return(err error) *MockRepository_ApproveCourseCycleCloseRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_ApproveCourseCycleCloseRequest_Call) RunAndReturn(run func(ctx context.Context, id string, reviewerID string, cycleID string) error) *MockRepository_ApproveCourseCycleCloseRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCourseCycleCloseRequest provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateCourseCycleCloseRequest(ctx context.Context, cycleID int64, submittedByID int64) (int64, error) {
	ret := _mock.Called(ctx, cycleID, submittedByID)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourseCycleCloseRequest")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (int64, error)); ok {
		return returnFunc(ctx, cycleID, submittedByID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) int64); ok {
		r0 = returnFunc(ctx, cycleID, submittedByID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, cycleID, submittedByID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateCourseCycleCloseRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCourseCycleCloseRequest'
type MockRepository_CreateCourseCycleCloseRequest_Call struct {
	*mock.Call
}

// CreateCourseCycleCloseRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - cycleID int64
//   - submittedByID int64
func (_e *MockRepository_Expecter) CreateCourseCycleCloseRequest(ctx interface{}, cycleID interface{}, submittedByID interface{}) *MockRepository_CreateCourseCycleCloseRequest_Call {
	return &MockRepository_CreateCourseCycleCloseRequest_Call{Call: _e.mock.On("CreateCourseCycleCloseRequest", ctx, cycleID, submittedByID)}
}

func (_c *MockRepository_CreateCourseCycleCloseRequest_Call) Run(run func(ctx context.Context, cycleID int64, submittedByID int64)) *MockRepository_CreateCourseCycleCloseRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_CreateCourseCycleCloseRequest_Call) Return(n int64, err error) *MockRepository_CreateCourseCycleCloseRequest_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_CreateCourseCycleCloseRequest_Call) RunAndReturn(run func(ctx context.Context, cycleID int64, submittedByID int64) (int64, error)) *MockRepository_CreateCourseCycleCloseRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetCourseCycleCloseRequestByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetCourseCycleCloseRequestByID(ctx context.Context, id string) (entities.CourseCycleCloseRequest, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCourseCycleCloseRequestByID")
	}

	var r0 entities.CourseCycleCloseRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entities.CourseCycleCloseRequest, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entities.CourseCycleCloseRequest); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.CourseCycleCloseRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetCourseCycleCloseRequestByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCourseCycleCloseRequestByID'
type MockRepository_GetCourseCycleCloseRequestByID_Call struct {
	*mock.Call
}

// GetCourseCycleCloseRequestByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) GetCourseCycleCloseRequestByID(ctx interface{}, id interface{}) *MockRepository_GetCourseCycleCloseRequestByID_Call {
	return &MockRepository_GetCourseCycleCloseRequestByID_Call{Call: _e.mock.On("GetCourseCycleCloseRequestByID", ctx, id)}
}

func (_c *MockRepository_GetCourseCycleCloseRequestByID_Call) Run(run func(ctx context.Context, id string)) *MockRepository_GetCourseCycleCloseRequestByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetCourseCycleCloseRequestByID_Call) Return(courseCycleCloseRequest entities.CourseCycleCloseRequest, err error) *MockRepository_GetCourseCycleCloseRequestByID_Call {
	_c.Call.Return(courseCycleCloseRequest, err)
	return _c
}

func (_c *MockRepository_GetCourseCycleCloseRequestByID_Call) RunAndReturn(run func(ctx context.Context, id string) (entities.CourseCycleCloseRequest, error)) *MockRepository_GetCourseCycleCloseRequestByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCourseCycleCloseRequests provides a mock function for the type MockRepository
func (_mock *MockRepository) GetCourseCycleCloseRequests(ctx context.Context, faculty entities.Faculty, pageScope entities.PageScope) ([]entities.CourseCycleCloseRequest, entities.PageScope, error) {
	ret := _mock.Called(ctx, faculty, pageScope)

	if len(ret) == 0 {
		panic("no return value specified for GetCourseCycleCloseRequests")
	}

	var r0 []entities.CourseCycleCloseRequest
	var r1 entities.PageScope
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Faculty, entities.PageScope) ([]entities.CourseCycleCloseRequest, entities.PageScope, error)); ok {
		return returnFunc(ctx, faculty, pageScope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Faculty, entities.PageScope) []entities.CourseCycleCloseRequest); ok {
		r0 = returnFunc(ctx, faculty, pageScope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.CourseCycleCloseRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Faculty, entities.PageScope) entities.PageScope); ok {
		r1 = returnFunc(ctx, faculty, pageScope)
	} else {
		r1 = ret.Get(1).(entities.PageScope)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, entities.Faculty, entities.PageScope) error); ok {
		r2 = returnFunc(ctx, faculty, pageScope)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_GetCourseCycleCloseRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCourseCycleCloseRequests'
type MockRepository_GetCourseCycleCloseRequests_Call struct {
	*mock.Call
}

// GetCourseCycleCloseRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - faculty entities.Faculty
//   - pageScope entities.PageScope
func (_e *MockRepository_Expecter) GetCourseCycleCloseRequests(ctx interface{}, faculty interface{}, pageScope interface{}) *MockRepository_GetCourseCycleCloseRequests_Call {
	return &MockRepository_GetCourseCycleCloseRequests_Call{Call: _e.mock.On("GetCourseCycleCloseRequests", ctx, faculty, pageScope)}
}

func (_c *MockRepository_GetCourseCycleCloseRequests_Call) Run(run func(ctx context.Context, faculty entities.Faculty, pageScope entities.PageScope)) *MockRepository_GetCourseCycleCloseRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Faculty
		if args[1] != nil {
			arg1 = args[1].(entities.Faculty)
		}
		var arg2 entities.PageScope
		if args[2] != nil {
			arg2 = args[2].(entities.PageScope)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_GetCourseCycleCloseRequests_Call) Return(courseCycleCloseRequests []entities.CourseCycleCloseRequest, pageScope1 entities.PageScope, err error) *MockRepository_GetCourseCycleCloseRequests_Call {
	_c.Call.Return(courseCycleCloseRequests, pageScope1, err)
	return _c
}

func (_c *MockRepository_GetCourseCycleCloseRequests_Call) RunAndReturn(run func(ctx context.Context, faculty entities.Faculty, pageScope entities.PageScope) ([]entities.CourseCycleCloseRequest, entities.PageScope, error)) *MockRepository_GetCourseCycleCloseRequests_Call {
	_c.Call.Return(run)
	return _c
}

// HasPendingCloseRequestForCycle provides a mock function for the type MockRepository
func (_mock *MockRepository) HasPendingCloseRequestForCycle(ctx context.Context, cycleID int64) (bool, error) {
	ret := _mock.Called(ctx, cycleID)

	if len(ret) == 0 {
		panic("no return value specified for HasPendingCloseRequestForCycle")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return returnFunc(ctx, cycleID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = returnFunc(ctx, cycleID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, cycleID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_HasPendingCloseRequestForCycle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasPendingCloseRequestForCycle'
type MockRepository_HasPendingCloseRequestForCycle_Call struct {
	*mock.Call
}

// HasPendingCloseRequestForCycle is a helper method to define mock.On call
//   - ctx context.Context
//   - cycleID int64
func (_e *MockRepository_Expecter) HasPendingCloseRequestForCycle(ctx interface{}, cycleID interface{}) *MockRepository_HasPendingCloseRequestForCycle_Call {
	return &MockRepository_HasPendingCloseRequestForCycle_Call{Call: _e.mock.On("HasPendingCloseRequestForCycle", ctx, cycleID)}
}

func (_c *MockRepository_HasPendingCloseRequestForCycle_Call) Run(run func(ctx context.Context, cycleID int64)) *MockRepository_HasPendingCloseRequestForCycle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_HasPendingCloseRequestForCycle_Call) Return(b bool, err error) *MockRepository_HasPendingCloseRequestForCycle_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_HasPendingCloseRequestForCycle_Call) RunAndReturn(run func(ctx context.Context, cycleID int64) (bool, error)) *MockRepository_HasPendingCloseRequestForCycle_Call {
	_c.Call.Return(run)
	return _c
}

// RejectCourseCycleCloseRequest provides a mock function for the type MockRepository
func (_mock *MockRepository) RejectCourseCycleCloseRequest(ctx context.Context, id string, reviewerID string, comments string, cycleID string) error {
	ret := _mock.Called(ctx, id, reviewerID, comments, cycleID)

	if len(ret) == 0 {
		panic("no return value specified for RejectCourseCycleCloseRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, id, reviewerID, comments, cycleID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RejectCourseCycleCloseRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectCourseCycleCloseRequest'
type MockRepository_RejectCourseCycleCloseRequest_Call struct {
	*mock.Call
}

// RejectCourseCycleCloseRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reviewerID string
//   - comments string
//   - cycleID string
func (_e *MockRepository_Expecter) RejectCourseCycleCloseRequest(ctx interface{}, id interface{}, reviewerID interface{}, comments interface{}, cycleID interface{}) *MockRepository_RejectCourseCycleCloseRequest_Call {
	return &MockRepository_RejectCourseCycleCloseRequest_Call{Call: _e.mock.On("RejectCourseCycleCloseRequest", ctx, id, reviewerID, comments, cycleID)}
}

func (_c *MockRepository_RejectCourseCycleCloseRequest_Call) Run(run func(ctx context.Context, id string, reviewerID string, comments string, cycleID string)) *MockRepository_RejectCourseCycleCloseRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepository_RejectCourseCycleCloseRequest_Call) Return(err error) *MockRepository_RejectCourseCycleCloseRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RejectCourseCycleCloseRequest_Call) RunAndReturn(run func(ctx context.Context, id string, reviewerID string, comments string, cycleID string) error) *MockRepository_RejectCourseCycleCloseRequest_Call {
	_c.Call.Return(run)
	return _c
}

// SaveFilesToDB provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveFilesToDB(ctx context.Context, files []*entities.File) error {
	ret := _mock.Called(ctx, files)

	if len(ret) == 0 {
		panic("no return value specified for SaveFilesToDB")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*entities.File) error); ok {
		r0 = returnFunc(ctx, files)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveFilesToDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFilesToDB'
type MockRepository_SaveFilesToDB_Call struct {
	*mock.Call
}

// SaveFilesToDB is a helper method to define mock.On call
//   - ctx context.Context
//   - files []*entities.File
func (_e *MockRepository_Expecter) SaveFilesToDB(ctx interface{}, files interface{}) *MockRepository_SaveFilesToDB_Call {
	return &MockRepository_SaveFilesToDB_Call{Call: _e.mock.On("SaveFilesToDB", ctx, files)}
}

func (_c *MockRepository_SaveFilesToDB_Call) Run(run func(ctx context.Context, files []*entities.File)) *MockRepository_SaveFilesToDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*entities.File
		if args[1] != nil {
			arg1 = args[1].([]*entities.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SaveFilesToDB_Call) Return(err error) *MockRepository_SaveFilesToDB_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveFilesToDB_Call) RunAndReturn(run func(ctx context.Context, files []*entities.File) error) *MockRepository_SaveFilesToDB_Call {
	_c.Call.Return(run)
	return _c
}
