// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/eaguilar88/deu/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// ApproveCloseRequest provides a mock function for the type MockService
func (_mock *MockService) ApproveCloseRequest(ctx context.Context, id string, reviewerID string) error {
	ret := _mock.Called(ctx, id, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for ApproveCloseRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, reviewerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_ApproveCloseRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveCloseRequest'
type MockService_ApproveCloseRequest_Call struct {
	*mock.Call
}

// ApproveCloseRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reviewerID string
func (_e *MockService_Expecter) ApproveCloseRequest(ctx interface{}, id interface{}, reviewerID interface{}) *MockService_ApproveCloseRequest_Call {
	return &MockService_ApproveCloseRequest_Call{Call: _e.mock.On("ApproveCloseRequest", ctx, id, reviewerID)}
}

func (_c *MockService_ApproveCloseRequest_Call) Run(run func(ctx context.Context, id string, reviewerID string)) *MockService_ApproveCloseRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_ApproveCloseRequest_Call) Return(err error) *MockService_ApproveCloseRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_ApproveCloseRequest_Call) RunAndReturn(run func(ctx context.Context, id string, reviewerID string) error) *MockService_ApproveCloseRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetCloseRequestByID provides a mock function for the type MockService
func (_mock *MockService) GetCloseRequestByID(ctx context.Context, id string) (entities.CourseCycleCloseRequest, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCloseRequestByID")
	}

	var r0 entities.CourseCycleCloseRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entities.CourseCycleCloseRequest, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entities.CourseCycleCloseRequest); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.CourseCycleCloseRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetCloseRequestByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCloseRequestByID'
type MockService_GetCloseRequestByID_Call struct {
	*mock.Call
}

// GetCloseRequestByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) GetCloseRequestByID(ctx interface{}, id interface{}) *MockService_GetCloseRequestByID_Call {
	return &MockService_GetCloseRequestByID_Call{Call: _e.mock.On("GetCloseRequestByID", ctx, id)}
}

func (_c *MockService_GetCloseRequestByID_Call) Run(run func(ctx context.Context, id string)) *MockService_GetCloseRequestByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetCloseRequestByID_Call) Return(courseCycleCloseRequest entities.CourseCycleCloseRequest, err error) *MockService_GetCloseRequestByID_Call {
	_c.Call.Return(courseCycleCloseRequest, err)
	return _c
}

func (_c *MockService_GetCloseRequestByID_Call) RunAndReturn(run func(ctx context.Context, id string) (entities.CourseCycleCloseRequest, error)) *MockService_GetCloseRequestByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCloseRequests provides a mock function for the type MockService
func (_mock *MockService) GetCloseRequests(ctx context.Context, faculty entities.Faculty, pageScope entities.PageScope) ([]entities.CourseCycleCloseRequest, entities.PageScope, error) {
	ret := _mock.Called(ctx, faculty, pageScope)

	if len(ret) == 0 {
		panic("no return value specified for GetCloseRequests")
	}

	var r0 []entities.CourseCycleCloseRequest
	var r1 entities.PageScope
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Faculty, entities.PageScope) ([]entities.CourseCycleCloseRequest, entities.PageScope, error)); ok {
		return returnFunc(ctx, faculty, pageScope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Faculty, entities.PageScope) []entities.CourseCycleCloseRequest); ok {
		r0 = returnFunc(ctx, faculty, pageScope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.CourseCycleCloseRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Faculty, entities.PageScope) entities.PageScope); ok {
		r1 = returnFunc(ctx, faculty, pageScope)
	} else {
		r1 = ret.Get(1).(entities.PageScope)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, entities.Faculty, entities.PageScope) error); ok {
		r2 = returnFunc(ctx, faculty, pageScope)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_GetCloseRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCloseRequests'
type MockService_GetCloseRequests_Call struct {
	*mock.Call
}

// GetCloseRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - faculty entities.Faculty
//   - pageScope entities.PageScope
func (_e *MockService_Expecter) GetCloseRequests(ctx interface{}, faculty interface{}, pageScope interface{}) *MockService_GetCloseRequests_Call {
	return &MockService_GetCloseRequests_Call{Call: _e.mock.On("GetCloseRequests", ctx, faculty, pageScope)}
}

func (_c *MockService_GetCloseRequests_Call) Run(run func(ctx context.Context, faculty entities.Faculty, pageScope entities.PageScope)) *MockService_GetCloseRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Faculty
		if args[1] != nil {
			arg1 = args[1].(entities.Faculty)
		}
		var arg2 entities.PageScope
		if args[2] != nil {
			arg2 = args[2].(entities.PageScope)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_GetCloseRequests_Call) Return(courseCycleCloseRequests []entities.CourseCycleCloseRequest, pageScope1 entities.PageScope, err error) *MockService_GetCloseRequests_Call {
	_c.Call.Return(courseCycleCloseRequests, pageScope1, err)
	return _c
}

func (_c *MockService_GetCloseRequests_Call) RunAndReturn(run func(ctx context.Context, faculty entities.Faculty, pageScope entities.PageScope) ([]entities.CourseCycleCloseRequest, entities.PageScope, error)) *MockService_GetCloseRequests_Call {
	_c.Call.Return(run)
	return _c
}

// RejectCloseRequest provides a mock function for the type MockService
func (_mock *MockService) RejectCloseRequest(ctx context.Context, id string, reviewerID string, comments string) error {
	ret := _mock.Called(ctx, id, reviewerID, comments)

	if len(ret) == 0 {
		panic("no return value specified for RejectCloseRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, id, reviewerID, comments)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RejectCloseRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectCloseRequest'
type MockService_RejectCloseRequest_Call struct {
	*mock.Call
}

// RejectCloseRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reviewerID string
//   - comments string
func (_e *MockService_Expecter) RejectCloseRequest(ctx interface{}, id interface{}, reviewerID interface{}, comments interface{}) *MockService_RejectCloseRequest_Call {
	return &MockService_RejectCloseRequest_Call{Call: _e.mock.On("RejectCloseRequest", ctx, id, reviewerID, comments)}
}

func (_c *MockService_RejectCloseRequest_Call) Run(run func(ctx context.Context, id string, reviewerID string, comments string)) *MockService_RejectCloseRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_RejectCloseRequest_Call) Return(err error) *MockService_RejectCloseRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RejectCloseRequest_Call) RunAndReturn(run func(ctx context.Context, id string, reviewerID string, comments string) error) *MockService_RejectCloseRequest_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitCloseRequest provides a mock function for the type MockService
func (_mock *MockService) SubmitCloseRequest(ctx context.Context, cycleID int64, submittedByID string) (int64, error) {
	ret := _mock.Called(ctx, cycleID, submittedByID)

	if len(ret) == 0 {
		panic("no return value specified for SubmitCloseRequest")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (int64, error)); ok {
		return returnFunc(ctx, cycleID, submittedByID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) int64); ok {
		r0 = returnFunc(ctx, cycleID, submittedByID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, cycleID, submittedByID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_SubmitCloseRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitCloseRequest'
type MockService_SubmitCloseRequest_Call struct {
	*mock.Call
}

// SubmitCloseRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - cycleID int64
//   - submittedByID string
func (_e *MockService_Expecter) SubmitCloseRequest(ctx interface{}, cycleID interface{}, submittedByID interface{}) *MockService_SubmitCloseRequest_Call {
	return &MockService_SubmitCloseRequest_Call{Call: _e.mock.On("SubmitCloseRequest", ctx, cycleID, submittedByID)}
}

func (_c *MockService_SubmitCloseRequest_Call) Run(run func(ctx context.Context, cycleID int64, submittedByID string)) *MockService_SubmitCloseRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_SubmitCloseRequest_Call) Return(n int64, err error) *MockService_SubmitCloseRequest_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockService_SubmitCloseRequest_Call) RunAndReturn(run func(ctx context.Context, cycleID int64, submittedByID string) (int64, error)) *MockService_SubmitCloseRequest_Call {
	_c.Call.Return(run)
	return _c
}
