// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// newMocksqlizer creates a new instance of mocksqlizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocksqlizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocksqlizer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mocksqlizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mocksqlizer is an autogenerated mock type for the sqlizer type
type mocksqlizer struct {
	mock.Mock
}

type mocksqlizer_Expecter struct {
	mock *mock.Mock
}

func (_m *mocksqlizer) EXPECT() *mocksqlizer_Expecter {
	return &mocksqlizer_Expecter{mock: &_m.Mock}
}

// ToSql provides a mock function for the type mocksqlizer
func (_mock *mocksqlizer) ToSql() (string, []any, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToSql")
	}

	var r0 string
	var r1 []any
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (string, []any, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() []any); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]any)
		}
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mocksqlizer_ToSql_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToSql'
type mocksqlizer_ToSql_Call struct {
	*mock.Call
}

// ToSql is a helper method to define mock.On call
func (_e *mocksqlizer_Expecter) ToSql() *mocksqlizer_ToSql_Call {
	return &mocksqlizer_ToSql_Call{Call: _e.mock.On("ToSql")}
}

func (_c *mocksqlizer_ToSql_Call) Run(run func()) *mocksqlizer_ToSql_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mocksqlizer_ToSql_Call) Return(s string, anyMoqParams []any, err error) *mocksqlizer_ToSql_Call {
	_c.Call.Return(s, anyMoqParams, err)
	return _c
}

func (_c *mocksqlizer_ToSql_Call) RunAndReturn(run func() (string, []any, error)) *mocksqlizer_ToSql_Call {
	_c.Call.Return(run)
	return _c
}
