// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/eaguilar88/deu/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// ServiceMock is an autogenerated mock type for the Service type
type ServiceMock struct {
	mock.Mock
}

type ServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceMock) EXPECT() *ServiceMock_Expecter {
	return &ServiceMock_Expecter{mock: &_m.Mock}
}

// ApproveCourseRequest provides a mock function with given fields: ctx, cr, courseType
func (_m *ServiceMock) ApproveCourseRequest(ctx context.Context, cr entities.CourseRequest, courseType entities.CourseType) error {
	ret := _m.Called(ctx, cr, courseType)

	if len(ret) == 0 {
		panic("no return value specified for ApproveCourseRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.CourseRequest, entities.CourseType) error); ok {
		r0 = rf(ctx, cr, courseType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServiceMock_ApproveCourseRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveCourseRequest'
type ServiceMock_ApproveCourseRequest_Call struct {
	*mock.Call
}

// ApproveCourseRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - cr entities.CourseRequest
//   - courseType entities.CourseType
func (_e *ServiceMock_Expecter) ApproveCourseRequest(ctx interface{}, cr interface{}, courseType interface{}) *ServiceMock_ApproveCourseRequest_Call {
	return &ServiceMock_ApproveCourseRequest_Call{Call: _e.mock.On("ApproveCourseRequest", ctx, cr, courseType)}
}

func (_c *ServiceMock_ApproveCourseRequest_Call) Run(run func(ctx context.Context, cr entities.CourseRequest, courseType entities.CourseType)) *ServiceMock_ApproveCourseRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.CourseRequest), args[2].(entities.CourseType))
	})
	return _c
}

func (_c *ServiceMock_ApproveCourseRequest_Call) Return(_a0 error) *ServiceMock_ApproveCourseRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceMock_ApproveCourseRequest_Call) RunAndReturn(run func(context.Context, entities.CourseRequest, entities.CourseType) error) *ServiceMock_ApproveCourseRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetCourseRequestByID provides a mock function with given fields: ctx, reqID
func (_m *ServiceMock) GetCourseRequestByID(ctx context.Context, reqID string) (entities.CourseRequest, error) {
	ret := _m.Called(ctx, reqID)

	if len(ret) == 0 {
		panic("no return value specified for GetCourseRequestByID")
	}

	var r0 entities.CourseRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.CourseRequest, error)); ok {
		return rf(ctx, reqID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.CourseRequest); ok {
		r0 = rf(ctx, reqID)
	} else {
		r0 = ret.Get(0).(entities.CourseRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, reqID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceMock_GetCourseRequestByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCourseRequestByID'
type ServiceMock_GetCourseRequestByID_Call struct {
	*mock.Call
}

// GetCourseRequestByID is a helper method to define mock.On call
//   - ctx context.Context
//   - reqID string
func (_e *ServiceMock_Expecter) GetCourseRequestByID(ctx interface{}, reqID interface{}) *ServiceMock_GetCourseRequestByID_Call {
	return &ServiceMock_GetCourseRequestByID_Call{Call: _e.mock.On("GetCourseRequestByID", ctx, reqID)}
}

func (_c *ServiceMock_GetCourseRequestByID_Call) Run(run func(ctx context.Context, reqID string)) *ServiceMock_GetCourseRequestByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ServiceMock_GetCourseRequestByID_Call) Return(_a0 entities.CourseRequest, _a1 error) *ServiceMock_GetCourseRequestByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceMock_GetCourseRequestByID_Call) RunAndReturn(run func(context.Context, string) (entities.CourseRequest, error)) *ServiceMock_GetCourseRequestByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCourseRequestsByFaculty provides a mock function with given fields: ctx, faculty, pageScope
func (_m *ServiceMock) GetCourseRequestsByFaculty(ctx context.Context, faculty entities.Faculty, pageScope entities.PageScope) ([]entities.CourseRequest, entities.PageScope, error) {
	ret := _m.Called(ctx, faculty, pageScope)

	if len(ret) == 0 {
		panic("no return value specified for GetCourseRequestsByFaculty")
	}

	var r0 []entities.CourseRequest
	var r1 entities.PageScope
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Faculty, entities.PageScope) ([]entities.CourseRequest, entities.PageScope, error)); ok {
		return rf(ctx, faculty, pageScope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.Faculty, entities.PageScope) []entities.CourseRequest); ok {
		r0 = rf(ctx, faculty, pageScope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.CourseRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.Faculty, entities.PageScope) entities.PageScope); ok {
		r1 = rf(ctx, faculty, pageScope)
	} else {
		r1 = ret.Get(1).(entities.PageScope)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entities.Faculty, entities.PageScope) error); ok {
		r2 = rf(ctx, faculty, pageScope)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ServiceMock_GetCourseRequestsByFaculty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCourseRequestsByFaculty'
type ServiceMock_GetCourseRequestsByFaculty_Call struct {
	*mock.Call
}

// GetCourseRequestsByFaculty is a helper method to define mock.On call
//   - ctx context.Context
//   - faculty entities.Faculty
//   - pageScope entities.PageScope
func (_e *ServiceMock_Expecter) GetCourseRequestsByFaculty(ctx interface{}, faculty interface{}, pageScope interface{}) *ServiceMock_GetCourseRequestsByFaculty_Call {
	return &ServiceMock_GetCourseRequestsByFaculty_Call{Call: _e.mock.On("GetCourseRequestsByFaculty", ctx, faculty, pageScope)}
}

func (_c *ServiceMock_GetCourseRequestsByFaculty_Call) Run(run func(ctx context.Context, faculty entities.Faculty, pageScope entities.PageScope)) *ServiceMock_GetCourseRequestsByFaculty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.Faculty), args[2].(entities.PageScope))
	})
	return _c
}

func (_c *ServiceMock_GetCourseRequestsByFaculty_Call) Return(_a0 []entities.CourseRequest, _a1 entities.PageScope, _a2 error) *ServiceMock_GetCourseRequestsByFaculty_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ServiceMock_GetCourseRequestsByFaculty_Call) RunAndReturn(run func(context.Context, entities.Faculty, entities.PageScope) ([]entities.CourseRequest, entities.PageScope, error)) *ServiceMock_GetCourseRequestsByFaculty_Call {
	_c.Call.Return(run)
	return _c
}

// RedirectCourseRequest provides a mock function with given fields: ctx, reqID, reviewerID, faculty, reason
func (_m *ServiceMock) RedirectCourseRequest(ctx context.Context, reqID string, reviewerID string, faculty entities.Faculty, reason string) error {
	ret := _m.Called(ctx, reqID, reviewerID, faculty, reason)

	if len(ret) == 0 {
		panic("no return value specified for RedirectCourseRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, entities.Faculty, string) error); ok {
		r0 = rf(ctx, reqID, reviewerID, faculty, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServiceMock_RedirectCourseRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RedirectCourseRequest'
type ServiceMock_RedirectCourseRequest_Call struct {
	*mock.Call
}

// RedirectCourseRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - reqID string
//   - reviewerID string
//   - faculty entities.Faculty
//   - reason string
func (_e *ServiceMock_Expecter) RedirectCourseRequest(ctx interface{}, reqID interface{}, reviewerID interface{}, faculty interface{}, reason interface{}) *ServiceMock_RedirectCourseRequest_Call {
	return &ServiceMock_RedirectCourseRequest_Call{Call: _e.mock.On("RedirectCourseRequest", ctx, reqID, reviewerID, faculty, reason)}
}

func (_c *ServiceMock_RedirectCourseRequest_Call) Run(run func(ctx context.Context, reqID string, reviewerID string, faculty entities.Faculty, reason string)) *ServiceMock_RedirectCourseRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(entities.Faculty), args[4].(string))
	})
	return _c
}

func (_c *ServiceMock_RedirectCourseRequest_Call) Return(_a0 error) *ServiceMock_RedirectCourseRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceMock_RedirectCourseRequest_Call) RunAndReturn(run func(context.Context, string, string, entities.Faculty, string) error) *ServiceMock_RedirectCourseRequest_Call {
	_c.Call.Return(run)
	return _c
}

// RejectCourseRequest provides a mock function with given fields: ctx, reqID, reviewerID, comments
func (_m *ServiceMock) RejectCourseRequest(ctx context.Context, reqID string, reviewerID string, comments string) error {
	ret := _m.Called(ctx, reqID, reviewerID, comments)

	if len(ret) == 0 {
		panic("no return value specified for RejectCourseRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, reqID, reviewerID, comments)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServiceMock_RejectCourseRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectCourseRequest'
type ServiceMock_RejectCourseRequest_Call struct {
	*mock.Call
}

// RejectCourseRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - reqID string
//   - reviewerID string
//   - comments string
func (_e *ServiceMock_Expecter) RejectCourseRequest(ctx interface{}, reqID interface{}, reviewerID interface{}, comments interface{}) *ServiceMock_RejectCourseRequest_Call {
	return &ServiceMock_RejectCourseRequest_Call{Call: _e.mock.On("RejectCourseRequest", ctx, reqID, reviewerID, comments)}
}

func (_c *ServiceMock_RejectCourseRequest_Call) Run(run func(ctx context.Context, reqID string, reviewerID string, comments string)) *ServiceMock_RejectCourseRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ServiceMock_RejectCourseRequest_Call) Return(_a0 error) *ServiceMock_RejectCourseRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceMock_RejectCourseRequest_Call) RunAndReturn(run func(context.Context, string, string, string) error) *ServiceMock_RejectCourseRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewServiceMock creates a new instance of ServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceMock {
	mock := &ServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
