// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// RegisterAdminEndpointsMock is an autogenerated mock type for the RegisterAdminEndpoints type
type RegisterAdminEndpointsMock struct {
	mock.Mock
}

type RegisterAdminEndpointsMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RegisterAdminEndpointsMock) EXPECT() *RegisterAdminEndpointsMock_Expecter {
	return &RegisterAdminEndpointsMock_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: g
func (_m *RegisterAdminEndpointsMock) Execute(g *echo.Group) {
	_m.Called(g)
}

// RegisterAdminEndpointsMock_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type RegisterAdminEndpointsMock_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - g *echo.Group
func (_e *RegisterAdminEndpointsMock_Expecter) Execute(g interface{}) *RegisterAdminEndpointsMock_Execute_Call {
	return &RegisterAdminEndpointsMock_Execute_Call{Call: _e.mock.On("Execute", g)}
}

func (_c *RegisterAdminEndpointsMock_Execute_Call) Run(run func(g *echo.Group)) *RegisterAdminEndpointsMock_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*echo.Group))
	})
	return _c
}

func (_c *RegisterAdminEndpointsMock_Execute_Call) Return() *RegisterAdminEndpointsMock_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *RegisterAdminEndpointsMock_Execute_Call) RunAndReturn(run func(*echo.Group)) *RegisterAdminEndpointsMock_Execute_Call {
	_c.Run(run)
	return _c
}

// NewRegisterAdminEndpointsMock creates a new instance of RegisterAdminEndpointsMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegisterAdminEndpointsMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegisterAdminEndpointsMock {
	mock := &RegisterAdminEndpointsMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
