openapi: 3.0.0
info:
  title: DEU UCV API
  description: API del proyecto DEU UCV
  version: 1.0.0
paths:
  /health:
    get:
      summary: Foo
      responses:
        200:
          description: "Documentation"