FROM ruby:3.1.2-alpine AS builder

RUN apk add --no-cache build-base postgresql-dev nodejs npm tzdata git curl

WORKDIR /rails

COPY Gemfile Gemfile.lock ./
ENV BUNDLE_WITHOUT="development:test"
RUN bundle install

COPY package*.json ./
RUN npm install

COPY . .

ENV RAILS_ENV=production SECRET_KEY_BASE=placeholder
RUN bundle exec vite build
RUN bundle exec rake assets:precompile

FROM ruby:3.1.2-alpine

RUN apk add --no-cache postgresql-client tzdata curl

ENV RAILS_ENV=production

WORKDIR /rails

COPY --from=builder /usr/local/bundle /usr/local/bundle
COPY --from=builder /rails /rails

EXPOSE 3000
CMD ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]
