# Stage 1: Build the Vue.js app
FROM node:24.3.0-alpine3.22 AS builder

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Serve the app with a production-ready server
FROM nginx:alpine 

# Copy the build output to the Nginx html directory
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]