// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SignerMock is an autogenerated mock type for the Signer type
type SignerMock struct {
	mock.Mock
}

type SignerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SignerMock) EXPECT() *SignerMock_Expecter {
	return &SignerMock_Expecter{mock: &_m.Mock}
}

// GenerateJWT provides a mock function with given fields: userID, roles
func (_m *SignerMock) GenerateJWT(userID string, roles []string) (string, error) {
	ret := _m.Called(userID, roles)

	if len(ret) == 0 {
		panic("no return value specified for GenerateJWT")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []string) (string, error)); ok {
		return rf(userID, roles)
	}
	if rf, ok := ret.Get(0).(func(string, []string) string); ok {
		r0 = rf(userID, roles)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = rf(userID, roles)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignerMock_GenerateJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateJWT'
type SignerMock_GenerateJWT_Call struct {
	*mock.Call
}

// GenerateJWT is a helper method to define mock.On call
//   - userID string
//   - roles []string
func (_e *SignerMock_Expecter) GenerateJWT(userID interface{}, roles interface{}) *SignerMock_GenerateJWT_Call {
	return &SignerMock_GenerateJWT_Call{Call: _e.mock.On("GenerateJWT", userID, roles)}
}

func (_c *SignerMock_GenerateJWT_Call) Run(run func(userID string, roles []string)) *SignerMock_GenerateJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]string))
	})
	return _c
}

func (_c *SignerMock_GenerateJWT_Call) Return(_a0 string, _a1 error) *SignerMock_GenerateJWT_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SignerMock_GenerateJWT_Call) RunAndReturn(run func(string, []string) (string, error)) *SignerMock_GenerateJWT_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: tokenString
func (_m *SignerMock) ValidateToken(tokenString string) error {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(tokenString)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SignerMock_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type SignerMock_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - tokenString string
func (_e *SignerMock_Expecter) ValidateToken(tokenString interface{}) *SignerMock_ValidateToken_Call {
	return &SignerMock_ValidateToken_Call{Call: _e.mock.On("ValidateToken", tokenString)}
}

func (_c *SignerMock_ValidateToken_Call) Run(run func(tokenString string)) *SignerMock_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *SignerMock_ValidateToken_Call) Return(_a0 error) *SignerMock_ValidateToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SignerMock_ValidateToken_Call) RunAndReturn(run func(string) error) *SignerMock_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewSignerMock creates a new instance of SignerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSignerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SignerMock {
	mock := &SignerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
