// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/eaguilar88/deu/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CountActivities provides a mock function for the type MockRepository
func (_mock *MockRepository) CountActivities(ctx context.Context, filter entities.ActivityFilter) (int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for CountActivities")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.ActivityFilter) (int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.ActivityFilter) int); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.ActivityFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CountActivities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountActivities'
type MockRepository_CountActivities_Call struct {
	*mock.Call
}

// CountActivities is a helper method to define mock.On call
//   - ctx context.Context
//   - filter entities.ActivityFilter
func (_e *MockRepository_Expecter) CountActivities(ctx interface{}, filter interface{}) *MockRepository_CountActivities_Call {
	return &MockRepository_CountActivities_Call{Call: _e.mock.On("CountActivities", ctx, filter)}
}

func (_c *MockRepository_CountActivities_Call) Run(run func(ctx context.Context, filter entities.ActivityFilter)) *MockRepository_CountActivities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.ActivityFilter
		if args[1] != nil {
			arg1 = args[1].(entities.ActivityFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CountActivities_Call) Return(n int, err error) *MockRepository_CountActivities_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_CountActivities_Call) RunAndReturn(run func(ctx context.Context, filter entities.ActivityFilter) (int, error)) *MockRepository_CountActivities_Call {
	_c.Call.Return(run)
	return _c
}

// CreateActivity provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateActivity(ctx context.Context, activity entities.Activity) (int64, error) {
	ret := _mock.Called(ctx, activity)

	if len(ret) == 0 {
		panic("no return value specified for CreateActivity")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Activity) (int64, error)); ok {
		return returnFunc(ctx, activity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Activity) int64); ok {
		r0 = returnFunc(ctx, activity)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Activity) error); ok {
		r1 = returnFunc(ctx, activity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateActivity'
type MockRepository_CreateActivity_Call struct {
	*mock.Call
}

// CreateActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - activity entities.Activity
func (_e *MockRepository_Expecter) CreateActivity(ctx interface{}, activity interface{}) *MockRepository_CreateActivity_Call {
	return &MockRepository_CreateActivity_Call{Call: _e.mock.On("CreateActivity", ctx, activity)}
}

func (_c *MockRepository_CreateActivity_Call) Run(run func(ctx context.Context, activity entities.Activity)) *MockRepository_CreateActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Activity
		if args[1] != nil {
			arg1 = args[1].(entities.Activity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateActivity_Call) Return(n int64, err error) *MockRepository_CreateActivity_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_CreateActivity_Call) RunAndReturn(run func(ctx context.Context, activity entities.Activity) (int64, error)) *MockRepository_CreateActivity_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteActivity provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteActivity(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteActivity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteActivity'
type MockRepository_DeleteActivity_Call struct {
	*mock.Call
}

// DeleteActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) DeleteActivity(ctx interface{}, id interface{}) *MockRepository_DeleteActivity_Call {
	return &MockRepository_DeleteActivity_Call{Call: _e.mock.On("DeleteActivity", ctx, id)}
}

func (_c *MockRepository_DeleteActivity_Call) Run(run func(ctx context.Context, id string)) *MockRepository_DeleteActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteActivity_Call) Return(err error) *MockRepository_DeleteActivity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteActivity_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockRepository_DeleteActivity_Call {
	_c.Call.Return(run)
	return _c
}

// GetActivities provides a mock function for the type MockRepository
func (_mock *MockRepository) GetActivities(ctx context.Context, filter entities.ActivityFilter, pageScope entities.PageScope) ([]entities.Activity, entities.PageScope, error) {
	ret := _mock.Called(ctx, filter, pageScope)

	if len(ret) == 0 {
		panic("no return value specified for GetActivities")
	}

	var r0 []entities.Activity
	var r1 entities.PageScope
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.ActivityFilter, entities.PageScope) ([]entities.Activity, entities.PageScope, error)); ok {
		return returnFunc(ctx, filter, pageScope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.ActivityFilter, entities.PageScope) []entities.Activity); ok {
		r0 = returnFunc(ctx, filter, pageScope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Activity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.ActivityFilter, entities.PageScope) entities.PageScope); ok {
		r1 = returnFunc(ctx, filter, pageScope)
	} else {
		r1 = ret.Get(1).(entities.PageScope)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, entities.ActivityFilter, entities.PageScope) error); ok {
		r2 = returnFunc(ctx, filter, pageScope)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_GetActivities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActivities'
type MockRepository_GetActivities_Call struct {
	*mock.Call
}

// GetActivities is a helper method to define mock.On call
//   - ctx context.Context
//   - filter entities.ActivityFilter
//   - pageScope entities.PageScope
func (_e *MockRepository_Expecter) GetActivities(ctx interface{}, filter interface{}, pageScope interface{}) *MockRepository_GetActivities_Call {
	return &MockRepository_GetActivities_Call{Call: _e.mock.On("GetActivities", ctx, filter, pageScope)}
}

func (_c *MockRepository_GetActivities_Call) Run(run func(ctx context.Context, filter entities.ActivityFilter, pageScope entities.PageScope)) *MockRepository_GetActivities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.ActivityFilter
		if args[1] != nil {
			arg1 = args[1].(entities.ActivityFilter)
		}
		var arg2 entities.PageScope
		if args[2] != nil {
			arg2 = args[2].(entities.PageScope)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_GetActivities_Call) Return(activitys []entities.Activity, pageScope1 entities.PageScope, err error) *MockRepository_GetActivities_Call {
	_c.Call.Return(activitys, pageScope1, err)
	return _c
}

func (_c *MockRepository_GetActivities_Call) RunAndReturn(run func(ctx context.Context, filter entities.ActivityFilter, pageScope entities.PageScope) ([]entities.Activity, entities.PageScope, error)) *MockRepository_GetActivities_Call {
	_c.Call.Return(run)
	return _c
}

// GetActivityByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetActivityByID(ctx context.Context, id string) (entities.Activity, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetActivityByID")
	}

	var r0 entities.Activity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entities.Activity, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entities.Activity); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.Activity)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetActivityByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActivityByID'
type MockRepository_GetActivityByID_Call struct {
	*mock.Call
}

// GetActivityByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) GetActivityByID(ctx interface{}, id interface{}) *MockRepository_GetActivityByID_Call {
	return &MockRepository_GetActivityByID_Call{Call: _e.mock.On("GetActivityByID", ctx, id)}
}

func (_c *MockRepository_GetActivityByID_Call) Run(run func(ctx context.Context, id string)) *MockRepository_GetActivityByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetActivityByID_Call) Return(activity entities.Activity, err error) *MockRepository_GetActivityByID_Call {
	_c.Call.Return(activity, err)
	return _c
}

func (_c *MockRepository_GetActivityByID_Call) RunAndReturn(run func(ctx context.Context, id string) (entities.Activity, error)) *MockRepository_GetActivityByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilesByOwner provides a mock function for the type MockRepository
func (_mock *MockRepository) GetFilesByOwner(ctx context.Context, ownerID string, ownerType entities.OwnerType) (entities.GroupedFiles, error) {
	ret := _mock.Called(ctx, ownerID, ownerType)

	if len(ret) == 0 {
		panic("no return value specified for GetFilesByOwner")
	}

	var r0 entities.GroupedFiles
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entities.OwnerType) (entities.GroupedFiles, error)); ok {
		return returnFunc(ctx, ownerID, ownerType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entities.OwnerType) entities.GroupedFiles); ok {
		r0 = returnFunc(ctx, ownerID, ownerType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.GroupedFiles)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, entities.OwnerType) error); ok {
		r1 = returnFunc(ctx, ownerID, ownerType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetFilesByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilesByOwner'
type MockRepository_GetFilesByOwner_Call struct {
	*mock.Call
}

// GetFilesByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - ownerType entities.OwnerType
func (_e *MockRepository_Expecter) GetFilesByOwner(ctx interface{}, ownerID interface{}, ownerType interface{}) *MockRepository_GetFilesByOwner_Call {
	return &MockRepository_GetFilesByOwner_Call{Call: _e.mock.On("GetFilesByOwner", ctx, ownerID, ownerType)}
}

func (_c *MockRepository_GetFilesByOwner_Call) Run(run func(ctx context.Context, ownerID string, ownerType entities.OwnerType)) *MockRepository_GetFilesByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entities.OwnerType
		if args[2] != nil {
			arg2 = args[2].(entities.OwnerType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_GetFilesByOwner_Call) Return(groupedFiles entities.GroupedFiles, err error) *MockRepository_GetFilesByOwner_Call {
	_c.Call.Return(groupedFiles, err)
	return _c
}

func (_c *MockRepository_GetFilesByOwner_Call) RunAndReturn(run func(ctx context.Context, ownerID string, ownerType entities.OwnerType) (entities.GroupedFiles, error)) *MockRepository_GetFilesByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupDashboardSummary provides a mock function for the type MockRepository
func (_mock *MockRepository) GetGroupDashboardSummary(ctx context.Context, groupID string) (entities.GroupDashboardSummary, error) {
	ret := _mock.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupDashboardSummary")
	}

	var r0 entities.GroupDashboardSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entities.GroupDashboardSummary, error)); ok {
		return returnFunc(ctx, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entities.GroupDashboardSummary); ok {
		r0 = returnFunc(ctx, groupID)
	} else {
		r0 = ret.Get(0).(entities.GroupDashboardSummary)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetGroupDashboardSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupDashboardSummary'
type MockRepository_GetGroupDashboardSummary_Call struct {
	*mock.Call
}

// GetGroupDashboardSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID string
func (_e *MockRepository_Expecter) GetGroupDashboardSummary(ctx interface{}, groupID interface{}) *MockRepository_GetGroupDashboardSummary_Call {
	return &MockRepository_GetGroupDashboardSummary_Call{Call: _e.mock.On("GetGroupDashboardSummary", ctx, groupID)}
}

func (_c *MockRepository_GetGroupDashboardSummary_Call) Run(run func(ctx context.Context, groupID string)) *MockRepository_GetGroupDashboardSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetGroupDashboardSummary_Call) Return(groupDashboardSummary entities.GroupDashboardSummary, err error) *MockRepository_GetGroupDashboardSummary_Call {
	_c.Call.Return(groupDashboardSummary, err)
	return _c
}

func (_c *MockRepository_GetGroupDashboardSummary_Call) RunAndReturn(run func(ctx context.Context, groupID string) (entities.GroupDashboardSummary, error)) *MockRepository_GetGroupDashboardSummary_Call {
	_c.Call.Return(run)
	return _c
}

// SaveFilesToDB provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveFilesToDB(ctx context.Context, files []*entities.File) error {
	ret := _mock.Called(ctx, files)

	if len(ret) == 0 {
		panic("no return value specified for SaveFilesToDB")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*entities.File) error); ok {
		r0 = returnFunc(ctx, files)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveFilesToDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFilesToDB'
type MockRepository_SaveFilesToDB_Call struct {
	*mock.Call
}

// SaveFilesToDB is a helper method to define mock.On call
//   - ctx context.Context
//   - files []*entities.File
func (_e *MockRepository_Expecter) SaveFilesToDB(ctx interface{}, files interface{}) *MockRepository_SaveFilesToDB_Call {
	return &MockRepository_SaveFilesToDB_Call{Call: _e.mock.On("SaveFilesToDB", ctx, files)}
}

func (_c *MockRepository_SaveFilesToDB_Call) Run(run func(ctx context.Context, files []*entities.File)) *MockRepository_SaveFilesToDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*entities.File
		if args[1] != nil {
			arg1 = args[1].([]*entities.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SaveFilesToDB_Call) Return(err error) *MockRepository_SaveFilesToDB_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveFilesToDB_Call) RunAndReturn(run func(ctx context.Context, files []*entities.File) error) *MockRepository_SaveFilesToDB_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateActivity provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateActivity(ctx context.Context, activity entities.Activity) error {
	ret := _mock.Called(ctx, activity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateActivity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Activity) error); ok {
		r0 = returnFunc(ctx, activity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateActivity'
type MockRepository_UpdateActivity_Call struct {
	*mock.Call
}

// UpdateActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - activity entities.Activity
func (_e *MockRepository_Expecter) UpdateActivity(ctx interface{}, activity interface{}) *MockRepository_UpdateActivity_Call {
	return &MockRepository_UpdateActivity_Call{Call: _e.mock.On("UpdateActivity", ctx, activity)}
}

func (_c *MockRepository_UpdateActivity_Call) Run(run func(ctx context.Context, activity entities.Activity)) *MockRepository_UpdateActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Activity
		if args[1] != nil {
			arg1 = args[1].(entities.Activity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateActivity_Call) Return(err error) *MockRepository_UpdateActivity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateActivity_Call) RunAndReturn(run func(ctx context.Context, activity entities.Activity) error) *MockRepository_UpdateActivity_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFeatureStatus provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateFeatureStatus(ctx context.Context, id string, featured bool) error {
	ret := _mock.Called(ctx, id, featured)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFeatureStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, id, featured)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateFeatureStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFeatureStatus'
type MockRepository_UpdateFeatureStatus_Call struct {
	*mock.Call
}

// UpdateFeatureStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - featured bool
func (_e *MockRepository_Expecter) UpdateFeatureStatus(ctx interface{}, id interface{}, featured interface{}) *MockRepository_UpdateFeatureStatus_Call {
	return &MockRepository_UpdateFeatureStatus_Call{Call: _e.mock.On("UpdateFeatureStatus", ctx, id, featured)}
}

func (_c *MockRepository_UpdateFeatureStatus_Call) Run(run func(ctx context.Context, id string, featured bool)) *MockRepository_UpdateFeatureStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateFeatureStatus_Call) Return(err error) *MockRepository_UpdateFeatureStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateFeatureStatus_Call) RunAndReturn(run func(ctx context.Context, id string, featured bool) error) *MockRepository_UpdateFeatureStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateReportCheckStatus provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateReportCheckStatus(ctx context.Context, id string, checked bool) error {
	ret := _mock.Called(ctx, id, checked)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReportCheckStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, id, checked)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateReportCheckStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReportCheckStatus'
type MockRepository_UpdateReportCheckStatus_Call struct {
	*mock.Call
}

// UpdateReportCheckStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - checked bool
func (_e *MockRepository_Expecter) UpdateReportCheckStatus(ctx interface{}, id interface{}, checked interface{}) *MockRepository_UpdateReportCheckStatus_Call {
	return &MockRepository_UpdateReportCheckStatus_Call{Call: _e.mock.On("UpdateReportCheckStatus", ctx, id, checked)}
}

func (_c *MockRepository_UpdateReportCheckStatus_Call) Run(run func(ctx context.Context, id string, checked bool)) *MockRepository_UpdateReportCheckStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateReportCheckStatus_Call) Return(err error) *MockRepository_UpdateReportCheckStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateReportCheckStatus_Call) RunAndReturn(run func(ctx context.Context, id string, checked bool) error) *MockRepository_UpdateReportCheckStatus_Call {
	_c.Call.Return(run)
	return _c
}
