// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/eaguilar88/deu/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockService
func (_mock *MockService) Login(ctx context.Context, username string, password string) (string, *entities.User, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 *entities.User
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, *entities.User, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *entities.User); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.User)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, username, password)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockService_Expecter) Login(ctx interface{}, username interface{}, password interface{}) *MockService_Login_Call {
	return &MockService_Login_Call{Call: _e.mock.On("Login", ctx, username, password)}
}

func (_c *MockService_Login_Call) Run(run func(ctx context.Context, username string, password string)) *MockService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Login_Call) Return(s string, user *entities.User, err error) *MockService_Login_Call {
	_c.Call.Return(s, user, err)
	return _c
}

func (_c *MockService_Login_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (string, *entities.User, error)) *MockService_Login_Call {
	_c.Call.Return(run)
	return _c
}
