// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CustomErrorMock is an autogenerated mock type for the CustomError type
type CustomErrorMock struct {
	mock.Mock
}

type CustomErrorMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CustomErrorMock) EXPECT() *CustomErrorMock_Expecter {
	return &CustomErrorMock_Expecter{mock: &_m.Mock}
}

// Error provides a mock function with no fields
func (_m *CustomErrorMock) Error() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// CustomErrorMock_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type CustomErrorMock_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *CustomErrorMock_Expecter) Error() *CustomErrorMock_Error_Call {
	return &CustomErrorMock_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *CustomErrorMock_Error_Call) Run(run func()) *CustomErrorMock_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CustomErrorMock_Error_Call) Return(_a0 string) *CustomErrorMock_Error_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CustomErrorMock_Error_Call) RunAndReturn(run func() string) *CustomErrorMock_Error_Call {
	_c.Call.Return(run)
	return _c
}

// StatusCode provides a mock function with no fields
func (_m *CustomErrorMock) StatusCode() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StatusCode")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// CustomErrorMock_StatusCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatusCode'
type CustomErrorMock_StatusCode_Call struct {
	*mock.Call
}

// StatusCode is a helper method to define mock.On call
func (_e *CustomErrorMock_Expecter) StatusCode() *CustomErrorMock_StatusCode_Call {
	return &CustomErrorMock_StatusCode_Call{Call: _e.mock.On("StatusCode")}
}

func (_c *CustomErrorMock_StatusCode_Call) Run(run func()) *CustomErrorMock_StatusCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CustomErrorMock_StatusCode_Call) Return(_a0 int) *CustomErrorMock_StatusCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CustomErrorMock_StatusCode_Call) RunAndReturn(run func() int) *CustomErrorMock_StatusCode_Call {
	_c.Call.Return(run)
	return _c
}

// Unwrap provides a mock function with no fields
func (_m *CustomErrorMock) Unwrap() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Unwrap")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CustomErrorMock_Unwrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unwrap'
type CustomErrorMock_Unwrap_Call struct {
	*mock.Call
}

// Unwrap is a helper method to define mock.On call
func (_e *CustomErrorMock_Expecter) Unwrap() *CustomErrorMock_Unwrap_Call {
	return &CustomErrorMock_Unwrap_Call{Call: _e.mock.On("Unwrap")}
}

func (_c *CustomErrorMock_Unwrap_Call) Run(run func()) *CustomErrorMock_Unwrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CustomErrorMock_Unwrap_Call) Return(_a0 error) *CustomErrorMock_Unwrap_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CustomErrorMock_Unwrap_Call) RunAndReturn(run func() error) *CustomErrorMock_Unwrap_Call {
	_c.Call.Return(run)
	return _c
}

// NewCustomErrorMock creates a new instance of CustomErrorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomErrorMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomErrorMock {
	mock := &CustomErrorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
