// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/eaguilar88/deu/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ApproveProviderRequest provides a mock function for the type MockRepository
func (_mock *MockRepository) ApproveProviderRequest(ctx context.Context, id string, reviewerID string, providerID int64) error {
	ret := _mock.Called(ctx, id, reviewerID, providerID)

	if len(ret) == 0 {
		panic("no return value specified for ApproveProviderRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) error); ok {
		r0 = returnFunc(ctx, id, reviewerID, providerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_ApproveProviderRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveProviderRequest'
type MockRepository_ApproveProviderRequest_Call struct {
	*mock.Call
}

// ApproveProviderRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reviewerID string
//   - providerID int64
func (_e *MockRepository_Expecter) ApproveProviderRequest(ctx interface{}, id interface{}, reviewerID interface{}, providerID interface{}) *MockRepository_ApproveProviderRequest_Call {
	return &MockRepository_ApproveProviderRequest_Call{Call: _e.mock.On("ApproveProviderRequest", ctx, id, reviewerID, providerID)}
}

func (_c *MockRepository_ApproveProviderRequest_Call) Run(run func(ctx context.Context, id string, reviewerID string, providerID int64)) *MockRepository_ApproveProviderRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_ApproveProviderRequest_Call) Return(err error) *MockRepository_ApproveProviderRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_ApproveProviderRequest_Call) RunAndReturn(run func(ctx context.Context, id string, reviewerID string, providerID int64) error) *MockRepository_ApproveProviderRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetProvider provides a mock function for the type MockRepository
func (_mock *MockRepository) GetProvider(ctx context.Context, providerID string) (entities.Provider, error) {
	ret := _mock.Called(ctx, providerID)

	if len(ret) == 0 {
		panic("no return value specified for GetProvider")
	}

	var r0 entities.Provider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entities.Provider, error)); ok {
		return returnFunc(ctx, providerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entities.Provider); ok {
		r0 = returnFunc(ctx, providerID)
	} else {
		r0 = ret.Get(0).(entities.Provider)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, providerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProvider'
type MockRepository_GetProvider_Call struct {
	*mock.Call
}

// GetProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - providerID string
func (_e *MockRepository_Expecter) GetProvider(ctx interface{}, providerID interface{}) *MockRepository_GetProvider_Call {
	return &MockRepository_GetProvider_Call{Call: _e.mock.On("GetProvider", ctx, providerID)}
}

func (_c *MockRepository_GetProvider_Call) Run(run func(ctx context.Context, providerID string)) *MockRepository_GetProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetProvider_Call) Return(provider entities.Provider, err error) *MockRepository_GetProvider_Call {
	_c.Call.Return(provider, err)
	return _c
}

func (_c *MockRepository_GetProvider_Call) RunAndReturn(run func(ctx context.Context, providerID string) (entities.Provider, error)) *MockRepository_GetProvider_Call {
	_c.Call.Return(run)
	return _c
}

// GetProviderRequestByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetProviderRequestByID(ctx context.Context, id string) (entities.ProviderRequest, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProviderRequestByID")
	}

	var r0 entities.ProviderRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entities.ProviderRequest, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entities.ProviderRequest); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.ProviderRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetProviderRequestByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProviderRequestByID'
type MockRepository_GetProviderRequestByID_Call struct {
	*mock.Call
}

// GetProviderRequestByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) GetProviderRequestByID(ctx interface{}, id interface{}) *MockRepository_GetProviderRequestByID_Call {
	return &MockRepository_GetProviderRequestByID_Call{Call: _e.mock.On("GetProviderRequestByID", ctx, id)}
}

func (_c *MockRepository_GetProviderRequestByID_Call) Run(run func(ctx context.Context, id string)) *MockRepository_GetProviderRequestByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetProviderRequestByID_Call) Return(providerRequest entities.ProviderRequest, err error) *MockRepository_GetProviderRequestByID_Call {
	_c.Call.Return(providerRequest, err)
	return _c
}

func (_c *MockRepository_GetProviderRequestByID_Call) RunAndReturn(run func(ctx context.Context, id string) (entities.ProviderRequest, error)) *MockRepository_GetProviderRequestByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetProviderRequests provides a mock function for the type MockRepository
func (_mock *MockRepository) GetProviderRequests(ctx context.Context, pageScope entities.PageScope) ([]entities.ProviderRequest, entities.PageScope, error) {
	ret := _mock.Called(ctx, pageScope)

	if len(ret) == 0 {
		panic("no return value specified for GetProviderRequests")
	}

	var r0 []entities.ProviderRequest
	var r1 entities.PageScope
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.PageScope) ([]entities.ProviderRequest, entities.PageScope, error)); ok {
		return returnFunc(ctx, pageScope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.PageScope) []entities.ProviderRequest); ok {
		r0 = returnFunc(ctx, pageScope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.ProviderRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.PageScope) entities.PageScope); ok {
		r1 = returnFunc(ctx, pageScope)
	} else {
		r1 = ret.Get(1).(entities.PageScope)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, entities.PageScope) error); ok {
		r2 = returnFunc(ctx, pageScope)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_GetProviderRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProviderRequests'
type MockRepository_GetProviderRequests_Call struct {
	*mock.Call
}

// GetProviderRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - pageScope entities.PageScope
func (_e *MockRepository_Expecter) GetProviderRequests(ctx interface{}, pageScope interface{}) *MockRepository_GetProviderRequests_Call {
	return &MockRepository_GetProviderRequests_Call{Call: _e.mock.On("GetProviderRequests", ctx, pageScope)}
}

func (_c *MockRepository_GetProviderRequests_Call) Run(run func(ctx context.Context, pageScope entities.PageScope)) *MockRepository_GetProviderRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.PageScope
		if args[1] != nil {
			arg1 = args[1].(entities.PageScope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetProviderRequests_Call) Return(providerRequests []entities.ProviderRequest, pageScope1 entities.PageScope, err error) *MockRepository_GetProviderRequests_Call {
	_c.Call.Return(providerRequests, pageScope1, err)
	return _c
}

func (_c *MockRepository_GetProviderRequests_Call) RunAndReturn(run func(ctx context.Context, pageScope entities.PageScope) ([]entities.ProviderRequest, entities.PageScope, error)) *MockRepository_GetProviderRequests_Call {
	_c.Call.Return(run)
	return _c
}

// RejectProviderRequest provides a mock function for the type MockRepository
func (_mock *MockRepository) RejectProviderRequest(ctx context.Context, id string, reviewerID string, comments string) error {
	ret := _mock.Called(ctx, id, reviewerID, comments)

	if len(ret) == 0 {
		panic("no return value specified for RejectProviderRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, id, reviewerID, comments)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RejectProviderRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectProviderRequest'
type MockRepository_RejectProviderRequest_Call struct {
	*mock.Call
}

// RejectProviderRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reviewerID string
//   - comments string
func (_e *MockRepository_Expecter) RejectProviderRequest(ctx interface{}, id interface{}, reviewerID interface{}, comments interface{}) *MockRepository_RejectProviderRequest_Call {
	return &MockRepository_RejectProviderRequest_Call{Call: _e.mock.On("RejectProviderRequest", ctx, id, reviewerID, comments)}
}

func (_c *MockRepository_RejectProviderRequest_Call) Run(run func(ctx context.Context, id string, reviewerID string, comments string)) *MockRepository_RejectProviderRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_RejectProviderRequest_Call) Return(err error) *MockRepository_RejectProviderRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RejectProviderRequest_Call) RunAndReturn(run func(ctx context.Context, id string, reviewerID string, comments string) error) *MockRepository_RejectProviderRequest_Call {
	_c.Call.Return(run)
	return _c
}
