// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/eaguilar88/deu/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// ApproveProviderRequest provides a mock function for the type MockService
func (_mock *MockService) ApproveProviderRequest(ctx context.Context, id string, reviewerID string) error {
	ret := _mock.Called(ctx, id, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for ApproveProviderRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, reviewerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_ApproveProviderRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveProviderRequest'
type MockService_ApproveProviderRequest_Call struct {
	*mock.Call
}

// ApproveProviderRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reviewerID string
func (_e *MockService_Expecter) ApproveProviderRequest(ctx interface{}, id interface{}, reviewerID interface{}) *MockService_ApproveProviderRequest_Call {
	return &MockService_ApproveProviderRequest_Call{Call: _e.mock.On("ApproveProviderRequest", ctx, id, reviewerID)}
}

func (_c *MockService_ApproveProviderRequest_Call) Run(run func(ctx context.Context, id string, reviewerID string)) *MockService_ApproveProviderRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_ApproveProviderRequest_Call) Return(err error) *MockService_ApproveProviderRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_ApproveProviderRequest_Call) RunAndReturn(run func(ctx context.Context, id string, reviewerID string) error) *MockService_ApproveProviderRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetProviderRequestByID provides a mock function for the type MockService
func (_mock *MockService) GetProviderRequestByID(ctx context.Context, id string) (entities.ProviderRequest, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProviderRequestByID")
	}

	var r0 entities.ProviderRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entities.ProviderRequest, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entities.ProviderRequest); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.ProviderRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetProviderRequestByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProviderRequestByID'
type MockService_GetProviderRequestByID_Call struct {
	*mock.Call
}

// GetProviderRequestByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) GetProviderRequestByID(ctx interface{}, id interface{}) *MockService_GetProviderRequestByID_Call {
	return &MockService_GetProviderRequestByID_Call{Call: _e.mock.On("GetProviderRequestByID", ctx, id)}
}

func (_c *MockService_GetProviderRequestByID_Call) Run(run func(ctx context.Context, id string)) *MockService_GetProviderRequestByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetProviderRequestByID_Call) Return(providerRequest entities.ProviderRequest, err error) *MockService_GetProviderRequestByID_Call {
	_c.Call.Return(providerRequest, err)
	return _c
}

func (_c *MockService_GetProviderRequestByID_Call) RunAndReturn(run func(ctx context.Context, id string) (entities.ProviderRequest, error)) *MockService_GetProviderRequestByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetProviderRequests provides a mock function for the type MockService
func (_mock *MockService) GetProviderRequests(ctx context.Context, faculty entities.Faculty, pageScope entities.PageScope) ([]entities.ProviderRequest, entities.PageScope, error) {
	ret := _mock.Called(ctx, faculty, pageScope)

	if len(ret) == 0 {
		panic("no return value specified for GetProviderRequests")
	}

	var r0 []entities.ProviderRequest
	var r1 entities.PageScope
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Faculty, entities.PageScope) ([]entities.ProviderRequest, entities.PageScope, error)); ok {
		return returnFunc(ctx, faculty, pageScope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Faculty, entities.PageScope) []entities.ProviderRequest); ok {
		r0 = returnFunc(ctx, faculty, pageScope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.ProviderRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Faculty, entities.PageScope) entities.PageScope); ok {
		r1 = returnFunc(ctx, faculty, pageScope)
	} else {
		r1 = ret.Get(1).(entities.PageScope)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, entities.Faculty, entities.PageScope) error); ok {
		r2 = returnFunc(ctx, faculty, pageScope)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_GetProviderRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProviderRequests'
type MockService_GetProviderRequests_Call struct {
	*mock.Call
}

// GetProviderRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - faculty entities.Faculty
//   - pageScope entities.PageScope
func (_e *MockService_Expecter) GetProviderRequests(ctx interface{}, faculty interface{}, pageScope interface{}) *MockService_GetProviderRequests_Call {
	return &MockService_GetProviderRequests_Call{Call: _e.mock.On("GetProviderRequests", ctx, faculty, pageScope)}
}

func (_c *MockService_GetProviderRequests_Call) Run(run func(ctx context.Context, faculty entities.Faculty, pageScope entities.PageScope)) *MockService_GetProviderRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Faculty
		if args[1] != nil {
			arg1 = args[1].(entities.Faculty)
		}
		var arg2 entities.PageScope
		if args[2] != nil {
			arg2 = args[2].(entities.PageScope)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_GetProviderRequests_Call) Return(providerRequests []entities.ProviderRequest, pageScope1 entities.PageScope, err error) *MockService_GetProviderRequests_Call {
	_c.Call.Return(providerRequests, pageScope1, err)
	return _c
}

func (_c *MockService_GetProviderRequests_Call) RunAndReturn(run func(ctx context.Context, faculty entities.Faculty, pageScope entities.PageScope) ([]entities.ProviderRequest, entities.PageScope, error)) *MockService_GetProviderRequests_Call {
	_c.Call.Return(run)
	return _c
}

// RejectProviderRequest provides a mock function for the type MockService
func (_mock *MockService) RejectProviderRequest(ctx context.Context, id string, reviewerID string, comments string) error {
	ret := _mock.Called(ctx, id, reviewerID, comments)

	if len(ret) == 0 {
		panic("no return value specified for RejectProviderRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, id, reviewerID, comments)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RejectProviderRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectProviderRequest'
type MockService_RejectProviderRequest_Call struct {
	*mock.Call
}

// RejectProviderRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reviewerID string
//   - comments string
func (_e *MockService_Expecter) RejectProviderRequest(ctx interface{}, id interface{}, reviewerID interface{}, comments interface{}) *MockService_RejectProviderRequest_Call {
	return &MockService_RejectProviderRequest_Call{Call: _e.mock.On("RejectProviderRequest", ctx, id, reviewerID, comments)}
}

func (_c *MockService_RejectProviderRequest_Call) Run(run func(ctx context.Context, id string, reviewerID string, comments string)) *MockService_RejectProviderRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_RejectProviderRequest_Call) Return(err error) *MockService_RejectProviderRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RejectProviderRequest_Call) RunAndReturn(run func(ctx context.Context, id string, reviewerID string, comments string) error) *MockService_RejectProviderRequest_Call {
	_c.Call.Return(run)
	return _c
}
