// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/eaguilar88/deu/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ApproveGroupResourceRequest provides a mock function for the type MockRepository
func (_mock *MockRepository) ApproveGroupResourceRequest(ctx context.Context, reqID string) error {
	ret := _mock.Called(ctx, reqID)

	if len(ret) == 0 {
		panic("no return value specified for ApproveGroupResourceRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, reqID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_ApproveGroupResourceRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveGroupResourceRequest'
type MockRepository_ApproveGroupResourceRequest_Call struct {
	*mock.Call
}

// ApproveGroupResourceRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - reqID string
func (_e *MockRepository_Expecter) ApproveGroupResourceRequest(ctx interface{}, reqID interface{}) *MockRepository_ApproveGroupResourceRequest_Call {
	return &MockRepository_ApproveGroupResourceRequest_Call{Call: _e.mock.On("ApproveGroupResourceRequest", ctx, reqID)}
}

func (_c *MockRepository_ApproveGroupResourceRequest_Call) Run(run func(ctx context.Context, reqID string)) *MockRepository_ApproveGroupResourceRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ApproveGroupResourceRequest_Call) Return(err error) *MockRepository_ApproveGroupResourceRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_ApproveGroupResourceRequest_Call) RunAndReturn(run func(ctx context.Context, reqID string) error) *MockRepository_ApproveGroupResourceRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGroupResourceRequest provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateGroupResourceRequest(ctx context.Context, req entities.GroupResourceRequest) (int64, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroupResourceRequest")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.GroupResourceRequest) (int64, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.GroupResourceRequest) int64); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.GroupResourceRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateGroupResourceRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroupResourceRequest'
type MockRepository_CreateGroupResourceRequest_Call struct {
	*mock.Call
}

// CreateGroupResourceRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - req entities.GroupResourceRequest
func (_e *MockRepository_Expecter) CreateGroupResourceRequest(ctx interface{}, req interface{}) *MockRepository_CreateGroupResourceRequest_Call {
	return &MockRepository_CreateGroupResourceRequest_Call{Call: _e.mock.On("CreateGroupResourceRequest", ctx, req)}
}

func (_c *MockRepository_CreateGroupResourceRequest_Call) Run(run func(ctx context.Context, req entities.GroupResourceRequest)) *MockRepository_CreateGroupResourceRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.GroupResourceRequest
		if args[1] != nil {
			arg1 = args[1].(entities.GroupResourceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateGroupResourceRequest_Call) Return(n int64, err error) *MockRepository_CreateGroupResourceRequest_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_CreateGroupResourceRequest_Call) RunAndReturn(run func(ctx context.Context, req entities.GroupResourceRequest) (int64, error)) *MockRepository_CreateGroupResourceRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupResourceRequestByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetGroupResourceRequestByID(ctx context.Context, reqID string) (entities.GroupResourceRequest, error) {
	ret := _mock.Called(ctx, reqID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupResourceRequestByID")
	}

	var r0 entities.GroupResourceRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entities.GroupResourceRequest, error)); ok {
		return returnFunc(ctx, reqID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entities.GroupResourceRequest); ok {
		r0 = returnFunc(ctx, reqID)
	} else {
		r0 = ret.Get(0).(entities.GroupResourceRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, reqID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetGroupResourceRequestByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupResourceRequestByID'
type MockRepository_GetGroupResourceRequestByID_Call struct {
	*mock.Call
}

// GetGroupResourceRequestByID is a helper method to define mock.On call
//   - ctx context.Context
//   - reqID string
func (_e *MockRepository_Expecter) GetGroupResourceRequestByID(ctx interface{}, reqID interface{}) *MockRepository_GetGroupResourceRequestByID_Call {
	return &MockRepository_GetGroupResourceRequestByID_Call{Call: _e.mock.On("GetGroupResourceRequestByID", ctx, reqID)}
}

func (_c *MockRepository_GetGroupResourceRequestByID_Call) Run(run func(ctx context.Context, reqID string)) *MockRepository_GetGroupResourceRequestByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetGroupResourceRequestByID_Call) Return(groupResourceRequest entities.GroupResourceRequest, err error) *MockRepository_GetGroupResourceRequestByID_Call {
	_c.Call.Return(groupResourceRequest, err)
	return _c
}

func (_c *MockRepository_GetGroupResourceRequestByID_Call) RunAndReturn(run func(ctx context.Context, reqID string) (entities.GroupResourceRequest, error)) *MockRepository_GetGroupResourceRequestByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupResourceRequestsByFaculty provides a mock function for the type MockRepository
func (_mock *MockRepository) GetGroupResourceRequestsByFaculty(ctx context.Context, faculty entities.Faculty, pageScope entities.PageScope) ([]entities.GroupResourceRequest, entities.PageScope, error) {
	ret := _mock.Called(ctx, faculty, pageScope)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupResourceRequestsByFaculty")
	}

	var r0 []entities.GroupResourceRequest
	var r1 entities.PageScope
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Faculty, entities.PageScope) ([]entities.GroupResourceRequest, entities.PageScope, error)); ok {
		return returnFunc(ctx, faculty, pageScope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Faculty, entities.PageScope) []entities.GroupResourceRequest); ok {
		r0 = returnFunc(ctx, faculty, pageScope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.GroupResourceRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Faculty, entities.PageScope) entities.PageScope); ok {
		r1 = returnFunc(ctx, faculty, pageScope)
	} else {
		r1 = ret.Get(1).(entities.PageScope)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, entities.Faculty, entities.PageScope) error); ok {
		r2 = returnFunc(ctx, faculty, pageScope)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_GetGroupResourceRequestsByFaculty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupResourceRequestsByFaculty'
type MockRepository_GetGroupResourceRequestsByFaculty_Call struct {
	*mock.Call
}

// GetGroupResourceRequestsByFaculty is a helper method to define mock.On call
//   - ctx context.Context
//   - faculty entities.Faculty
//   - pageScope entities.PageScope
func (_e *MockRepository_Expecter) GetGroupResourceRequestsByFaculty(ctx interface{}, faculty interface{}, pageScope interface{}) *MockRepository_GetGroupResourceRequestsByFaculty_Call {
	return &MockRepository_GetGroupResourceRequestsByFaculty_Call{Call: _e.mock.On("GetGroupResourceRequestsByFaculty", ctx, faculty, pageScope)}
}

func (_c *MockRepository_GetGroupResourceRequestsByFaculty_Call) Run(run func(ctx context.Context, faculty entities.Faculty, pageScope entities.PageScope)) *MockRepository_GetGroupResourceRequestsByFaculty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Faculty
		if args[1] != nil {
			arg1 = args[1].(entities.Faculty)
		}
		var arg2 entities.PageScope
		if args[2] != nil {
			arg2 = args[2].(entities.PageScope)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_GetGroupResourceRequestsByFaculty_Call) Return(groupResourceRequests []entities.GroupResourceRequest, pageScope1 entities.PageScope, err error) *MockRepository_GetGroupResourceRequestsByFaculty_Call {
	_c.Call.Return(groupResourceRequests, pageScope1, err)
	return _c
}

func (_c *MockRepository_GetGroupResourceRequestsByFaculty_Call) RunAndReturn(run func(ctx context.Context, faculty entities.Faculty, pageScope entities.PageScope) ([]entities.GroupResourceRequest, entities.PageScope, error)) *MockRepository_GetGroupResourceRequestsByFaculty_Call {
	_c.Call.Return(run)
	return _c
}

// RejectGroupResourceRequest provides a mock function for the type MockRepository
func (_mock *MockRepository) RejectGroupResourceRequest(ctx context.Context, reqID string) error {
	ret := _mock.Called(ctx, reqID)

	if len(ret) == 0 {
		panic("no return value specified for RejectGroupResourceRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, reqID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RejectGroupResourceRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectGroupResourceRequest'
type MockRepository_RejectGroupResourceRequest_Call struct {
	*mock.Call
}

// RejectGroupResourceRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - reqID string
func (_e *MockRepository_Expecter) RejectGroupResourceRequest(ctx interface{}, reqID interface{}) *MockRepository_RejectGroupResourceRequest_Call {
	return &MockRepository_RejectGroupResourceRequest_Call{Call: _e.mock.On("RejectGroupResourceRequest", ctx, reqID)}
}

func (_c *MockRepository_RejectGroupResourceRequest_Call) Run(run func(ctx context.Context, reqID string)) *MockRepository_RejectGroupResourceRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_RejectGroupResourceRequest_Call) Return(err error) *MockRepository_RejectGroupResourceRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RejectGroupResourceRequest_Call) RunAndReturn(run func(ctx context.Context, reqID string) error) *MockRepository_RejectGroupResourceRequest_Call {
	_c.Call.Return(run)
	return _c
}
