// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/eaguilar88/deu/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateCourse provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateCourse(ctx context.Context, course entities.Course) (int64, error) {
	ret := _mock.Called(ctx, course)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourse")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Course) (int64, error)); ok {
		return returnFunc(ctx, course)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Course) int64); ok {
		r0 = returnFunc(ctx, course)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Course) error); ok {
		r1 = returnFunc(ctx, course)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCourse'
type MockRepository_CreateCourse_Call struct {
	*mock.Call
}

// CreateCourse is a helper method to define mock.On call
//   - ctx context.Context
//   - course entities.Course
func (_e *MockRepository_Expecter) CreateCourse(ctx interface{}, course interface{}) *MockRepository_CreateCourse_Call {
	return &MockRepository_CreateCourse_Call{Call: _e.mock.On("CreateCourse", ctx, course)}
}

func (_c *MockRepository_CreateCourse_Call) Run(run func(ctx context.Context, course entities.Course)) *MockRepository_CreateCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Course
		if args[1] != nil {
			arg1 = args[1].(entities.Course)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateCourse_Call) Return(n int64, err error) *MockRepository_CreateCourse_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_CreateCourse_Call) RunAndReturn(run func(ctx context.Context, course entities.Course) (int64, error)) *MockRepository_CreateCourse_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCourseRequest provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateCourseRequest(ctx context.Context, request entities.CourseRequest) (int64, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourseRequest")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.CourseRequest) (int64, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.CourseRequest) int64); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.CourseRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateCourseRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCourseRequest'
type MockRepository_CreateCourseRequest_Call struct {
	*mock.Call
}

// CreateCourseRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - request entities.CourseRequest
func (_e *MockRepository_Expecter) CreateCourseRequest(ctx interface{}, request interface{}) *MockRepository_CreateCourseRequest_Call {
	return &MockRepository_CreateCourseRequest_Call{Call: _e.mock.On("CreateCourseRequest", ctx, request)}
}

func (_c *MockRepository_CreateCourseRequest_Call) Run(run func(ctx context.Context, request entities.CourseRequest)) *MockRepository_CreateCourseRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.CourseRequest
		if args[1] != nil {
			arg1 = args[1].(entities.CourseRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateCourseRequest_Call) Return(n int64, err error) *MockRepository_CreateCourseRequest_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_CreateCourseRequest_Call) RunAndReturn(run func(ctx context.Context, request entities.CourseRequest) (int64, error)) *MockRepository_CreateCourseRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCourseWithRequest provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateCourseWithRequest(ctx context.Context, course entities.Course) (int64, int64, error) {
	ret := _mock.Called(ctx, course)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourseWithRequest")
	}

	var r0 int64
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Course) (int64, int64, error)); ok {
		return returnFunc(ctx, course)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Course) int64); ok {
		r0 = returnFunc(ctx, course)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Course) int64); ok {
		r1 = returnFunc(ctx, course)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, entities.Course) error); ok {
		r2 = returnFunc(ctx, course)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_CreateCourseWithRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCourseWithRequest'
type MockRepository_CreateCourseWithRequest_Call struct {
	*mock.Call
}

// CreateCourseWithRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - course entities.Course
func (_e *MockRepository_Expecter) CreateCourseWithRequest(ctx interface{}, course interface{}) *MockRepository_CreateCourseWithRequest_Call {
	return &MockRepository_CreateCourseWithRequest_Call{Call: _e.mock.On("CreateCourseWithRequest", ctx, course)}
}

func (_c *MockRepository_CreateCourseWithRequest_Call) Run(run func(ctx context.Context, course entities.Course)) *MockRepository_CreateCourseWithRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Course
		if args[1] != nil {
			arg1 = args[1].(entities.Course)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateCourseWithRequest_Call) Return(courseID int64, requestID int64, err error) *MockRepository_CreateCourseWithRequest_Call {
	_c.Call.Return(courseID, requestID, err)
	return _c
}

func (_c *MockRepository_CreateCourseWithRequest_Call) RunAndReturn(run func(ctx context.Context, course entities.Course) (int64, int64, error)) *MockRepository_CreateCourseWithRequest_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCourse provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteCourse(ctx context.Context, courseID string) error {
	ret := _mock.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCourse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, courseID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCourse'
type MockRepository_DeleteCourse_Call struct {
	*mock.Call
}

// DeleteCourse is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID string
func (_e *MockRepository_Expecter) DeleteCourse(ctx interface{}, courseID interface{}) *MockRepository_DeleteCourse_Call {
	return &MockRepository_DeleteCourse_Call{Call: _e.mock.On("DeleteCourse", ctx, courseID)}
}

func (_c *MockRepository_DeleteCourse_Call) Run(run func(ctx context.Context, courseID string)) *MockRepository_DeleteCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteCourse_Call) Return(err error) *MockRepository_DeleteCourse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteCourse_Call) RunAndReturn(run func(ctx context.Context, courseID string) error) *MockRepository_DeleteCourse_Call {
	_c.Call.Return(run)
	return _c
}

// GetCourse provides a mock function for the type MockRepository
func (_mock *MockRepository) GetCourse(ctx context.Context, courseID string) (entities.Course, error) {
	ret := _mock.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for GetCourse")
	}

	var r0 entities.Course
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entities.Course, error)); ok {
		return returnFunc(ctx, courseID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entities.Course); ok {
		r0 = returnFunc(ctx, courseID)
	} else {
		r0 = ret.Get(0).(entities.Course)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, courseID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCourse'
type MockRepository_GetCourse_Call struct {
	*mock.Call
}

// GetCourse is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID string
func (_e *MockRepository_Expecter) GetCourse(ctx interface{}, courseID interface{}) *MockRepository_GetCourse_Call {
	return &MockRepository_GetCourse_Call{Call: _e.mock.On("GetCourse", ctx, courseID)}
}

func (_c *MockRepository_GetCourse_Call) Run(run func(ctx context.Context, courseID string)) *MockRepository_GetCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetCourse_Call) Return(course entities.Course, err error) *MockRepository_GetCourse_Call {
	_c.Call.Return(course, err)
	return _c
}

func (_c *MockRepository_GetCourse_Call) RunAndReturn(run func(ctx context.Context, courseID string) (entities.Course, error)) *MockRepository_GetCourse_Call {
	_c.Call.Return(run)
	return _c
}

// GetCourses provides a mock function for the type MockRepository
func (_mock *MockRepository) GetCourses(ctx context.Context, pageScope entities.PageScope) ([]entities.Course, entities.PageScope, error) {
	ret := _mock.Called(ctx, pageScope)

	if len(ret) == 0 {
		panic("no return value specified for GetCourses")
	}

	var r0 []entities.Course
	var r1 entities.PageScope
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.PageScope) ([]entities.Course, entities.PageScope, error)); ok {
		return returnFunc(ctx, pageScope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.PageScope) []entities.Course); ok {
		r0 = returnFunc(ctx, pageScope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Course)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.PageScope) entities.PageScope); ok {
		r1 = returnFunc(ctx, pageScope)
	} else {
		r1 = ret.Get(1).(entities.PageScope)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, entities.PageScope) error); ok {
		r2 = returnFunc(ctx, pageScope)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_GetCourses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCourses'
type MockRepository_GetCourses_Call struct {
	*mock.Call
}

// GetCourses is a helper method to define mock.On call
//   - ctx context.Context
//   - pageScope entities.PageScope
func (_e *MockRepository_Expecter) GetCourses(ctx interface{}, pageScope interface{}) *MockRepository_GetCourses_Call {
	return &MockRepository_GetCourses_Call{Call: _e.mock.On("GetCourses", ctx, pageScope)}
}

func (_c *MockRepository_GetCourses_Call) Run(run func(ctx context.Context, pageScope entities.PageScope)) *MockRepository_GetCourses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.PageScope
		if args[1] != nil {
			arg1 = args[1].(entities.PageScope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetCourses_Call) Return(courses []entities.Course, pageScope1 entities.PageScope, err error) *MockRepository_GetCourses_Call {
	_c.Call.Return(courses, pageScope1, err)
	return _c
}

func (_c *MockRepository_GetCourses_Call) RunAndReturn(run func(ctx context.Context, pageScope entities.PageScope) ([]entities.Course, entities.PageScope, error)) *MockRepository_GetCourses_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilesByOwner provides a mock function for the type MockRepository
func (_mock *MockRepository) GetFilesByOwner(ctx context.Context, ownerID string, ownerType entities.OwnerType) (entities.GroupedFiles, error) {
	ret := _mock.Called(ctx, ownerID, ownerType)

	if len(ret) == 0 {
		panic("no return value specified for GetFilesByOwner")
	}

	var r0 entities.GroupedFiles
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entities.OwnerType) (entities.GroupedFiles, error)); ok {
		return returnFunc(ctx, ownerID, ownerType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entities.OwnerType) entities.GroupedFiles); ok {
		r0 = returnFunc(ctx, ownerID, ownerType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.GroupedFiles)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, entities.OwnerType) error); ok {
		r1 = returnFunc(ctx, ownerID, ownerType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetFilesByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilesByOwner'
type MockRepository_GetFilesByOwner_Call struct {
	*mock.Call
}

// GetFilesByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - ownerType entities.OwnerType
func (_e *MockRepository_Expecter) GetFilesByOwner(ctx interface{}, ownerID interface{}, ownerType interface{}) *MockRepository_GetFilesByOwner_Call {
	return &MockRepository_GetFilesByOwner_Call{Call: _e.mock.On("GetFilesByOwner", ctx, ownerID, ownerType)}
}

func (_c *MockRepository_GetFilesByOwner_Call) Run(run func(ctx context.Context, ownerID string, ownerType entities.OwnerType)) *MockRepository_GetFilesByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entities.OwnerType
		if args[2] != nil {
			arg2 = args[2].(entities.OwnerType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_GetFilesByOwner_Call) Return(groupedFiles entities.GroupedFiles, err error) *MockRepository_GetFilesByOwner_Call {
	_c.Call.Return(groupedFiles, err)
	return _c
}

func (_c *MockRepository_GetFilesByOwner_Call) RunAndReturn(run func(ctx context.Context, ownerID string, ownerType entities.OwnerType) (entities.GroupedFiles, error)) *MockRepository_GetFilesByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestCoursePeriod provides a mock function for the type MockRepository
func (_mock *MockRepository) GetLatestCoursePeriod(ctx context.Context, courseID string) (entities.CoursePeriod, error) {
	ret := _mock.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestCoursePeriod")
	}

	var r0 entities.CoursePeriod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entities.CoursePeriod, error)); ok {
		return returnFunc(ctx, courseID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entities.CoursePeriod); ok {
		r0 = returnFunc(ctx, courseID)
	} else {
		r0 = ret.Get(0).(entities.CoursePeriod)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, courseID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetLatestCoursePeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestCoursePeriod'
type MockRepository_GetLatestCoursePeriod_Call struct {
	*mock.Call
}

// GetLatestCoursePeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID string
func (_e *MockRepository_Expecter) GetLatestCoursePeriod(ctx interface{}, courseID interface{}) *MockRepository_GetLatestCoursePeriod_Call {
	return &MockRepository_GetLatestCoursePeriod_Call{Call: _e.mock.On("GetLatestCoursePeriod", ctx, courseID)}
}

func (_c *MockRepository_GetLatestCoursePeriod_Call) Run(run func(ctx context.Context, courseID string)) *MockRepository_GetLatestCoursePeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetLatestCoursePeriod_Call) Return(coursePeriod entities.CoursePeriod, err error) *MockRepository_GetLatestCoursePeriod_Call {
	_c.Call.Return(coursePeriod, err)
	return _c
}

func (_c *MockRepository_GetLatestCoursePeriod_Call) RunAndReturn(run func(ctx context.Context, courseID string) (entities.CoursePeriod, error)) *MockRepository_GetLatestCoursePeriod_Call {
	_c.Call.Return(run)
	return _c
}

// GetProviderByUserID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetProviderByUserID(ctx context.Context, userID string) (entities.Provider, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProviderByUserID")
	}

	var r0 entities.Provider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entities.Provider, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entities.Provider); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(entities.Provider)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetProviderByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProviderByUserID'
type MockRepository_GetProviderByUserID_Call struct {
	*mock.Call
}

// GetProviderByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) GetProviderByUserID(ctx interface{}, userID interface{}) *MockRepository_GetProviderByUserID_Call {
	return &MockRepository_GetProviderByUserID_Call{Call: _e.mock.On("GetProviderByUserID", ctx, userID)}
}

func (_c *MockRepository_GetProviderByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_GetProviderByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetProviderByUserID_Call) Return(provider entities.Provider, err error) *MockRepository_GetProviderByUserID_Call {
	_c.Call.Return(provider, err)
	return _c
}

func (_c *MockRepository_GetProviderByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) (entities.Provider, error)) *MockRepository_GetProviderByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// SaveFilesToDB provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveFilesToDB(ctx context.Context, file []*entities.File) error {
	ret := _mock.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for SaveFilesToDB")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*entities.File) error); ok {
		r0 = returnFunc(ctx, file)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveFilesToDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFilesToDB'
type MockRepository_SaveFilesToDB_Call struct {
	*mock.Call
}

// SaveFilesToDB is a helper method to define mock.On call
//   - ctx context.Context
//   - file []*entities.File
func (_e *MockRepository_Expecter) SaveFilesToDB(ctx interface{}, file interface{}) *MockRepository_SaveFilesToDB_Call {
	return &MockRepository_SaveFilesToDB_Call{Call: _e.mock.On("SaveFilesToDB", ctx, file)}
}

func (_c *MockRepository_SaveFilesToDB_Call) Run(run func(ctx context.Context, file []*entities.File)) *MockRepository_SaveFilesToDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*entities.File
		if args[1] != nil {
			arg1 = args[1].([]*entities.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SaveFilesToDB_Call) Return(err error) *MockRepository_SaveFilesToDB_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveFilesToDB_Call) RunAndReturn(run func(ctx context.Context, file []*entities.File) error) *MockRepository_SaveFilesToDB_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCourse provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateCourse(ctx context.Context, courseID string, user entities.Course) error {
	ret := _mock.Called(ctx, courseID, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCourse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entities.Course) error); ok {
		r0 = returnFunc(ctx, courseID, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCourse'
type MockRepository_UpdateCourse_Call struct {
	*mock.Call
}

// UpdateCourse is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID string
//   - user entities.Course
func (_e *MockRepository_Expecter) UpdateCourse(ctx interface{}, courseID interface{}, user interface{}) *MockRepository_UpdateCourse_Call {
	return &MockRepository_UpdateCourse_Call{Call: _e.mock.On("UpdateCourse", ctx, courseID, user)}
}

func (_c *MockRepository_UpdateCourse_Call) Run(run func(ctx context.Context, courseID string, user entities.Course)) *MockRepository_UpdateCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entities.Course
		if args[2] != nil {
			arg2 = args[2].(entities.Course)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateCourse_Call) Return(err error) *MockRepository_UpdateCourse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateCourse_Call) RunAndReturn(run func(ctx context.Context, courseID string, user entities.Course) error) *MockRepository_UpdateCourse_Call {
	_c.Call.Return(run)
	return _c
}
