// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/eaguilar88/deu/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryMock is an autogenerated mock type for the Repository type
type RepositoryMock struct {
	mock.Mock
}

type RepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryMock) EXPECT() *RepositoryMock_Expecter {
	return &RepositoryMock_Expecter{mock: &_m.Mock}
}

// CreateCourse provides a mock function with given fields: ctx, course
func (_m *RepositoryMock) CreateCourse(ctx context.Context, course entities.Course) (int64, error) {
	ret := _m.Called(ctx, course)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourse")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Course) (int64, error)); ok {
		return rf(ctx, course)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.Course) int64); ok {
		r0 = rf(ctx, course)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.Course) error); ok {
		r1 = rf(ctx, course)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryMock_CreateCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCourse'
type RepositoryMock_CreateCourse_Call struct {
	*mock.Call
}

// CreateCourse is a helper method to define mock.On call
//   - ctx context.Context
//   - course entities.Course
func (_e *RepositoryMock_Expecter) CreateCourse(ctx interface{}, course interface{}) *RepositoryMock_CreateCourse_Call {
	return &RepositoryMock_CreateCourse_Call{Call: _e.mock.On("CreateCourse", ctx, course)}
}

func (_c *RepositoryMock_CreateCourse_Call) Run(run func(ctx context.Context, course entities.Course)) *RepositoryMock_CreateCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.Course))
	})
	return _c
}

func (_c *RepositoryMock_CreateCourse_Call) Return(_a0 int64, _a1 error) *RepositoryMock_CreateCourse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryMock_CreateCourse_Call) RunAndReturn(run func(context.Context, entities.Course) (int64, error)) *RepositoryMock_CreateCourse_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCourseRequest provides a mock function with given fields: ctx, request
func (_m *RepositoryMock) CreateCourseRequest(ctx context.Context, request entities.CourseRequest) (int64, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourseRequest")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.CourseRequest) (int64, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.CourseRequest) int64); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.CourseRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryMock_CreateCourseRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCourseRequest'
type RepositoryMock_CreateCourseRequest_Call struct {
	*mock.Call
}

// CreateCourseRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - request entities.CourseRequest
func (_e *RepositoryMock_Expecter) CreateCourseRequest(ctx interface{}, request interface{}) *RepositoryMock_CreateCourseRequest_Call {
	return &RepositoryMock_CreateCourseRequest_Call{Call: _e.mock.On("CreateCourseRequest", ctx, request)}
}

func (_c *RepositoryMock_CreateCourseRequest_Call) Run(run func(ctx context.Context, request entities.CourseRequest)) *RepositoryMock_CreateCourseRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.CourseRequest))
	})
	return _c
}

func (_c *RepositoryMock_CreateCourseRequest_Call) Return(_a0 int64, _a1 error) *RepositoryMock_CreateCourseRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryMock_CreateCourseRequest_Call) RunAndReturn(run func(context.Context, entities.CourseRequest) (int64, error)) *RepositoryMock_CreateCourseRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCourseWithRequest provides a mock function with given fields: ctx, course
func (_m *RepositoryMock) CreateCourseWithRequest(ctx context.Context, course entities.Course) (int64, int64, error) {
	ret := _m.Called(ctx, course)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourseWithRequest")
	}

	var r0 int64
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Course) (int64, int64, error)); ok {
		return rf(ctx, course)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.Course) int64); ok {
		r0 = rf(ctx, course)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.Course) int64); ok {
		r1 = rf(ctx, course)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entities.Course) error); ok {
		r2 = rf(ctx, course)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RepositoryMock_CreateCourseWithRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCourseWithRequest'
type RepositoryMock_CreateCourseWithRequest_Call struct {
	*mock.Call
}

// CreateCourseWithRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - course entities.Course
func (_e *RepositoryMock_Expecter) CreateCourseWithRequest(ctx interface{}, course interface{}) *RepositoryMock_CreateCourseWithRequest_Call {
	return &RepositoryMock_CreateCourseWithRequest_Call{Call: _e.mock.On("CreateCourseWithRequest", ctx, course)}
}

func (_c *RepositoryMock_CreateCourseWithRequest_Call) Run(run func(ctx context.Context, course entities.Course)) *RepositoryMock_CreateCourseWithRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.Course))
	})
	return _c
}

func (_c *RepositoryMock_CreateCourseWithRequest_Call) Return(courseID int64, requestID int64, err error) *RepositoryMock_CreateCourseWithRequest_Call {
	_c.Call.Return(courseID, requestID, err)
	return _c
}

func (_c *RepositoryMock_CreateCourseWithRequest_Call) RunAndReturn(run func(context.Context, entities.Course) (int64, int64, error)) *RepositoryMock_CreateCourseWithRequest_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCourse provides a mock function with given fields: ctx, courseID
func (_m *RepositoryMock) DeleteCourse(ctx context.Context, courseID string) error {
	ret := _m.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, courseID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryMock_DeleteCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCourse'
type RepositoryMock_DeleteCourse_Call struct {
	*mock.Call
}

// DeleteCourse is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID string
func (_e *RepositoryMock_Expecter) DeleteCourse(ctx interface{}, courseID interface{}) *RepositoryMock_DeleteCourse_Call {
	return &RepositoryMock_DeleteCourse_Call{Call: _e.mock.On("DeleteCourse", ctx, courseID)}
}

func (_c *RepositoryMock_DeleteCourse_Call) Run(run func(ctx context.Context, courseID string)) *RepositoryMock_DeleteCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RepositoryMock_DeleteCourse_Call) Return(_a0 error) *RepositoryMock_DeleteCourse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryMock_DeleteCourse_Call) RunAndReturn(run func(context.Context, string) error) *RepositoryMock_DeleteCourse_Call {
	_c.Call.Return(run)
	return _c
}

// GetCourse provides a mock function with given fields: ctx, courseID
func (_m *RepositoryMock) GetCourse(ctx context.Context, courseID string) (entities.Course, error) {
	ret := _m.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for GetCourse")
	}

	var r0 entities.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.Course, error)); ok {
		return rf(ctx, courseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.Course); ok {
		r0 = rf(ctx, courseID)
	} else {
		r0 = ret.Get(0).(entities.Course)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryMock_GetCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCourse'
type RepositoryMock_GetCourse_Call struct {
	*mock.Call
}

// GetCourse is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID string
func (_e *RepositoryMock_Expecter) GetCourse(ctx interface{}, courseID interface{}) *RepositoryMock_GetCourse_Call {
	return &RepositoryMock_GetCourse_Call{Call: _e.mock.On("GetCourse", ctx, courseID)}
}

func (_c *RepositoryMock_GetCourse_Call) Run(run func(ctx context.Context, courseID string)) *RepositoryMock_GetCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RepositoryMock_GetCourse_Call) Return(_a0 entities.Course, _a1 error) *RepositoryMock_GetCourse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryMock_GetCourse_Call) RunAndReturn(run func(context.Context, string) (entities.Course, error)) *RepositoryMock_GetCourse_Call {
	_c.Call.Return(run)
	return _c
}

// GetCourses provides a mock function with given fields: ctx, pageScope
func (_m *RepositoryMock) GetCourses(ctx context.Context, pageScope entities.PageScope) ([]entities.Course, entities.PageScope, error) {
	ret := _m.Called(ctx, pageScope)

	if len(ret) == 0 {
		panic("no return value specified for GetCourses")
	}

	var r0 []entities.Course
	var r1 entities.PageScope
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.PageScope) ([]entities.Course, entities.PageScope, error)); ok {
		return rf(ctx, pageScope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.PageScope) []entities.Course); ok {
		r0 = rf(ctx, pageScope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.PageScope) entities.PageScope); ok {
		r1 = rf(ctx, pageScope)
	} else {
		r1 = ret.Get(1).(entities.PageScope)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entities.PageScope) error); ok {
		r2 = rf(ctx, pageScope)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RepositoryMock_GetCourses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCourses'
type RepositoryMock_GetCourses_Call struct {
	*mock.Call
}

// GetCourses is a helper method to define mock.On call
//   - ctx context.Context
//   - pageScope entities.PageScope
func (_e *RepositoryMock_Expecter) GetCourses(ctx interface{}, pageScope interface{}) *RepositoryMock_GetCourses_Call {
	return &RepositoryMock_GetCourses_Call{Call: _e.mock.On("GetCourses", ctx, pageScope)}
}

func (_c *RepositoryMock_GetCourses_Call) Run(run func(ctx context.Context, pageScope entities.PageScope)) *RepositoryMock_GetCourses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.PageScope))
	})
	return _c
}

func (_c *RepositoryMock_GetCourses_Call) Return(_a0 []entities.Course, _a1 entities.PageScope, _a2 error) *RepositoryMock_GetCourses_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *RepositoryMock_GetCourses_Call) RunAndReturn(run func(context.Context, entities.PageScope) ([]entities.Course, entities.PageScope, error)) *RepositoryMock_GetCourses_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestCoursePeriod provides a mock function with given fields: ctx, courseID
func (_m *RepositoryMock) GetLatestCoursePeriod(ctx context.Context, courseID string) (entities.CoursePeriod, error) {
	ret := _m.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestCoursePeriod")
	}

	var r0 entities.CoursePeriod
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.CoursePeriod, error)); ok {
		return rf(ctx, courseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.CoursePeriod); ok {
		r0 = rf(ctx, courseID)
	} else {
		r0 = ret.Get(0).(entities.CoursePeriod)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryMock_GetLatestCoursePeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestCoursePeriod'
type RepositoryMock_GetLatestCoursePeriod_Call struct {
	*mock.Call
}

// GetLatestCoursePeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID string
func (_e *RepositoryMock_Expecter) GetLatestCoursePeriod(ctx interface{}, courseID interface{}) *RepositoryMock_GetLatestCoursePeriod_Call {
	return &RepositoryMock_GetLatestCoursePeriod_Call{Call: _e.mock.On("GetLatestCoursePeriod", ctx, courseID)}
}

func (_c *RepositoryMock_GetLatestCoursePeriod_Call) Run(run func(ctx context.Context, courseID string)) *RepositoryMock_GetLatestCoursePeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RepositoryMock_GetLatestCoursePeriod_Call) Return(_a0 entities.CoursePeriod, _a1 error) *RepositoryMock_GetLatestCoursePeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryMock_GetLatestCoursePeriod_Call) RunAndReturn(run func(context.Context, string) (entities.CoursePeriod, error)) *RepositoryMock_GetLatestCoursePeriod_Call {
	_c.Call.Return(run)
	return _c
}

// GetProviderByUserID provides a mock function with given fields: ctx, userID
func (_m *RepositoryMock) GetProviderByUserID(ctx context.Context, userID string) (entities.Provider, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProviderByUserID")
	}

	var r0 entities.Provider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.Provider, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.Provider); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(entities.Provider)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryMock_GetProviderByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProviderByUserID'
type RepositoryMock_GetProviderByUserID_Call struct {
	*mock.Call
}

// GetProviderByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *RepositoryMock_Expecter) GetProviderByUserID(ctx interface{}, userID interface{}) *RepositoryMock_GetProviderByUserID_Call {
	return &RepositoryMock_GetProviderByUserID_Call{Call: _e.mock.On("GetProviderByUserID", ctx, userID)}
}

func (_c *RepositoryMock_GetProviderByUserID_Call) Run(run func(ctx context.Context, userID string)) *RepositoryMock_GetProviderByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RepositoryMock_GetProviderByUserID_Call) Return(_a0 entities.Provider, _a1 error) *RepositoryMock_GetProviderByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryMock_GetProviderByUserID_Call) RunAndReturn(run func(context.Context, string) (entities.Provider, error)) *RepositoryMock_GetProviderByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCourse provides a mock function with given fields: ctx, courseID, user
func (_m *RepositoryMock) UpdateCourse(ctx context.Context, courseID string, user entities.Course) error {
	ret := _m.Called(ctx, courseID, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.Course) error); ok {
		r0 = rf(ctx, courseID, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryMock_UpdateCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCourse'
type RepositoryMock_UpdateCourse_Call struct {
	*mock.Call
}

// UpdateCourse is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID string
//   - user entities.Course
func (_e *RepositoryMock_Expecter) UpdateCourse(ctx interface{}, courseID interface{}, user interface{}) *RepositoryMock_UpdateCourse_Call {
	return &RepositoryMock_UpdateCourse_Call{Call: _e.mock.On("UpdateCourse", ctx, courseID, user)}
}

func (_c *RepositoryMock_UpdateCourse_Call) Run(run func(ctx context.Context, courseID string, user entities.Course)) *RepositoryMock_UpdateCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entities.Course))
	})
	return _c
}

func (_c *RepositoryMock_UpdateCourse_Call) Return(_a0 error) *RepositoryMock_UpdateCourse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryMock_UpdateCourse_Call) RunAndReturn(run func(context.Context, string, entities.Course) error) *RepositoryMock_UpdateCourse_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepositoryMock creates a new instance of RepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryMock {
	mock := &RepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
