// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/eaguilar88/deu/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// ServiceMock is an autogenerated mock type for the Service type
type ServiceMock struct {
	mock.Mock
}

type ServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceMock) EXPECT() *ServiceMock_Expecter {
	return &ServiceMock_Expecter{mock: &_m.Mock}
}

// CreateCourse provides a mock function with given fields: ctx, userID, course
func (_m *ServiceMock) CreateCourse(ctx context.Context, userID string, course entities.Course) (int64, error) {
	ret := _m.Called(ctx, userID, course)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourse")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.Course) (int64, error)); ok {
		return rf(ctx, userID, course)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.Course) int64); ok {
		r0 = rf(ctx, userID, course)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, entities.Course) error); ok {
		r1 = rf(ctx, userID, course)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceMock_CreateCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCourse'
type ServiceMock_CreateCourse_Call struct {
	*mock.Call
}

// CreateCourse is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - course entities.Course
func (_e *ServiceMock_Expecter) CreateCourse(ctx interface{}, userID interface{}, course interface{}) *ServiceMock_CreateCourse_Call {
	return &ServiceMock_CreateCourse_Call{Call: _e.mock.On("CreateCourse", ctx, userID, course)}
}

func (_c *ServiceMock_CreateCourse_Call) Run(run func(ctx context.Context, userID string, course entities.Course)) *ServiceMock_CreateCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entities.Course))
	})
	return _c
}

func (_c *ServiceMock_CreateCourse_Call) Return(_a0 int64, _a1 error) *ServiceMock_CreateCourse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceMock_CreateCourse_Call) RunAndReturn(run func(context.Context, string, entities.Course) (int64, error)) *ServiceMock_CreateCourse_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCourse provides a mock function with given fields: ctx, courseID
func (_m *ServiceMock) DeleteCourse(ctx context.Context, courseID string) error {
	ret := _m.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, courseID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServiceMock_DeleteCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCourse'
type ServiceMock_DeleteCourse_Call struct {
	*mock.Call
}

// DeleteCourse is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID string
func (_e *ServiceMock_Expecter) DeleteCourse(ctx interface{}, courseID interface{}) *ServiceMock_DeleteCourse_Call {
	return &ServiceMock_DeleteCourse_Call{Call: _e.mock.On("DeleteCourse", ctx, courseID)}
}

func (_c *ServiceMock_DeleteCourse_Call) Run(run func(ctx context.Context, courseID string)) *ServiceMock_DeleteCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ServiceMock_DeleteCourse_Call) Return(_a0 error) *ServiceMock_DeleteCourse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceMock_DeleteCourse_Call) RunAndReturn(run func(context.Context, string) error) *ServiceMock_DeleteCourse_Call {
	_c.Call.Return(run)
	return _c
}

// GetCourse provides a mock function with given fields: ctx, courseID
func (_m *ServiceMock) GetCourse(ctx context.Context, courseID string) (entities.Course, error) {
	ret := _m.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for GetCourse")
	}

	var r0 entities.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.Course, error)); ok {
		return rf(ctx, courseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.Course); ok {
		r0 = rf(ctx, courseID)
	} else {
		r0 = ret.Get(0).(entities.Course)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceMock_GetCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCourse'
type ServiceMock_GetCourse_Call struct {
	*mock.Call
}

// GetCourse is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID string
func (_e *ServiceMock_Expecter) GetCourse(ctx interface{}, courseID interface{}) *ServiceMock_GetCourse_Call {
	return &ServiceMock_GetCourse_Call{Call: _e.mock.On("GetCourse", ctx, courseID)}
}

func (_c *ServiceMock_GetCourse_Call) Run(run func(ctx context.Context, courseID string)) *ServiceMock_GetCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ServiceMock_GetCourse_Call) Return(_a0 entities.Course, _a1 error) *ServiceMock_GetCourse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceMock_GetCourse_Call) RunAndReturn(run func(context.Context, string) (entities.Course, error)) *ServiceMock_GetCourse_Call {
	_c.Call.Return(run)
	return _c
}

// GetCourses provides a mock function with given fields: ctx, pageScope
func (_m *ServiceMock) GetCourses(ctx context.Context, pageScope entities.PageScope) ([]entities.Course, entities.PageScope, error) {
	ret := _m.Called(ctx, pageScope)

	if len(ret) == 0 {
		panic("no return value specified for GetCourses")
	}

	var r0 []entities.Course
	var r1 entities.PageScope
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.PageScope) ([]entities.Course, entities.PageScope, error)); ok {
		return rf(ctx, pageScope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.PageScope) []entities.Course); ok {
		r0 = rf(ctx, pageScope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.PageScope) entities.PageScope); ok {
		r1 = rf(ctx, pageScope)
	} else {
		r1 = ret.Get(1).(entities.PageScope)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entities.PageScope) error); ok {
		r2 = rf(ctx, pageScope)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ServiceMock_GetCourses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCourses'
type ServiceMock_GetCourses_Call struct {
	*mock.Call
}

// GetCourses is a helper method to define mock.On call
//   - ctx context.Context
//   - pageScope entities.PageScope
func (_e *ServiceMock_Expecter) GetCourses(ctx interface{}, pageScope interface{}) *ServiceMock_GetCourses_Call {
	return &ServiceMock_GetCourses_Call{Call: _e.mock.On("GetCourses", ctx, pageScope)}
}

func (_c *ServiceMock_GetCourses_Call) Run(run func(ctx context.Context, pageScope entities.PageScope)) *ServiceMock_GetCourses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.PageScope))
	})
	return _c
}

func (_c *ServiceMock_GetCourses_Call) Return(_a0 []entities.Course, _a1 entities.PageScope, _a2 error) *ServiceMock_GetCourses_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ServiceMock_GetCourses_Call) RunAndReturn(run func(context.Context, entities.PageScope) ([]entities.Course, entities.PageScope, error)) *ServiceMock_GetCourses_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestCoursePeriod provides a mock function with given fields: ctx, courseID
func (_m *ServiceMock) GetLatestCoursePeriod(ctx context.Context, courseID string) (entities.CoursePeriod, error) {
	ret := _m.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestCoursePeriod")
	}

	var r0 entities.CoursePeriod
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.CoursePeriod, error)); ok {
		return rf(ctx, courseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.CoursePeriod); ok {
		r0 = rf(ctx, courseID)
	} else {
		r0 = ret.Get(0).(entities.CoursePeriod)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceMock_GetLatestCoursePeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestCoursePeriod'
type ServiceMock_GetLatestCoursePeriod_Call struct {
	*mock.Call
}

// GetLatestCoursePeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID string
func (_e *ServiceMock_Expecter) GetLatestCoursePeriod(ctx interface{}, courseID interface{}) *ServiceMock_GetLatestCoursePeriod_Call {
	return &ServiceMock_GetLatestCoursePeriod_Call{Call: _e.mock.On("GetLatestCoursePeriod", ctx, courseID)}
}

func (_c *ServiceMock_GetLatestCoursePeriod_Call) Run(run func(ctx context.Context, courseID string)) *ServiceMock_GetLatestCoursePeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ServiceMock_GetLatestCoursePeriod_Call) Return(_a0 entities.CoursePeriod, _a1 error) *ServiceMock_GetLatestCoursePeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceMock_GetLatestCoursePeriod_Call) RunAndReturn(run func(context.Context, string) (entities.CoursePeriod, error)) *ServiceMock_GetLatestCoursePeriod_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCourse provides a mock function with given fields: ctx, courseID, user
func (_m *ServiceMock) UpdateCourse(ctx context.Context, courseID string, user entities.Course) error {
	ret := _m.Called(ctx, courseID, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.Course) error); ok {
		r0 = rf(ctx, courseID, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServiceMock_UpdateCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCourse'
type ServiceMock_UpdateCourse_Call struct {
	*mock.Call
}

// UpdateCourse is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID string
//   - user entities.Course
func (_e *ServiceMock_Expecter) UpdateCourse(ctx interface{}, courseID interface{}, user interface{}) *ServiceMock_UpdateCourse_Call {
	return &ServiceMock_UpdateCourse_Call{Call: _e.mock.On("UpdateCourse", ctx, courseID, user)}
}

func (_c *ServiceMock_UpdateCourse_Call) Run(run func(ctx context.Context, courseID string, user entities.Course)) *ServiceMock_UpdateCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entities.Course))
	})
	return _c
}

func (_c *ServiceMock_UpdateCourse_Call) Return(_a0 error) *ServiceMock_UpdateCourse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceMock_UpdateCourse_Call) RunAndReturn(run func(context.Context, string, entities.Course) error) *ServiceMock_UpdateCourse_Call {
	_c.Call.Return(run)
	return _c
}

// NewServiceMock creates a new instance of ServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceMock {
	mock := &ServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
