// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/eaguilar88/deu/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ClaimJob provides a mock function for the type MockRepository
func (_mock *MockRepository) ClaimJob(ctx context.Context, lease time.Duration) (*entities.Job, error) {
	ret := _mock.Called(ctx, lease)

	if len(ret) == 0 {
		panic("no return value specified for ClaimJob")
	}

	var r0 *entities.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) (*entities.Job, error)); ok {
		return returnFunc(ctx, lease)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) *entities.Job); ok {
		r0 = returnFunc(ctx, lease)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = returnFunc(ctx, lease)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ClaimJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimJob'
type MockRepository_ClaimJob_Call struct {
	*mock.Call
}

// ClaimJob is a helper method to define mock.On call
//   - ctx context.Context
//   - lease time.Duration
func (_e *MockRepository_Expecter) ClaimJob(ctx interface{}, lease interface{}) *MockRepository_ClaimJob_Call {
	return &MockRepository_ClaimJob_Call{Call: _e.mock.On("ClaimJob", ctx, lease)}
}

func (_c *MockRepository_ClaimJob_Call) Run(run func(ctx context.Context, lease time.Duration)) *MockRepository_ClaimJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ClaimJob_Call) Return(job *entities.Job, err error) *MockRepository_ClaimJob_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *MockRepository_ClaimJob_Call) RunAndReturn(run func(ctx context.Context, lease time.Duration) (*entities.Job, error)) *MockRepository_ClaimJob_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteJob provides a mock function for the type MockRepository
func (_mock *MockRepository) CompleteJob(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CompleteJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CompleteJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteJob'
type MockRepository_CompleteJob_Call struct {
	*mock.Call
}

// CompleteJob is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRepository_Expecter) CompleteJob(ctx interface{}, id interface{}) *MockRepository_CompleteJob_Call {
	return &MockRepository_CompleteJob_Call{Call: _e.mock.On("CompleteJob", ctx, id)}
}

func (_c *MockRepository_CompleteJob_Call) Run(run func(ctx context.Context, id int64)) *MockRepository_CompleteJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CompleteJob_Call) Return(err error) *MockRepository_CompleteJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CompleteJob_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockRepository_CompleteJob_Call {
	_c.Call.Return(run)
	return _c
}

// FailJob provides a mock function for the type MockRepository
func (_mock *MockRepository) FailJob(ctx context.Context, id int64, lastError string) error {
	ret := _mock.Called(ctx, id, lastError)

	if len(ret) == 0 {
		panic("no return value specified for FailJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, id, lastError)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_FailJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailJob'
type MockRepository_FailJob_Call struct {
	*mock.Call
}

// FailJob is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - lastError string
func (_e *MockRepository_Expecter) FailJob(ctx interface{}, id interface{}, lastError interface{}) *MockRepository_FailJob_Call {
	return &MockRepository_FailJob_Call{Call: _e.mock.On("FailJob", ctx, id, lastError)}
}

func (_c *MockRepository_FailJob_Call) Run(run func(ctx context.Context, id int64, lastError string)) *MockRepository_FailJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_FailJob_Call) Return(err error) *MockRepository_FailJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_FailJob_Call) RunAndReturn(run func(ctx context.Context, id int64, lastError string) error) *MockRepository_FailJob_Call {
	_c.Call.Return(run)
	return _c
}

// RetryJobLater provides a mock function for the type MockRepository
func (_mock *MockRepository) RetryJobLater(ctx context.Context, id int64, lastError string, delay time.Duration) error {
	ret := _mock.Called(ctx, id, lastError, delay)

	if len(ret) == 0 {
		panic("no return value specified for RetryJobLater")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, id, lastError, delay)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RetryJobLater_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryJobLater'
type MockRepository_RetryJobLater_Call struct {
	*mock.Call
}

// RetryJobLater is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - lastError string
//   - delay time.Duration
func (_e *MockRepository_Expecter) RetryJobLater(ctx interface{}, id interface{}, lastError interface{}, delay interface{}) *MockRepository_RetryJobLater_Call {
	return &MockRepository_RetryJobLater_Call{Call: _e.mock.On("RetryJobLater", ctx, id, lastError, delay)}
}

func (_c *MockRepository_RetryJobLater_Call) Run(run func(ctx context.Context, id int64, lastError string, delay time.Duration)) *MockRepository_RetryJobLater_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_RetryJobLater_Call) Return(err error) *MockRepository_RetryJobLater_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RetryJobLater_Call) RunAndReturn(run func(ctx context.Context, id int64, lastError string, delay time.Duration) error) *MockRepository_RetryJobLater_Call {
	_c.Call.Return(run)
	return _c
}
