name: Run Go Tests
run-name: ${{github.actor}} is running Go app tests
on:
  push:
    branches:
      - development
      - main

jobs:
  run-with-coverage:
    name: Run Go Tests with Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run tests
      run: go test backend/... -race -short -cover -count=1
